// The ten presentation skins. Each is data — a palette, a self-hosted OFL font set, a decor mode, and the
// handful of layouts it draws structurally differently. Palettes and font stacks are transcribed
// from the reference deck (Templates.dc.html); the shared layouts render every other slide kind in
// the same voice. Skins are a self-contained fixed-palette layer (see types.ts).
import { NoirCover, NoirQuote, NorthStatement, PressProse } from './layouts/overrides';
import type { SlideSkin, SlideSkinId } from './types';

const SELF_HOSTED_FONTS = '/fonts/fonts.css';
// Skin labels belong in the style picker, never on the finished slide. A person may choose Press,
// Lumen, or another skin purely for its visual language; printing that internal style name makes it
// look like the deck belongs to a fictitious publisher/clinic/company. Present, PDF, and PPTX all
// render this shared output brand through SlideStage, so one neutral value keeps all three honest.
const OUTPUT_BRAND = { name: 'MAVÉA', tagline: 'A Mavéa presentation' };

export const folio: SlideSkin = {
  id: 'folio',
  label: 'Folio',
  archetype: 'Editorial',
  blurb: 'Warm editorial — Newsreader serif, hairlines, a deep-pine divider.',
  brand: OUTPUT_BRAND,
  decor: 'none',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Newsreader', serif",
    body: "'Hanken Grotesk', sans-serif",
    displayWeight: 500,
  },
  tokens: {
    paper: '#F4F1EA',
    ink: '#1A1916',
    muted: '#4A463D',
    faint: '#8A8478',
    accent: '#B98C46',
    tint: '#ECE3CF',
    rule: '#D8D3C7',
    ruleStrong: '#1A1916',
    track: '#E4DECF',
    card: '#FBFAF6',
    darkSurface: '#1E3A32',
    darkInk: '#F4F1EA',
    darkAccent: '#C9A766',
    radius: 4,
    pad: '92px 120px',
    accentInk: '#8A6420',
    elevation: 'soft',
    texture: 'paper',
  },
  layouts: {},
};

export const meridian: SlideSkin = {
  id: 'meridian',
  label: 'Meridian',
  archetype: 'Corporate',
  blurb: 'Boardroom-grade — Source Serif headings, IBM Plex body, ruled and precise.',
  brand: OUTPUT_BRAND,
  decor: 'none',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Source Serif 4', serif",
    body: "'IBM Plex Sans', sans-serif",
    displayWeight: 700,
  },
  tokens: {
    paper: '#FFFFFF',
    ink: '#0E2235',
    muted: '#5B6B7B',
    faint: '#9AA6B0',
    accent: '#1763C6',
    accent2: '#6FA8FF',
    tint: '#EAF1FB',
    rule: '#D9E0E6',
    ruleStrong: '#0E2235',
    track: '#E6ECF1',
    card: '#F7FAFD',
    darkSurface: '#0E2235',
    darkInk: '#FFFFFF',
    darkAccent: '#6FA8FF',
    radius: 6,
    pad: '92px 120px',
    elevation: 'soft',
  },
  layouts: {},
};

export const noir: SlideSkin = {
  id: 'noir',
  label: 'Noir',
  archetype: 'Luxury',
  blurb: 'Black-and-gold luxury — Bodoni Moda, centred, whisper-quiet.',
  brand: OUTPUT_BRAND,
  decor: 'none',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Bodoni Moda', serif",
    body: "'Hanken Grotesk', sans-serif",
    displayWeight: 600,
  },
  tokens: {
    paper: '#0C0C0D',
    ink: '#F2EFE9',
    muted: 'rgba(242,239,233,0.62)',
    faint: 'rgba(242,239,233,0.4)',
    accent: '#C9A227',
    tint: 'rgba(201,162,39,0.14)',
    rule: 'rgba(242,239,233,0.16)',
    ruleStrong: 'rgba(242,239,233,0.6)',
    track: 'rgba(242,239,233,0.12)',
    card: 'rgba(242,239,233,0.05)',
    darkSurface: '#161616',
    darkInk: '#F2EFE9',
    darkAccent: '#C9A227',
    dark: true,
    radius: 2,
    pad: '110px 150px',
    texture: 'linen',
  },
  layouts: { cover: NoirCover, quote: NoirQuote },
};

export const north: SlideSkin = {
  id: 'north',
  label: 'North',
  archetype: 'Startup',
  blurb: 'High-energy pitch — Space Grotesk, electric blue + coral, bold geometry.',
  brand: OUTPUT_BRAND,
  decor: 'geo',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Space Grotesk', sans-serif",
    body: "'Hanken Grotesk', sans-serif",
    displayWeight: 700,
  },
  tokens: {
    paper: '#FFFFFF',
    ink: '#111111',
    muted: '#444444',
    faint: '#9A9A9A',
    accent: '#2C4BFF',
    accent2: '#FF5436',
    tint: '#EAEDFF',
    rule: '#E6E6E6',
    ruleStrong: '#111111',
    track: '#ECECEC',
    card: '#FFFFFF',
    darkSurface: '#2C4BFF',
    darkInk: '#FFFFFF',
    darkAccent: '#FF5436',
    radius: 18,
    pad: '92px 120px',
    elevation: 'raised',
    decorStrength: 1.2,
  },
  layouts: { quote: NorthStatement },
};

export const lumen: SlideSkin = {
  id: 'lumen',
  label: 'Lumen',
  archetype: 'Clinical',
  blurb: 'Evidence-first clinical — Libre Franklin, clinical teal, calm and trustworthy.',
  brand: OUTPUT_BRAND,
  decor: 'none',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Libre Franklin', sans-serif",
    body: "'Libre Franklin', sans-serif",
    displayWeight: 800,
  },
  tokens: {
    paper: '#FFFFFF',
    ink: '#102A33',
    muted: '#4A6670',
    faint: '#7E97A0',
    accent: '#0E7C86',
    tint: '#EAF4F4',
    rule: '#DCE6E7',
    ruleStrong: '#102A33',
    track: '#E4EFEF',
    card: '#F1F7F7',
    darkSurface: '#102A33',
    darkInk: '#FFFFFF',
    darkAccent: '#5FC7CF',
    radius: 18,
    pad: '92px 120px',
    elevation: 'soft',
  },
  layouts: {},
};

export const grid: SlideSkin = {
  id: 'grid',
  label: 'Grid',
  archetype: 'Swiss',
  blurb: 'International-style — Archivo black, a visible grid, hard red, sharp edges.',
  brand: OUTPUT_BRAND,
  decor: 'grid',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Archivo', sans-serif",
    body: "'Archivo', sans-serif",
    displayWeight: 900,
    bodyWeight: 600,
  },
  tokens: {
    paper: '#FFFFFF',
    ink: '#111111',
    muted: '#6A6A6A',
    faint: '#9A9A9A',
    accent: '#E8330A',
    tint: '#FDEDEA',
    rule: '#ECECEC',
    ruleStrong: '#111111',
    track: '#ECECEC',
    card: '#FFFFFF',
    darkSurface: '#111111',
    darkInk: '#FFFFFF',
    darkAccent: '#E8330A',
    radius: 0,
    pad: '110px 120px',
    accentInk: '#C92C06',
    decorStrength: 1.4,
  },
  layouts: {},
};

export const terra: SlideSkin = {
  id: 'terra',
  label: 'Terra',
  archetype: 'Organic',
  blurb: 'Warm and crafted — Instrument Serif, clay + olive, organic shapes.',
  brand: OUTPUT_BRAND,
  decor: 'organic',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Instrument Serif', serif",
    body: "'Hanken Grotesk', sans-serif",
    displayWeight: 400,
  },
  tokens: {
    paper: '#ECE3D5',
    ink: '#3A2E25',
    muted: '#5A4D3F',
    faint: '#8A7E6F',
    accent: '#B5503A',
    accent2: '#6B6A41',
    tint: '#E3D8C5',
    rule: '#C9BBA6',
    ruleStrong: '#3A2E25',
    track: '#D9CDB8',
    card: '#F3ECDD',
    darkSurface: '#3A2E25',
    darkInk: '#ECE3D5',
    darkAccent: '#E0A07F',
    radius: 16,
    pad: '96px 130px',
    accentInk: '#9E4230',
    elevation: 'soft',
    texture: 'paper',
  },
  layouts: {},
};

export const cobalt: SlideSkin = {
  id: 'cobalt',
  label: 'Cobalt',
  archetype: 'Deep-tech',
  blurb: 'Data-native — Space Grotesk + IBM Plex Mono, midnight navy, teal + a dot grid.',
  brand: OUTPUT_BRAND,
  decor: 'dots',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Space Grotesk', sans-serif",
    body: "'Space Grotesk', sans-serif",
    mono: "'IBM Plex Mono', monospace",
    displayWeight: 700,
  },
  tokens: {
    paper: '#0E1424',
    ink: '#E6E9F2',
    muted: '#9AA4BE',
    faint: 'rgba(230,233,242,0.5)',
    accent: '#46E0B0',
    accent2: '#6E8BFF',
    tint: 'rgba(70,224,176,0.12)',
    rule: 'rgba(110,139,255,0.24)',
    ruleStrong: 'rgba(230,233,242,0.6)',
    track: 'rgba(230,233,242,0.14)',
    card: '#16203A',
    darkSurface: '#16203A',
    darkInk: '#E6E9F2',
    darkAccent: '#46E0B0',
    dark: true,
    radius: 18,
    pad: '100px 130px',
    elevation: 'glow',
    decorStrength: 1.7,
    flourish: '#5AF0BE',
  },
  layouts: {},
};

export const press: SlideSkin = {
  id: 'press',
  label: 'Press',
  archetype: 'Academic',
  blurb: 'Scholarly — all-serif Spectral, drop caps, a deep academic red.',
  brand: OUTPUT_BRAND,
  decor: 'none',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Spectral', serif",
    body: "'Spectral', serif",
    displayWeight: 600,
    allSerif: true,
  },
  tokens: {
    paper: '#F3EEE3',
    ink: '#221C16',
    muted: '#5A4D3F',
    faint: '#8A7E6F',
    accent: '#6E1423',
    tint: '#EFE4D5',
    rule: '#D6CDBC',
    ruleStrong: '#221C16',
    track: '#DDD3C1',
    card: '#F8F3E9',
    darkSurface: '#221C16',
    darkInk: '#F3EEE3',
    darkAccent: '#C98A93',
    radius: 4,
    pad: '110px 150px',
    texture: 'paper',
  },
  layouts: { prose: PressProse },
};

export const sol: SlideSkin = {
  id: 'sol',
  label: 'Sol',
  archetype: 'Classroom',
  blurb: 'Bright and friendly — Hanken Grotesk, teal/yellow/coral, rounded and playful.',
  brand: OUTPUT_BRAND,
  decor: 'playful',
  fonts: {
    href: SELF_HOSTED_FONTS,
    display: "'Hanken Grotesk', sans-serif",
    body: "'Hanken Grotesk', sans-serif",
    displayWeight: 800,
  },
  tokens: {
    paper: '#FFFDF7',
    ink: '#28323A',
    muted: '#5C6770',
    faint: '#94A0A8',
    accent: '#1FA29A',
    accent2: '#F4B12A',
    tint: '#E3F4F2',
    rule: '#E6E0D2',
    ruleStrong: '#28323A',
    track: '#EAE4D6',
    card: '#FFF4DC',
    darkSurface: '#1FA29A',
    darkInk: '#FFFFFF',
    darkAccent: '#FFE08A',
    radius: 26,
    pad: '92px 120px',
    accentInk: '#178079',
    elevation: 'raised',
  },
  layouts: {},
};

export const SLIDE_SKINS: Record<SlideSkinId, SlideSkin> = {
  folio,
  meridian,
  noir,
  north,
  lumen,
  grid,
  terra,
  cobalt,
  press,
  sol,
};

/** Gallery order — light → dark, editorial → expressive. */
export const SLIDE_SKIN_ORDER: SlideSkinId[] = [
  'folio',
  'meridian',
  'lumen',
  'press',
  'grid',
  'north',
  'sol',
  'terra',
  'noir',
  'cobalt',
];

const SUGGEST: [SlideSkinId, RegExp][] = [
  ['meridian', /financ|business|market|invest|revenue|strateg|quarter|sales/i],
  ['lumen', /health|medic|clinic|biolog|patient|disease|wellness|nutrition|fitness/i],
  ['press', /research|science|academ|study|paper|theor|hypothes|literature/i],
  ['cobalt', /tech|software|engineer|\bai\b|data|platform|system|architecture|code|cloud/i],
  [
    'sol',
    /education|school|\blearn|classroom|\bclass\b|teach|student|\bcourse\b|lesson|kindergarten/i,
  ],
  ['noir', /luxury|fashion|brand|design|premium|art\b|gallery/i],
  ['terra', /food|nature|sustain|craft|travel|garden|environment|recipe|farm/i],
  ['north', /startup|product|pitch|launch|growth|founder|venture/i],
];

/** Pre-select a fitting skin from the answer's domain; the user can override. */
export function suggestSlideSkin(topic?: string): SlideSkinId {
  const s = topic ?? '';
  for (const [id, re] of SUGGEST) if (re.test(s)) return id;
  return 'folio';
}
