// Image, audio, video, and diagram block examples (split from authoredExamples.ts).
// Entries verbatim — do not edit content.
export const MEDIA_EXAMPLES: Record<string, Record<string, unknown>> = {
  waveform: {
    title: 'Podcast Episode',
    icon: 'speaker',
    iconColor: 'var(--presence)',
    durationLabel: '45:32',
    color: 'var(--presence)',
    position: 28,
    bars: [
      0.2, 0.15, 0.35, 0.4, 0.28, 0.32, 0.45, 0.38, 0.42, 0.35, 0.28, 0.25, 0.18, 0.22, 0.3, 0.35,
    ],
    markers: [
      {
        at: 12,
        label: 'Guest intro',
      },
      {
        at: 35,
        label: 'Main topic',
      },
      {
        at: 75,
        label: 'Q&A starts',
      },
    ],
    footer: 'Click or drag the waveform to scrub through the episode',
  },
  diagram: {
    title: 'Anatomy of a flower',
    icon: 'image',
    iconColor: 'var(--presence)',
    shapes: [
      {
        kind: 'circle',
        cx: 50,
        cy: 30,
        r: 8,
        color: 'var(--danger)',
        fill: 'var(--presence-soft)',
      },
      {
        kind: 'line',
        x1: 50,
        y1: 38,
        x2: 50,
        y2: 65,
        color: 'var(--insight)',
        arrow: false,
      },
      {
        kind: 'polygon',
        points: '30,70 70,70 50,90',
        color: 'var(--warning)',
        fill: 'var(--warning)',
      },
    ],
    labels: [
      {
        x: 50,
        y: 30,
        text: 'Pistil',
        side: 'right',
        color: 'var(--text-primary)',
      },
      {
        x: 50,
        y: 65,
        text: 'Stem',
        side: 'left',
        color: 'var(--text-muted)',
      },
      {
        x: 50,
        y: 80,
        text: 'Sepal',
        side: 'bottom',
        color: 'var(--text-primary)',
      },
    ],
    ratio: 1.6,
    footer: 'A complete flower anatomy with key reproductive and protective parts.',
  },
  beforeafter: {
    title: 'Design iteration',
    icon: 'image',
    iconColor: 'var(--presence)',
    before: {
      label: 'Original',
      from: 'var(--warning)',
      to: 'var(--danger)',
      caption: 'Before redesign',
      src: 'https://example.com/design-old.jpg',
    },
    after: {
      label: 'Updated',
      from: 'var(--insight)',
      to: 'var(--presence)',
      caption: 'After redesign',
      src: 'https://example.com/design-new.jpg',
    },
    position: 50,
    footer: 'Drag the divider left or right to compare the two versions',
  },
  carousel: {
    title: 'Product lineup',
    icon: 'image',
    iconColor: 'var(--presence)',
    slides: [
      {
        label: 'Model A',
        caption: 'Entry-level compact design',
        from: 'var(--presence)',
        to: 'var(--presence-soft)',
        tag: 'Popular',
        src: 'https://example.com/product-a.jpg',
      },
      {
        label: 'Model B',
        caption: 'Mid-range with advanced features',
        from: 'var(--insight)',
        to: 'var(--presence)',
        tag: 'Pro',
        src: 'https://example.com/product-b.jpg',
      },
      {
        label: 'Model C',
        caption: 'Premium professional edition',
        from: 'var(--warning)',
        to: 'var(--danger)',
        src: 'https://example.com/product-c.jpg',
      },
    ],
    start: 0,
    footer: 'Swipe or tap arrows to browse the full product range',
  },
  lightbox: {
    title: 'Portfolio gallery',
    icon: 'image',
    iconColor: 'var(--presence)',
    items: [
      {
        label: 'Sunset landscape',
        caption: 'Golden hour mountain vista',
        from: 'var(--warning)',
        to: 'var(--danger)',
        src: 'https://example.com/portfolio-01.jpg',
      },
      {
        label: 'Urban architecture',
        caption: 'Modern glass and steel composition',
        from: 'var(--text-muted)',
        to: 'var(--presence)',
        src: 'https://example.com/portfolio-02.jpg',
      },
      {
        label: 'Portrait study',
        caption: 'Dramatic lighting and depth',
        from: 'var(--presence)',
        to: 'var(--insight)',
        src: 'https://example.com/portfolio-03.jpg',
      },
      {
        label: 'Forest canopy',
        caption: 'Nature photography deep in woods',
        from: 'var(--insight)',
        to: 'var(--presence-soft)',
        src: 'https://example.com/portfolio-04.jpg',
      },
    ],
    footer: 'Click any thumbnail to open the lightbox · 4 images',
  },
  videoembed: {
    title: 'Tutorial: Getting started',
    icon: 'play',
    iconColor: 'var(--presence)',
    thumb: {
      from: 'var(--presence)',
      to: 'var(--presence-soft)',
      label: 'Play tutorial',
    },
    video: 'https://example.com/tutorial-complete.mp4',
    poster: 'https://example.com/tutorial-poster.jpg',
    durationLabel: '12:40',
    chapters: [
      {
        time: '0:00',
        at: 0,
        title: 'Introduction',
      },
      {
        time: '2:15',
        at: 18,
        title: 'Setting up your workspace',
      },
      {
        time: '5:30',
        at: 44,
        title: 'Core features walkthrough',
      },
      {
        time: '9:45',
        at: 77,
        title: 'Tips and best practices',
      },
    ],
    active: 0,
    footer: 'A complete guide to the platform basics—follow along at your own pace',
  },
  moodboard: {
    title: 'Brand mood exploration',
    icon: 'palette',
    iconColor: 'var(--insight)',
    tiles: [
      {
        kind: 'image',
        span: 1,
        rows: 1,
        from: 'var(--presence)',
        to: 'var(--presence-soft)',
        label: 'Minimalist serif',
        src: 'https://example.com/img1.jpg',
      },
      {
        kind: 'color',
        span: 1,
        rows: 1,
        swatch: 'var(--insight)',
        hex: '#2DD4BF',
        label: 'Teal accent',
      },
      {
        kind: 'text',
        span: 2,
        rows: 1,
        text: 'Warm, approachable, modern. Think high-end simplicity.',
      },
      {
        kind: 'image',
        span: 1,
        rows: 2,
        from: 'var(--warning)',
        to: 'var(--presence)',
        label: 'Golden hour',
        src: 'https://example.com/img2.jpg',
      },
    ],
    footer: 'Click any tile to add to favorites',
  },
  imagecallouts: {
    title: 'UI component breakdown',
    icon: 'image',
    iconColor: 'var(--presence)',
    image: {
      from: 'var(--presence)',
      to: 'var(--insight)',
      label: 'Screenshot',
      src: 'https://example.com/ui-mockup.jpg',
    },
    callouts: [
      {
        x: 15,
        y: 25,
        label: 'Header navigation',
        detail: 'Sticky positioning on scroll, rounded shadow',
        color: 'var(--insight)',
      },
      {
        x: 50,
        y: 60,
        label: 'Content card',
        detail: 'Max-width 600px, padding 24px, border-radius 12px',
        color: 'var(--presence)',
      },
      {
        x: 85,
        y: 80,
        label: 'Action button',
        detail: 'Primary state: bold 600, 12px sans-serif',
        color: 'var(--warning)',
      },
    ],
    footer: 'Tap any number to see the detail',
  },
};
