// Complete examples for the applied-brief family. Values are illustrative fixtures, not claims.
export const APPLIED_EXAMPLES: Record<string, Record<string, unknown>> = {
  decisionrecord: {
    title: 'Decision record · DR-014',
    icon: 'check',
    iconColor: 'var(--insight)',
    decision: 'Run a two-week pilot with one support queue before changing the full workflow.',
    rationale: [
      'A narrow pilot exposes operational issues without moving every team at once.',
      'The queue already has a stable baseline and an accountable owner.',
      'Two weeks captures both weekday and weekend demand.',
    ],
    status: 'decided',
    owner: 'Support operations',
    decidedAt: 'August 22',
    revisitWhen: 'Resolution time worsens by more than 10%',
  },
  assumptionledger: {
    title: 'Launch assumptions',
    icon: 'layers',
    assumptions: [
      {
        assumption: 'New users understand the first-run prompt without instruction.',
        evidence: 'Five of seven moderated participants completed it unaided.',
        confidence: 'medium',
        test: 'Run an unmoderated comprehension study.',
        status: 'active',
      },
      {
        assumption: 'The existing support rotation can absorb pilot demand.',
        evidence: 'Current utilization averages 68%.',
        confidence: 'low',
        status: 'pending',
      },
      {
        assumption: 'Customers value faster setup over advanced controls.',
        test: 'Compare activation across simplified and advanced variants.',
        confidence: 'untested',
        status: 'unknown',
      },
    ],
  },
  requirementboard: {
    title: 'Release scope',
    icon: 'table',
    groups: [
      {
        priority: 'must',
        items: [
          {
            requirement: 'Keyboard-complete setup',
            acceptance: 'All actions work without a pointer.',
            owner: 'Web',
            status: 'active',
          },
          {
            requirement: 'Recoverable save failures',
            acceptance: 'Draft remains available after a failed request.',
            owner: 'Platform',
            status: 'pending',
          },
        ],
      },
      {
        priority: 'should',
        items: [{ requirement: 'Import saved preferences', owner: 'Platform', status: 'pending' }],
      },
      {
        priority: 'could',
        items: [{ requirement: 'Optional compact density', status: 'unknown' }],
      },
      { priority: 'wont', items: [{ requirement: 'Custom themes in this release' }] },
    ],
  },
  experimentplan: {
    title: 'Pilot experiment',
    icon: 'spark',
    hypothesis: 'Showing one concrete example before setup will improve successful first sessions.',
    variables: [
      { name: 'Example preview', role: 'input', level: 'Shown vs hidden' },
      { name: 'Successful first session', role: 'outcome', level: 'Completed within 10 minutes' },
      { name: 'Traffic source', role: 'control', level: 'Balanced by channel' },
    ],
    steps: [
      'Randomly assign eligible new sessions.',
      'Run until the agreed sample or stop condition.',
      'Compare completion and support-contact rates.',
    ],
    measures: ['Completion rate', 'Time to first result', 'Support contacts'],
    guardrail: 'Stop if error rate rises materially or participants cannot exit the flow.',
  },
  negotiationplan: {
    title: 'Renewal negotiation',
    icon: 'chat',
    goal: 'Hold the annual price while adding a 60-day cancellation window.',
    walkAway: 'More than a 7% increase without a shorter commitment.',
    levers: [
      { label: 'Contract length', value: '12–24 months', priority: 'high' },
      { label: 'Payment schedule', value: 'Annual or quarterly', priority: 'medium' },
      { label: 'Reference participation', value: 'Case study after six months', priority: 'low' },
    ],
    concessions: ['Prepay the first year', 'Name a single administrative owner'],
    guardrails: ['No automatic renewal', 'Usage data remains exportable'],
  },
  stakeholdermap: {
    title: 'Migration stakeholders',
    icon: 'share',
    stakeholders: [
      {
        name: 'Executive sponsor',
        role: 'Budget owner',
        influence: 'high',
        interest: 'high',
        strategy: 'Weekly decision brief.',
      },
      {
        name: 'Security review',
        role: 'Control owner',
        influence: 'high',
        interest: 'low',
        strategy: 'Bring evidence before each gate.',
      },
      {
        name: 'Support team',
        role: 'Frontline users',
        influence: 'low',
        interest: 'high',
        strategy: 'Pilot early and publish changes.',
      },
      { name: 'Adjacent teams', influence: 'low', interest: 'low', strategy: 'Monthly digest.' },
    ],
  },
  serviceblueprint: {
    title: 'Repair appointment blueprint',
    icon: 'layers',
    stages: [
      {
        stage: 'Book',
        customer: 'Choose a time',
        frontstage: 'Show availability',
        backstage: 'Reserve capacity',
        support: 'Scheduling service',
      },
      {
        stage: 'Arrive',
        customer: 'Check in',
        frontstage: 'Confirm the request',
        backstage: 'Open work order',
        support: 'Customer record',
      },
      {
        stage: 'Repair',
        customer: 'Receive updates',
        frontstage: 'Explain findings',
        backstage: 'Complete diagnosis',
        support: 'Parts inventory',
      },
      {
        stage: 'Collect',
        customer: 'Review and pay',
        frontstage: 'Handoff',
        backstage: 'Close work order',
        support: 'Payments',
      },
    ],
    evidence: ['Booking confirmation', 'Status message', 'Receipt'],
  },
  approvalflow: {
    title: 'Campaign approval',
    icon: 'check',
    request: 'Approve the fall launch campaign for production.',
    status: 'active',
    due: 'Friday, 3:00 PM',
    approvers: [
      { name: 'Brand lead', role: 'Voice and identity', status: 'done', decidedAt: 'Tue 10:15 AM' },
      {
        name: 'Legal review',
        role: 'Claims and usage rights',
        status: 'active',
        note: 'Waiting on the final image credits.',
      },
      { name: 'Marketing director', role: 'Final sign-off', status: 'pending' },
    ],
  },
  resourceplan: {
    title: 'Workshop capacity',
    icon: 'layers',
    period: 'September sessions',
    resources: [
      {
        name: 'Facilitators',
        capacity: '12 shifts',
        demand: '14 shifts',
        gap: '−2 shifts',
        owner: 'Program lead',
        status: 'blocked',
      },
      {
        name: 'Training room',
        capacity: '8 days',
        demand: '8 days',
        gap: 'Balanced',
        owner: 'Facilities',
        status: 'done',
      },
      {
        name: 'Loaner laptops',
        capacity: '24',
        demand: '20',
        gap: '+4',
        owner: 'IT',
        status: 'active',
      },
    ],
  },
  maintenanceplan: {
    title: 'Home maintenance plan',
    icon: 'sliders',
    assets: [
      {
        asset: 'Heating and cooling',
        tasks: [
          {
            task: 'Replace air filter',
            interval: '3 months',
            lastDone: 'July 5',
            nextDue: 'October 5',
            owner: 'Household',
            status: 'active',
          },
          {
            task: 'Professional service',
            interval: '1 year',
            nextDue: 'March',
            owner: 'Licensed technician',
            status: 'pending',
          },
        ],
      },
      {
        asset: 'Safety',
        tasks: [
          {
            task: 'Test smoke alarms',
            interval: '1 month',
            lastDone: 'August 1',
            nextDue: 'September 1',
            status: 'active',
          },
        ],
      },
    ],
  },
  contactdirectory: {
    title: 'Event contacts',
    icon: 'mail',
    entries: [
      {
        name: 'Jordan Lee',
        role: 'Venue lead',
        organization: 'Harbor Hall',
        methods: [
          { label: 'Work', value: '(555) 010-0184' },
          { label: 'Email', value: 'jordan@example.test' },
        ],
        availability: 'Event day · 8 AM–8 PM',
      },
      {
        name: 'Sam Rivera',
        role: 'Catering captain',
        methods: [{ label: 'Work', value: '(555) 010-0168' }],
        note: 'Call for delivery access.',
      },
      {
        name: 'Avery Chen',
        role: 'Accessibility contact',
        methods: [{ label: 'Email', value: 'avery@example.test' }],
      },
    ],
    privacyNote:
      'Example data only. Share real contact information only with the intended audience.',
  },
  tripbudget: {
    title: 'Trip budget',
    icon: 'globe',
    trip: 'Four days in Montréal',
    currency: 'CAD',
    lines: [
      { category: 'Rail', planned: '$240', actual: '$228', note: 'Round trip' },
      { category: 'Stay', planned: '$720', actual: '$704', note: 'Three nights' },
      { category: 'Food', planned: '$320', actual: '$346' },
      { category: 'Local transit', planned: '$60', actual: '$54' },
    ],
    plannedTotal: '$1,340',
    actualTotal: '$1,332',
    footer: 'Illustrative amounts; taxes and exchange fees can change the total.',
  },
  careinstructions: {
    title: 'After-visit care summary',
    icon: 'shield',
    subject: 'Minor ankle sprain · clinician-supplied instructions',
    do: [
      'Follow the provided activity limits.',
      'Use the recommended support as directed.',
      'Keep the follow-up appointment.',
    ],
    avoid: [
      'Do not exceed the clinician’s return-to-activity plan.',
      'Do not use medication differently from its label or instructions.',
    ],
    warningSigns: [
      'New numbness or weakness',
      'Rapidly increasing swelling or pain',
      'Any symptom the care team marked urgent',
    ],
    followUp: 'Contact the care team if recovery is not progressing as they described.',
    source: 'Example after-visit instructions',
  },
  clausecompare: {
    title: 'Clause comparison',
    icon: 'doc',
    left: {
      label: 'Current draft',
      text: 'Either party may terminate with 30 days’ written notice.',
    },
    right: {
      label: 'Proposed draft',
      text: 'The customer may terminate after the initial term with 60 days’ written notice.',
    },
    differences: [
      {
        topic: 'Who may terminate',
        change: 'The right changes from either party to the customer only.',
        risk: 'medium',
      },
      {
        topic: 'Timing',
        change: 'Notice grows from 30 to 60 days and applies only after the initial term.',
        risk: 'high',
      },
      { topic: 'Form', change: 'Written notice remains required.', risk: 'low' },
    ],
    jurisdiction: 'the relevant jurisdiction',
  },
  incidentbrief: {
    title: 'Service incident · INC-27',
    icon: 'alert',
    impact: 'Some customers cannot complete checkout.',
    severity: 'high',
    status: 'active',
    timeline: [
      { time: '10:02', event: 'Automated error-rate alert fired.', status: 'done' },
      { time: '10:09', event: 'On-call traced failures to the payment handoff.', status: 'done' },
      { time: '10:21', event: 'Traffic shifted to the previous stable path.', status: 'active' },
    ],
    owners: ['Incident lead', 'Payments on-call'],
    actions: ['Confirm error-rate recovery', 'Reconcile interrupted orders'],
    nextUpdate: '10:45 AM',
  },
  coveragecheck: {
    title: 'Warranty coverage check',
    icon: 'shield',
    policy: 'Example appliance protection plan',
    asOf: 'the supplied policy copy',
    rows: [
      {
        item: 'Mechanical breakdown',
        status: 'covered',
        limit: 'Up to the stated service limit',
        evidence: 'Coverage section 2',
      },
      { item: 'Accidental damage', status: 'excluded', evidence: 'Exclusions section 4' },
      {
        item: 'Food loss',
        status: 'conditional',
        limit: 'Receipt and outage duration required',
        evidence: 'Benefit section 6',
      },
      {
        item: 'Pre-existing fault',
        status: 'unknown',
        evidence: 'Confirm the effective date and inspection terms',
      },
    ],
  },
  offerbreakdown: {
    title: 'Offer breakdown',
    icon: 'chart',
    employer: 'Example Studio',
    role: 'Senior product designer',
    parts: [
      { label: 'Base salary', value: '$165,000', kind: 'base' },
      {
        label: 'Target bonus',
        value: '10%',
        kind: 'bonus',
        note: 'Performance-based; not guaranteed.',
      },
      {
        label: 'Equity grant',
        value: '4,000 units',
        kind: 'equity',
        note: 'Value depends on vesting, price, and liquidity.',
      },
      {
        label: 'Signing bonus',
        value: '$12,000',
        kind: 'one-time',
        note: 'Repayment terms may apply.',
      },
      { label: 'Retirement match', value: 'Up to 4%', kind: 'benefit' },
    ],
    estimatedTotal: '$193,500 first-year cash at target',
    assumptions: [
      'Target bonus is achieved',
      'Equity is excluded from the cash total',
      'Verify tax and repayment terms',
    ],
  },
};
