// DemoOverlay — the demo replay's chrome, deliberately lighter than the walkthrough's: a slim
// persona banner (who this session belongs to), a bottom transport (step dots, play/pause,
// exit), and the occasional one-line beat caption. No coach voice, no spotlight scrim — the
// answers' own narration and reveal walks ARE the show; this overlay only frames them. It
// renders OVER the real Live surface and is pointer-transparent except for its own controls.
import type { ReactElement } from 'react';
import { Icon } from '../icons/icons';
import type { DemoDriver } from './useDemoDriver';
import { DEMO_CAST, type DemoCastMember } from './cast';
import { launchDemo } from './demoEntry';
import './demo.css';

function isEmojiAvatar(avatar: string): boolean {
  return /\p{Extended_Pictographic}/u.test(avatar);
}

export function DemoOverlay({
  driver,
  member,
  onExit,
}: {
  driver: DemoDriver;
  member: DemoCastMember;
  /** Leave the demo into the real surface (clean reload — see endTourToApp). */
  onExit: () => void;
}): ReactElement | null {
  if (!driver.active) return null;
  const accentStyle = { ['--accent' as string]: member.accent };

  if (driver.loadState === 'loading') {
    return (
      <div className="demox" aria-live="polite">
        <div className="demox-load" style={accentStyle}>
          <Icon.spinner className="demox-spinner" />
          Loading {member.name}&rsquo;s session…
        </div>
      </div>
    );
  }

  if (driver.loadState === 'error') {
    return (
      <div className="demox" aria-live="polite">
        <div className="demox-card" style={accentStyle} role="alert">
          <p className="demox-card-title">This demo couldn&rsquo;t load</p>
          <p className="demox-card-body">
            The recorded session did not come through. Check your connection and try again.
          </p>
          <div className="demox-card-actions">
            <button type="button" className="demox-primary" onClick={driver.reload}>
              Retry
            </button>
            <button
              type="button"
              className="demox-ghost"
              onClick={() => {
                window.location.hash = '#/';
              }}
            >
              Back to home
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!driver.started) {
    return (
      <div className="demox demox-intro" aria-live="polite">
        <div
          className="demox-card demox-start"
          style={accentStyle}
          role="dialog"
          aria-modal="true"
          aria-labelledby="demox-start-title"
        >
          <span className={'demox-avatar' + (isEmojiAvatar(member.avatar) ? ' emoji' : '')}>
            {member.avatar}
          </span>
          <span className="demox-card-kicker">Recorded session</span>
          <p id="demox-start-title" className="demox-card-title">
            Watch {member.name} use Mavéa
          </p>
          <p className="demox-card-body">
            The session plays automatically. Pause or move between steps at any time.
          </p>
          <div className="demox-card-actions">
            <button type="button" className="demox-primary" onClick={driver.start}>
              Start demo
            </button>
            <button type="button" className="demox-ghost" onClick={onExit}>
              Back to home
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (driver.done) {
    // Every other recorded session — the end card is how the non-hero cast stays reachable.
    const others = DEMO_CAST.filter((p) => p.id !== member.id);
    return (
      <div className="demox" aria-live="polite">
        <div className="demox-card demox-end" style={accentStyle}>
          <span className={'demox-avatar' + (isEmojiAvatar(member.avatar) ? ' emoji' : '')}>
            {member.avatar}
          </span>
          <p className="demox-card-title">That was {member.name}&rsquo;s session</p>
          <p className="demox-card-body">
            Every answer you watched was generated by a real model and replayed exactly. Nothing was
            staged. Your turn.
          </p>
          <div className="demox-card-actions">
            <button type="button" className="demox-primary" onClick={onExit}>
              Try it yourself
            </button>
            <button type="button" className="demox-ghost" onClick={driver.replay}>
              Replay
            </button>
          </div>
          <div className="demox-others" role="group" aria-label="More sessions">
            {others.map((p) => (
              <button
                key={p.id}
                type="button"
                className="demox-other"
                style={{ ['--accent' as string]: p.accent }}
                onClick={() => launchDemo(p.id)}
                title={`${p.name} · ${p.role}`}
              >
                <span className={'demox-other-avatar' + (isEmojiAvatar(p.avatar) ? ' emoji' : '')}>
                  {p.avatar}
                </span>
                {p.useCase}
              </button>
            ))}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="demox" aria-live="polite">
      {/* What this session shows (the persona is the supporting detail) — top-left. */}
      <div className="demox-banner" style={accentStyle}>
        <span className={'demox-avatar' + (isEmojiAvatar(member.avatar) ? ' emoji' : '')}>
          {member.avatar}
        </span>
        <span className="demox-who">
          <span className="demox-name">{member.useCase}</span>
          <span className="demox-role">
            {member.name} · {member.role}
          </span>
        </span>
        <span className="demox-badge">Demo</span>
      </div>

      {/* One-line beat caption ("Renata pins the bridge…"), only while a beat performs. */}
      {driver.note && (
        <div className="demox-note" key={driver.note} style={accentStyle}>
          {driver.note}
        </div>
      )}

      {/* Transport — bottom-center, above the composer. */}
      <div className="demox-panel" style={accentStyle} role="group" aria-label="Demo controls">
        <button
          type="button"
          className="demox-btn"
          onClick={driver.prev}
          disabled={driver.index === 0}
          aria-label="Previous step"
        >
          <Icon.chevL className="demox-ic" />
        </button>
        <button
          type="button"
          className="demox-btn demox-play"
          onClick={driver.toggle}
          aria-label={driver.playing ? 'Pause autoplay' : 'Turn on autoplay'}
        >
          {driver.playing ? (
            <Icon.pause className="demox-ic" />
          ) : (
            <Icon.play className="demox-ic" />
          )}
        </button>
        <button
          type="button"
          className="demox-btn demox-mute"
          onClick={driver.toggleMute}
          aria-label={driver.muted ? 'Turn narration on' : 'Mute narration'}
          aria-pressed={driver.muted}
          title={driver.muted ? 'Turn narration on' : 'Mute narration'}
        >
          {driver.muted ? (
            <Icon.speakerOff className="demox-ic" />
          ) : (
            <Icon.speaker className="demox-ic" />
          )}
        </button>
        <button type="button" className="demox-btn" onClick={driver.next} aria-label="Next step">
          <Icon.chevR className="demox-ic" />
        </button>
        <div className="demox-dots" role="tablist" aria-label="Steps">
          {Array.from({ length: driver.total }, (_, i) => (
            <button
              key={i}
              type="button"
              role="tab"
              aria-selected={i === driver.index}
              aria-label={`Step ${i + 1}`}
              className={'demox-dot' + (i === driver.index ? ' is-active' : '')}
              onClick={() => driver.jumpTo(i)}
            />
          ))}
        </div>
        <button
          type="button"
          className="demox-skip"
          onClick={onExit}
          aria-label="Exit demo, try it yourself"
        >
          <span className="demox-skip-full">Exit, try it yourself</span>
          <span className="demox-skip-short" aria-hidden="true">
            Exit
          </span>
        </button>
      </div>
    </div>
  );
}
