// GENERATED by `pnpm gen:catalog` — DO NOT EDIT. Detail shard 078: caseload.
import type { ComponentDetail } from '../facts';

export const D: Record<string, ComponentDetail> = {"caseload":{"blurb":"A social-worker caseload: one row per client (a case reference or initials, never a full name), a risk-flag badge banded like a risk matrix, and the next scheduled contact. Social work, case management — \"where does each case stand, who needs attention first\".","optional":["icon","iconColor","footer"],"itemShapes":[{"prop":"cases","text":"clientRef","textAliases":["client","ref","caseId"]}],"propHints":{"clientRef":"a case reference or initials — NEVER a full client name (confidentiality)","cases[].riskLevel":"'low'|'medium'|'high' — omit when a case hasn't been assessed yet"}}};
