// GENERATED by scripts/generate-gallery-fixtures.mjs — DO NOT EDIT BY HAND.

export type GalleryFixtureMap = Readonly<Record<string, unknown>>;

const LOADERS: Readonly<Record<string, () => Promise<GalleryFixtureMap>>> = {
  "ai": () => import('./fixtures/ai.json').then((module) => module.default as GalleryFixtureMap),
  "charts1": () => import('./fixtures/charts1.json').then((module) => module.default as GalleryFixtureMap),
  "charts2": () => import('./fixtures/charts2.json').then((module) => module.default as GalleryFixtureMap),
  "code": () => import('./fixtures/code.json').then((module) => module.default as GalleryFixtureMap),
  "compose": () => import('./fixtures/compose.json').then((module) => module.default as GalleryFixtureMap),
  "core": () => import('./fixtures/core.json').then((module) => module.default as GalleryFixtureMap),
  "diagrams": () => import('./fixtures/diagrams.json').then((module) => module.default as GalleryFixtureMap),
  "display": () => import('./fixtures/display.json').then((module) => module.default as GalleryFixtureMap),
  "docs": () => import('./fixtures/docs.json').then((module) => module.default as GalleryFixtureMap),
  "everyday": () => import('./fixtures/everyday.json').then((module) => module.default as GalleryFixtureMap),
  "finance": () => import('./fixtures/finance.json').then((module) => module.default as GalleryFixtureMap),
  "flows": () => import('./fixtures/flows.json').then((module) => module.default as GalleryFixtureMap),
  "forms": () => import('./fixtures/forms.json').then((module) => module.default as GalleryFixtureMap),
  "layout": () => import('./fixtures/layout.json').then((module) => module.default as GalleryFixtureMap),
  "learn": () => import('./fixtures/learn.json').then((module) => module.default as GalleryFixtureMap),
  "media": () => import('./fixtures/media.json').then((module) => module.default as GalleryFixtureMap),
  "nav": () => import('./fixtures/nav.json').then((module) => module.default as GalleryFixtureMap),
  "overlays": () => import('./fixtures/overlays.json').then((module) => module.default as GalleryFixtureMap),
  "pickers": () => import('./fixtures/pickers.json').then((module) => module.default as GalleryFixtureMap),
  "reference": () => import('./fixtures/reference.json').then((module) => module.default as GalleryFixtureMap),
  "stats": () => import('./fixtures/stats.json').then((module) => module.default as GalleryFixtureMap),
  "status": () => import('./fixtures/status.json').then((module) => module.default as GalleryFixtureMap),
  "tables": () => import('./fixtures/tables.json').then((module) => module.default as GalleryFixtureMap),
};
const CACHE = new Map<string, Promise<GalleryFixtureMap>>();

export function loadGalleryFixture(family: string, type: string): Promise<unknown> {
  const loader = LOADERS[family];
  if (!loader) return Promise.resolve(undefined);
  let pending = CACHE.get(family);
  if (!pending) {
    pending = loader();
    CACHE.set(family, pending);
  }
  return pending.then((fixtures) => fixtures[type]);
}
