// world/seed.ts — a hand-authored, clearly-illustrative living world shown before a real turn
// builds one (the WHY_SEED precedent). It demonstrates the whole world surface — weighted,
// relation-typed edges with receipts (two of them multi-receipt), per-node series, a one-level
// breakdown — WITHOUT pretending to be the user's data: provenance.illustrative is true, so the
// UI wears the "illustrative — shows the shape, not your numbers" banner, and every receipt
// points at the bundled sample timeline, never a real private source. Figures are textbook-scale,
// not measurements. Structurally it honors every gate in world/validate (unique ids, top-level
// edge refs, an acyclic web, ≤4 namespaced children, receipts[0] === receipt, a receipt on every
// point of every real series), so it round-trips the engine. Nodes with no history of their own
// carry their own date, which is what puts a wholly qualitative cause on the time axis.
import type { WorldSeriesPoint, WorldSpec } from './types';

const HOST = 'sample timeline';

/** Points that each earn their OWN receipt, written FROM the point's value so the sentence and the
 *  number can never drift. world/validate verifies a real series point by point and drops the ones
 *  it cannot check, so a history authored without them is a history the gate deletes on the way to
 *  the screen — which is what happened to all five of these until it was measured. */
function dated(
  subject: string,
  unit: string,
  points: ReadonlyArray<readonly [string, number]>,
): WorldSeriesPoint[] {
  const measure = (value: number): string => (unit === '%' ? `${value}%` : `${value} ${unit}`);
  return points.map(([t, value]) => ({
    t,
    value,
    receipt: { quote: `${subject} in ${t} measured ${measure(value)}.`, host: HOST },
  }));
}

// The two multi-receipt edges share their primary receipt by reference — the coerce gate's
// receipts[0] === receipt invariant, kept literally true here too.
const PIVOT_RECEIPT = {
  quote: 'Rising defaults hollowed out the pools behind the bonds.',
  host: HOST,
};
const PANIC_RECEIPT = {
  quote: 'Each surprise writedown made every rival look suspect.',
  host: HOST,
};

export const WORLD_SEED: WorldSpec = {
  title: 'Why did the 2008 financial crisis happen?',
  outcomeId: 'credit-crisis',
  provenance: {
    illustrative: true,
    notes: ['Illustrative example — the classic 2008 causal web, not your data.'],
  },
  nodes: [
    {
      id: 'cheap-mortgages',
      label: 'Cheap credit after 2001',
      role: 'root',
      domain: 'policy',
      depth: 0,
      tier: 'T2',
      date: { t: '2001', until: '2004' },
      detail: 'Policy rates near 1% through 2004 pushed lenders and investors toward yield.',
      receipt: { quote: 'Policy rates were held near 1 percent into 2004.', host: HOST },
    },
    {
      id: 'lending-standards',
      label: 'Lending standards loosened',
      role: 'root',
      domain: 'policy',
      depth: 0,
      tier: 'T2',
      date: { t: '2003', until: '2006' },
      detail: 'Low-doc and no-doc loans normalized as origination fees rewarded volume.',
      receipt: { quote: 'Documentation requirements fell steadily from 2003.', host: HOST },
    },
    {
      id: 'housing-boom',
      label: 'Housing boom',
      role: 'mechanism',
      domain: 'economy',
      depth: 1,
      tier: 'T2',
      date: { t: '2003', until: '2006' },
      receipt: { quote: 'Housing starts ran well above trend through 2005.', host: HOST },
    },
    {
      id: 'mortgage-volume',
      label: 'Mortgage volume surged',
      role: 'mechanism',
      domain: 'economy',
      depth: 1,
      tier: 'T2',
      unit: '$bn',
      receipt: { quote: 'Originations peaked near 3,100 billion dollars.', host: HOST },
      series: {
        tier: 'T2',
        unit: '$bn',
        receipt: { quote: 'Annual originations, 2003-2009.', host: HOST },
        points: dated('Originations', '$bn', [
          ['2003', 3800],
          ['2004', 2900],
          ['2005', 3100],
          ['2006', 3000],
          ['2007', 2400],
          ['2008', 1500],
          ['2009', 1800],
        ]),
      },
      children: [
        {
          id: 'mortgage-volume.prime',
          label: 'Prime',
          role: 'mechanism',
          depth: 1,
          tier: 'T2',
          value: 1900,
          unit: '$bn',
          receipt: { quote: 'Prime loans made up about 1,900 of originations.', host: HOST },
        },
        {
          id: 'mortgage-volume.alt-a',
          label: 'Alt-A',
          role: 'mechanism',
          depth: 1,
          tier: 'T2',
          value: 400,
          unit: '$bn',
          receipt: { quote: 'Alt-A lending reached roughly 400 billion.', host: HOST },
        },
        {
          id: 'mortgage-volume.subprime',
          label: 'Subprime',
          role: 'mechanism',
          depth: 1,
          tier: 'T2',
          value: 600,
          unit: '$bn',
          receipt: { quote: 'Subprime originations touched 600 billion at the peak.', host: HOST },
        },
        {
          id: 'mortgage-volume.arm',
          label: 'Adjustable-rate',
          role: 'mechanism',
          depth: 1,
          tier: 'T2',
          value: 100,
          unit: '$bn',
          receipt: { quote: 'Exotic adjustable-rate products added another 100.', host: HOST },
        },
      ],
    },
    {
      id: 'home-prices',
      label: 'Home prices climbed, then fell',
      role: 'mechanism',
      domain: 'economy',
      depth: 2,
      tier: 'T2',
      receipt: { quote: 'National prices rose two-thirds, then gave most of it back.', host: HOST },
      series: {
        tier: 'T2',
        unit: 'index',
        receipt: { quote: 'National house-price index, 2003-2009.', host: HOST },
        points: dated('The national house-price index', 'index', [
          ['2003', 100],
          ['2004', 127],
          ['2005', 152],
          ['2006', 168],
          ['2007', 160],
          ['2008', 132],
          ['2009', 115],
        ]),
      },
    },
    {
      id: 'mbs-cdo-exposure',
      label: 'MBS / CDO exposure spread',
      role: 'mechanism',
      domain: 'economy',
      depth: 2,
      tier: 'T2',
      date: { t: '2004', until: '2007' },
      detail: 'Securitization moved mortgage risk onto bank and fund balance sheets worldwide.',
      receipt: { quote: 'Structured mortgage products spread across balance sheets.', host: HOST },
    },
    {
      id: 'defaults',
      label: 'Mortgage defaults rose',
      role: 'mechanism',
      domain: 'society',
      depth: 3,
      tier: 'T2',
      value: 10.1,
      unit: '%',
      receipt: { quote: 'Delinquencies reached 10.1 percent by 2009.', host: HOST },
      series: {
        tier: 'T2',
        unit: '%',
        receipt: { quote: 'Mortgage delinquency rate, 2003-2009.', host: HOST },
        points: dated('The delinquency rate', '%', [
          ['2003', 4.5],
          ['2004', 4.3],
          ['2005', 4.6],
          ['2006', 5.0],
          ['2007', 6.3],
          ['2008', 8.9],
          ['2009', 10.1],
        ]),
      },
    },
    {
      id: 'asset-values',
      label: 'MBS asset values',
      role: 'mechanism',
      domain: 'economy',
      depth: 4,
      tier: 'T2',
      date: { t: '2007', until: '2008' },
      receipt: { quote: 'Senior tranches once rated AAA traded at deep discounts.', host: HOST },
    },
    {
      id: 'bank-losses',
      label: 'Bank losses and writedowns',
      role: 'mechanism',
      domain: 'economy',
      depth: 4,
      tier: 'T2',
      receipt: { quote: 'Writedowns climbed into the hundreds of billions.', host: HOST },
      series: {
        tier: 'T2',
        unit: '$bn',
        receipt: { quote: 'Annual bank writedowns, 2003-2009.', host: HOST },
        points: dated('Writedowns', '$bn', [
          ['2003', 2],
          ['2004', 3],
          ['2005', 4],
          ['2006', 12],
          ['2007', 160],
          ['2008', 490],
          ['2009', 280],
        ]),
      },
    },
    {
      id: 'panic',
      label: 'Counterparty panic',
      role: 'mechanism',
      domain: 'society',
      depth: 5,
      tier: 'T2',
      date: { t: '2008-09' },
      detail: 'Nobody could tell who held the losses, so everyone stopped trusting everyone.',
      receipt: { quote: 'After Lehman failed, counterparty trust evaporated.', host: HOST },
    },
    {
      id: 'liquidity',
      label: 'Interbank liquidity',
      role: 'mechanism',
      domain: 'economy',
      depth: 5,
      tier: 'T2',
      receipt: { quote: 'Interbank lending spreads spiked to records.', host: HOST },
      series: {
        tier: 'T2',
        unit: 'bps',
        receipt: { quote: 'Interbank spread, annual average, 2003-2009.', host: HOST },
        points: dated('The interbank spread', 'bps', [
          ['2003', 30],
          ['2004', 28],
          ['2005', 35],
          ['2006', 40],
          ['2007', 110],
          ['2008', 160],
          ['2009', 65],
        ]),
      },
    },
    {
      id: 'credit-crisis',
      label: 'Credit crisis',
      role: 'outcome',
      domain: 'economy',
      depth: 6,
      tier: 'T2',
      date: { t: '2008', until: '2009' },
      value: 4.3,
      unit: '%',
      receipt: { quote: 'Output fell 4.3 percent from peak to trough.', host: HOST },
    },
  ],
  edges: [
    {
      from: 'cheap-mortgages',
      to: 'housing-boom',
      verb: 'fueled',
      relation: 'causes',
      weight: 0.55,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Cheap financing pulled buyers forward into the boom.', host: HOST },
    },
    {
      from: 'cheap-mortgages',
      to: 'mortgage-volume',
      verb: 'expanded',
      relation: 'contributes',
      weight: 0.35,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Low rates made ever-larger loans serviceable.', host: HOST },
    },
    {
      from: 'lending-standards',
      to: 'mortgage-volume',
      verb: 'opened',
      relation: 'enables',
      weight: 0.5,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Looser underwriting admitted borrowers once turned away.', host: HOST },
    },
    {
      from: 'housing-boom',
      to: 'home-prices',
      verb: 'lifted',
      relation: 'causes',
      weight: 0.7,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Demand outran supply and prices followed.', host: HOST },
    },
    {
      from: 'mortgage-volume',
      to: 'mbs-cdo-exposure',
      verb: 'fed',
      relation: 'causes',
      weight: 0.8,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Nearly every new loan was pooled and resold.', host: HOST },
    },
    {
      from: 'home-prices',
      to: 'defaults',
      verb: 'suppressed',
      relation: 'dampens',
      weight: 0.4,
      sign: -1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Rising prices let stressed borrowers refinance or sell.', host: HOST },
    },
    {
      from: 'mortgage-volume',
      to: 'defaults',
      verb: 'seeded',
      relation: 'contributes',
      weight: 0.5,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'The marginal loan was the first to sour.', host: HOST },
    },
    {
      // Multi-receipt edge: the defaults → asset-values link is the crisis pivot, so it carries
      // the strongest (illustrative) evidence — receipts[0] is the primary receipt, always.
      from: 'defaults',
      to: 'asset-values',
      verb: 'crushed',
      relation: 'dampens',
      weight: 0.65,
      sign: -1,
      tier: 'T2',
      status: 'supported',
      receipt: PIVOT_RECEIPT,
      receipts: [
        PIVOT_RECEIPT,
        { quote: 'Tranche models had assumed defaults could not cluster.', host: HOST },
      ],
    },
    {
      from: 'asset-values',
      to: 'bank-losses',
      verb: 'cushioned',
      relation: 'dampens',
      weight: 0.6,
      sign: -1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'While marks held up, balance sheets looked whole.', host: HOST },
    },
    {
      from: 'mbs-cdo-exposure',
      to: 'bank-losses',
      verb: 'transmitted',
      relation: 'contributes',
      weight: 0.5,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: {
        quote: 'The bigger the book of structured paper, the bigger the hit.',
        host: HOST,
      },
    },
    {
      // The second multi-receipt edge: losses → panic is where the story turns systemic.
      from: 'bank-losses',
      to: 'panic',
      verb: 'ignited',
      relation: 'causes',
      weight: 0.7,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: PANIC_RECEIPT,
      receipts: [
        PANIC_RECEIPT,
        { quote: 'Money funds broke the buck and the run went wholesale.', host: HOST },
      ],
    },
    {
      from: 'panic',
      to: 'liquidity',
      verb: 'froze',
      relation: 'dampens',
      weight: 0.6,
      sign: -1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Banks hoarded cash rather than lend to each other.', host: HOST },
    },
    {
      from: 'liquidity',
      to: 'credit-crisis',
      verb: 'restrained',
      relation: 'dampens',
      weight: 0.3,
      sign: -1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'While money still moved, the real economy held on.', host: HOST },
    },
    {
      from: 'bank-losses',
      to: 'credit-crisis',
      verb: 'drove',
      relation: 'contributes',
      weight: 0.45,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: {
        quote: 'Capital-starved banks pulled credit from firms and households.',
        host: HOST,
      },
    },
    {
      from: 'panic',
      to: 'credit-crisis',
      verb: 'deepened',
      relation: 'contributes',
      weight: 0.35,
      sign: 1,
      tier: 'T2',
      status: 'supported',
      receipt: { quote: 'Fear finished what the losses started.', host: HOST },
    },
  ],
};
