// generate-example-shards.mts — shard the compact reference-example JSON into small, canonical-
// order modules Vite code-splits, so a turn's prompt-example lookup pays only for the handful of
// component types it actually offers instead of keeping the whole ~380 KB blob parsed and resident
// for the session. Mirrors how the block catalog shards its detail fields
// (scripts/generate-catalog-index.mts → canvas/blocks/catalog/details/).
//
//   pnpm gen:examples
//
// `referenceExamples.generated.json` (built by `pnpm gen:reference-examples` from the real demo
// topics + authored fallbacks) stays the source of truth; this only reshapes it for lazy loading, so
// re-run it whenever that JSON changes. A staleness test regenerates into a scratch directory and
// diffs against the committed output, the same way the catalog's shards are pinned.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

// The staleness test regenerates into a scratch directory and diffs, so it must never clobber the
// committed files out from under the workers importing them.
const OUT_DIR = process.env.EXAMPLES_OUT_DIR ?? 'src/live/select/examples';
const SOURCE = 'src/live/select/referenceExamples.generated.json';

/** Components per shard — mirrors SHARD_SIZE in scripts/generate-catalog-index.mts: small enough
 *  that a shard is mostly useful bytes, large enough that a turn opens tens of chunks, not hundreds. */
const SHARD_SIZE = 8;

const source = JSON.parse(readFileSync(SOURCE, 'utf8')) as Record<string, unknown>;
const types = Object.keys(source);

const indexSource = `// GENERATED by \`pnpm gen:examples\` from referenceExamples.generated.json — DO NOT EDIT BY HAND.
//
// Canonical order of every block type with a reference example, and the shard size the loaders
// below use to place it. Always resident (tiny — just the type names), unlike the shards themselves.
export const EXAMPLE_TYPES: readonly string[] = ${JSON.stringify(types)};

export const SHARD_SIZE = ${SHARD_SIZE};
`;

// Rebuild the whole directory: everything in it is generated, and a shrinking type count must not
// leave a stale shardNNN.ts behind for the loader array to no longer reference.
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(`${OUT_DIR}/index.generated.ts`, indexSource);

const shardCount = Math.ceil(types.length / SHARD_SIZE);
const pad = (n: number) => String(n).padStart(3, '0');
let shardBytes = 0;
for (let i = 0; i < shardCount; i++) {
  const slice = types.slice(i * SHARD_SIZE, (i + 1) * SHARD_SIZE);
  const map = Object.fromEntries(slice.map((type) => [type, source[type]]));
  const body = `// GENERATED by \`pnpm gen:examples\` — DO NOT EDIT. Example shard ${pad(i)}: ${slice.join(', ')}.
export const E: Record<string, unknown> = ${JSON.stringify(map)};
`;
  shardBytes += Buffer.byteLength(body);
  writeFileSync(`${OUT_DIR}/shard${pad(i)}.ts`, body);
}

const loaders = Array.from(
  { length: shardCount },
  (_, i) => `  () => import('./shard${pad(i)}'),`,
).join('\n');
writeFileSync(
  `${OUT_DIR}/loaders.generated.ts`,
  `// GENERATED by \`pnpm gen:examples\` — DO NOT EDIT.
//
// One dynamic import per example shard, so Vite emits one chunk each and a turn fetches only the
// shards holding the types its menu actually offers. The import specifiers must be static literals
// for the bundler to see them, which is why this file is generated rather than looped.
export const SHARD_LOADERS: (() => Promise<{ E: Record<string, unknown> }>)[] = [
${loaders}
];
`,
);

const fileCount = readdirSync(OUT_DIR).length;
console.log(
  `${OUT_DIR}: ${types.length} types, ${shardCount} shards of ${SHARD_SIZE}, ` +
    `${(shardBytes / 1024).toFixed(1)} KB total, ${fileCount} files`,
);
