// generate-catalog-index.mts — emit the compact selection-facts index from the family files.
//
//   pnpm gen:catalog
//
// The selector scores every candidate on every turn, so the facts it reads must be cheap to parse
// and small to ship. The DETAIL fields (blurb, optional, item shapes, prop hints) are ~70% of the
// catalog's bytes and are needed only for the ≤30 components a turn actually offers, so they stay in
// the lazily-loaded family modules and never appear here.
//
// Rows are TUPLES, not objects, and every repeated string (family, archetype, data shape, intent,
// domain, cap) is interned into a shared table. At 600 components that is the difference between a
// ~130 KB object literal and a ~35 KB one; at 10,000 it is the difference between a payload that
// stalls a 2016 laptop and one that does not. The decoder lives in catalog/facts.ts.
//
// A staleness test recomputes this file at test time and fails if it differs, so editing a family
// without regenerating cannot reach CI.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { RAW_CATALOG } from '../src/canvas/blocks/catalog/catalog.data';
import type { ComponentMeta } from '../src/canvas/blocks/catalog/meta';
import { enumValuesFromHint } from '../src/canvas/blocks/catalog/propHints';

// Read the compact reference-example JSON directly rather than through live/select/examples.ts:
// that module lazy-loads its data in shards for the browser (pnpm gen:examples), and this script
// needs every generic component's example synchronously, in one pass, to derive the structural
// references below. `pnpm gen:reference-examples` keeps this JSON current against the real topics.
const REFERENCE_EXAMPLES: Record<string, unknown> = JSON.parse(
  readFileSync('src/live/select/referenceExamples.generated.json', 'utf8'),
);
function referencePropsFor(type: string): Record<string, unknown> | null {
  const props = REFERENCE_EXAMPLES[type];
  return props && typeof props === 'object' && !Array.isArray(props)
    ? (props as Record<string, unknown>)
    : null;
}

// The staleness test regenerates into a scratch directory and diffs, so it must never clobber the
// committed files out from under the workers importing them.
const ROOT = process.env.CATALOG_OUT_DIR ?? 'src/canvas/blocks/catalog';
const OUT = `${ROOT}/facts.generated.ts`;
const STRUCTURES_OUT = `${ROOT}/structures.generated.ts`;
const FIXTURE_CONTRACTS_OUT = `${ROOT}/fixture-contracts.generated.ts`;
const DETAIL_DIR = `${ROOT}/details`;

/** Components per detail shard.
 *
 *  The unit of lazy loading has to match the unit of USE. A menu draws ~30 components and, by the
 *  selector's per-family cap, takes only ~2 from any one family — so family-sized detail modules ship
 *  ~30× more prose than the turn quotes (measured: 126 KB of 138 KB, 17 of 23 families, for a single
 *  ask). Small canonical-order shards make the fetched bytes track the MENU instead of the library,
 *  which is the whole point of the split. Eight is the knee: small enough that a shard is mostly
 *  useful bytes, large enough that a turn opens tens of chunks rather than hundreds. */
const SHARD_SIZE = 8;

/** One interning table per string axis, so a row stores small integer indices. */
class Intern {
  private readonly index = new Map<string, number>();
  readonly values: string[] = [];
  id(v: string): number {
    const hit = this.index.get(v);
    if (hit !== undefined) return hit;
    this.index.set(v, this.values.length);
    this.values.push(v);
    return this.values.length - 1;
  }
}

const families = new Intern();
const archetypes = new Intern();
const shapes = new Intern();
const intents = new Intern();
const domains = new Intern();
const caps = new Intern();
const coercers = new Intern();
const tiers = new Intern();
const embeds = new Intern();

/** Tuple layout — keep in lockstep with the decoder in facts.ts. */
const row = (m: ComponentMeta) => [
  m.type,
  families.id(m.family),
  archetypes.id(m.archetype),
  m.dataShapes.map((s) => shapes.id(s)),
  tiers.id(m.tier),
  m.wowWeight,
  m.interactive ? 1 : 0,
  coercers.id(m.coercer),
  m.colDefault,
  m.colMin ?? 0,
  m.embed ? embeds.id(m.embed) + 1 : 0,
  (m.intents ?? []).map((i) => intents.id(i)),
  (m.domains ?? []).map((d) => domains.id(d)),
  (m.caps ?? []).map((c) => caps.id(c)),
  m.requires,
];

// Build rows first so the intern tables are fully populated before they are serialized.
const rows = RAW_CATALOG.map(row);
const table = (name: string, t: Intern) => `export const ${name} = ${JSON.stringify(t.values)};`;

const source = `// GENERATED by \`pnpm gen:catalog\` from catalog/families/*.ts — DO NOT EDIT BY HAND.
//
// Compact selection facts, one tuple per component, in canonical catalog order. Strings are interned
// into the tables below. See catalog/facts.ts for the decoder and the tuple layout, and
// scripts/generate-catalog-index.mts for how this file is produced.

${table('FAMILIES', families)}
${table('ARCHETYPES', archetypes)}
${table('SHAPES', shapes)}
${table('TIERS', tiers)}
${table('COERCERS', coercers)}
${table('EMBEDS', embeds)}
${table('INTENTS', intents)}
${table('DOMAINS', domains)}
${table('CAPS', caps)}

/** [type, family, archetype, shapes[], tier, wow, interactive, coercer, colDefault, colMin,
 *   embed+1 (0 = none), intents[], domains[], caps[], requires[]]
 *
 *  \`requires\` is a fact, not authoring detail: it is the block's data CONTRACT (which props must be
 *  present for it to render anything), it is tiny (~12 KB across 600 components against ~120 KB for
 *  the blurbs), and the export/figure path reads it synchronously. Keeping it here is what lets that
 *  path stay sync while blurbs and prop hints load lazily. */
export type FactRow = [
  string,
  number,
  number,
  number[],
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number[],
  number[],
  number[],
  string[],
];

export const FACT_ROWS: FactRow[] = ${JSON.stringify(rows)};
`;

writeFileSync(OUT, source);
const bytes = Buffer.byteLength(source);
console.log(`${OUT}: ${RAW_CATALOG.length} components, ${(bytes / 1024).toFixed(1)} KB`);

// ── runtime structural references ───────────────────────────────────────────────────────────────
// The real examples import every authored topic (~724 KB minified). The prompt path needs those
// values, but validation only needs field names and primitive kinds. Generate value-free shapes so
// validating a restored/cached answer never downloads or parses the entire demo corpus.
function structuralReference(value: unknown): unknown {
  if (typeof value === 'string') return '';
  if (typeof value === 'number') return 0;
  if (typeof value === 'boolean') return false;
  if (value === null) return null;
  if (Array.isArray(value)) {
    if (!value.length) return [];
    // Arrays in real components are often intentionally heterogeneous: a family-tree person may
    // have parents while another has a partner, a grade may optionally carry maxScore, and a math
    // row mixes operators, identifiers, and fractions. Preserve every distinct VALUE-FREE shape
    // as a union of variants. Keeping only the richest item made valid compact examples disappear
    // whenever their first few entries used a simpler legitimate variant.
    const variants = value.map(structuralReference);
    return variants.filter(
      (variant, index) =>
        variants.findIndex((candidate) => JSON.stringify(candidate) === JSON.stringify(variant)) ===
        index,
    );
  }
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, item]) => [
        key,
        structuralReference(item),
      ]),
    );
  }
  return null;
}

const structures = Object.fromEntries(
  RAW_CATALOG.filter((meta) => meta.coercer === 'generic').map((meta) => [
    meta.type,
    structuralReference(referencePropsFor(meta.type)),
  ]),
);
const structuresSource = `// GENERATED by \`pnpm gen:catalog\` from real shipping fixtures — DO NOT EDIT.
//
// Value-free nested contracts for generic Live validation. Empty strings/zero/false encode only
// primitive kinds; no demo value is ever copied into a model answer. Keeping this separate from
// live/select/examples.ts prevents the validator from importing the complete authored topic corpus.

export const STRUCTURAL_REFERENCES: Readonly<Record<string, unknown>> = ${JSON.stringify(structures)};
`;
writeFileSync(STRUCTURES_OUT, structuresSource);
console.log(`${STRUCTURES_OUT}: ${(Buffer.byteLength(structuresSource) / 1024).toFixed(1)} KB`);

// ── gallery fixture contracts ──────────────────────────────────────────────────────────────────
// Verbose gallery fixtures lengthen prose and repeat short lists. Renderer discriminators must
// remain exact while that synthetic data is produced: changing `claims[].verdict: "true"`, for
// example, erases the fact-check result. Keep this gallery-only index separate from selection facts
// so Live and the landing route never pay for stress-test metadata.
function closedVocabularyPaths(meta: ComponentMeta): string[] {
  const paths = new Set<string>();
  for (const [path, hint] of Object.entries(meta.propHints ?? {})) {
    if (enumValuesFromHint(hint)) paths.add(path);
  }
  const visitItemShape = (spec: NonNullable<ComponentMeta['itemShapes']>[number], path: string) => {
    if (spec.closedVocab && spec.text) paths.add(`${path}[].${spec.text}`);
    for (const field of spec.closedVocabFields ?? []) paths.add(`${path}[].${field}`);
    if (spec.children) visitItemShape(spec.children, `${path}[].${spec.children.prop}`);
  };
  for (const spec of meta.itemShapes ?? []) visitItemShape(spec, spec.prop);
  return [...paths].sort();
}

const fixtureContracts = Object.fromEntries(
  RAW_CATALOG.flatMap((meta) => {
    const paths = closedVocabularyPaths(meta);
    return paths.length ? [[meta.type, paths]] : [];
  }),
);
const fixtureContractsSource = `// GENERATED by \`pnpm gen:catalog\` — DO NOT EDIT.
// Gallery-only paths whose string values are renderer discriminators, not prose.

export const GALLERY_CLOSED_VOCAB_PATHS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(fixtureContracts)};
`;
writeFileSync(FIXTURE_CONTRACTS_OUT, fixtureContractsSource);
console.log(
  `${FIXTURE_CONTRACTS_OUT}: ${(Buffer.byteLength(fixtureContractsSource) / 1024).toFixed(1)} KB`,
);

// ── detail shards ────────────────────────────────────────────────────────────────────────────────
// The authoring families stay the source of truth; these are derived. A component's shard is a pure
// function of its canonical index, so the loader needs no lookup table beyond the facts index.
const detailOf = (m: ComponentMeta) => {
  const d: Record<string, unknown> = { blurb: m.blurb, optional: m.optional };
  if (m.itemShapes) d.itemShapes = m.itemShapes;
  if (m.requiredPaths) d.requiredPaths = m.requiredPaths;
  if (m.stringItems) d.stringItems = m.stringItems;
  if (m.propHints) d.propHints = m.propHints;
  if (m.contentBudget) d.contentBudget = m.contentBudget;
  if (m.defaultProps) d.defaultProps = m.defaultProps;
  return d;
};

mkdirSync(ROOT, { recursive: true });
rmSync(DETAIL_DIR, { recursive: true, force: true });
mkdirSync(DETAIL_DIR, { recursive: true });

const shardCount = Math.ceil(RAW_CATALOG.length / SHARD_SIZE);
const pad = (n: number) => String(n).padStart(3, '0');
let detailBytes = 0;
for (let i = 0; i < shardCount; i++) {
  const slice = RAW_CATALOG.slice(i * SHARD_SIZE, (i + 1) * SHARD_SIZE);
  const map = Object.fromEntries(slice.map((m) => [m.type, detailOf(m)]));
  const body = `// GENERATED by \`pnpm gen:catalog\` — DO NOT EDIT. Detail shard ${pad(i)}: ${slice
    .map((m) => m.type)
    .join(', ')}.
import type { ComponentDetail } from '../facts';

export const D: Record<string, ComponentDetail> = ${JSON.stringify(map)};
`;
  detailBytes += Buffer.byteLength(body);
  writeFileSync(`${DETAIL_DIR}/shard${pad(i)}.ts`, body);
}

const loaders = Array.from(
  { length: shardCount },
  (_, i) => `  () => import('./shard${pad(i)}'),`,
).join('\n');
writeFileSync(
  `${DETAIL_DIR}/loaders.generated.ts`,
  `// GENERATED by \`pnpm gen:catalog\` — DO NOT EDIT.
//
// One dynamic import per detail shard, so Vite emits one chunk each and a turn fetches only the
// shards holding the components it actually offers. The import specifiers must be static literals
// for the bundler to see them, which is why this file is generated rather than looped.
import type { ComponentDetail } from '../facts';

/** Components per shard — mirrors SHARD_SIZE in scripts/generate-catalog-index.mts. */
export const SHARD_SIZE = ${SHARD_SIZE};

export const SHARD_LOADERS: (() => Promise<{ D: Record<string, ComponentDetail> }>)[] = [
${loaders}
];
`,
);
console.log(
  `${DETAIL_DIR}: ${shardCount} shards of ${SHARD_SIZE}, ${(detailBytes / 1024).toFixed(1)} KB total`,
);
