// Catalog entries for the `ai` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_AI: ComponentCatalog = [
  // — ai —
  createMeta('reasoning', {
    family: 'ai',
    dataShapes: ['sequence'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'conclusion', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'steps', text: 'label', textAliases: ['name', 'title', 'step'] }],
    blurb: 'Step-by-step reasoning with expandable detail.',
  }),
  createMeta('toolcalls', {
    family: 'ai',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'calls'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'calls', text: 'name', textAliases: ['label', 'title', 'tool'] }],
    blurb: 'Tool invocations with request/response payloads.',
    propHints: {
      'calls[].status': "'ok'|'error'|'pending'",
    },
  }),
  createMeta('agenttrace', {
    family: 'ai',
    dataShapes: ['hierarchy', 'comparison', 'ranking'],
    requires: ['title', 'nodes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Agent decision tree with scores and chosen branches.',
  }),
  createMeta('modelcompare', {
    family: 'ai',
    dataShapes: ['comparison', 'text'],
    requires: ['title', 'outputs'],
    optional: ['icon', 'iconColor', 'prompt', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'outputs', text: 'model', textAliases: ['name', 'label', 'title'] }],
    blurb: 'Compare responses from multiple models with diff highlight.',
  }),
  createMeta('tokenstream', {
    family: 'ai',
    dataShapes: ['series', 'distribution'],
    requires: ['title', 'tokens'],
    optional: ['icon', 'iconColor', 'prefix', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Token stream with confidence heatmap and alternatives.',
  }),
  createMeta('retrieval', {
    family: 'ai',
    dataShapes: ['ranking', 'list'],
    requires: ['title', 'chunks'],
    optional: ['icon', 'iconColor', 'query', 'footer'],
    interactive: true,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'chunks', text: 'snippet', textAliases: ['text', 'content', 'body', 'label'] },
    ],
    blurb:
      'Search/RAG retrieval results — ranked source chunks each with a relevance score, illustrating how a system retrieves context. Never for a generic ranked list of items — use leaderboard or list.',
  }),
  createMeta('whatchanged', {
    family: 'ai',
    dataShapes: ['comparison', 'sequence'],
    requires: ['title', 'before', 'after', 'diff'],
    optional: ['icon', 'iconColor', 'beforeLabel', 'afterLabel', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Before/after comparison with unified diff view.',
    propHints: {
      'diff[].t': "'add'|'del'|'ctx'",
    },
  }),
  createMeta('routing', {
    family: 'ai',
    dataShapes: ['comparison', 'flow'],
    requires: ['title', 'choices'],
    optional: ['icon', 'iconColor', 'query', 'classifier', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'choices', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Routing decision with choice branches and scores.',
  }),
  createMeta('embedmap', {
    family: 'ai',
    dataShapes: ['relationship', 'geo'],
    requires: ['title', 'clusters', 'points'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: '2D embedding scatter plot with cluster visualization.',
  }),
  createMeta('calibration', {
    family: 'ai',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'bins'],
    optional: ['icon', 'iconColor', 'color', 'ece', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Calibration curve with predicted vs actual reliability.',
  }),
  createMeta('httpexchange', {
    family: 'ai',
    dataShapes: ['sequence', 'flow', 'status'],
    requires: ['exchanges'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'exchanges', text: 'url', textAliases: ['path', 'endpoint', 'name'] }],
    blurb:
      'HTTP request/response inspector — a sequence of exchanges, each a method badge, URL, status pill colored by class, latency, and optional request/response body preview.',
    propHints: {
      'exchanges[].method': "'GET'|'POST'|'PUT'|'PATCH'|'DELETE'",
      'exchanges[].status': 'numeric HTTP status code, e.g. 200, 404, 503',
    },
    domains: ['code', 'tech', 'data'],
    intents: ['explain', 'reference'],
  }),
  createMeta('trainingcurve', {
    family: 'ai',
    dataShapes: ['series', 'comparison'],
    requires: ['epochs', 'trainLoss'],
    optional: ['title', 'icon', 'iconColor', 'valLoss', 'trainAcc', 'valAcc', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'ML model training-curve panel: loss curves (train + validation) in the top panel and accuracy curves in the bottom, both against epoch index. Marks the best-val-loss epoch. Reveals overfitting when train and val curves diverge. Use for showing neural-network training progress, diagnosing overfitting/underfitting, comparing learning-rate schedules.',
    propHints: {
      epochs: 'array of epoch indices (or auto 1..N if omitted)',
      trainLoss: 'training loss per epoch',
      valLoss: 'validation loss per epoch',
      trainAcc: 'training accuracy per epoch (0–1)',
      valAcc: 'validation accuracy per epoch (0–1)',
    },
    intents: ['analyze', 'explain', 'teach'],
    domains: ['ai', 'education'],
  }),
];
