import { createMeta, type ComponentCatalog } from '../meta';

const BRIEF_STATUS_HINT = "'done'|'active'|'pending'|'blocked'|'unknown'";

// Applied briefs turn common, consequential conversations into inspectable working artifacts.
// Each contract owns a distinct job; the family shares presentation primitives, not semantics.
export const CATALOG_BRIEFS: ComponentCatalog = [
  createMeta('decisionrecord', {
    family: 'briefs',
    dataShapes: ['text', 'list', 'status'],
    requires: ['title', 'decision', 'rationale'],
    optional: ['icon', 'iconColor', 'status', 'owner', 'decidedAt', 'revisitWhen', 'footer'],
    tier: 'base',
    wowWeight: 0.76,
    interactive: false,
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A durable decision record: the selected course, the reasons behind it, accountable owner, decision date, and explicit trigger for reopening it. Use after a decision is made; use compare or proscons while options are still being evaluated.',
    stringItems: ['rationale'],
    propHints: { status: "'proposed'|'decided'|'revisiting'" },
  }),
  createMeta('assumptionledger', {
    family: 'briefs',
    dataShapes: ['tabular', 'status', 'list'],
    requires: ['title', 'assumptions'],
    optional: ['icon', 'iconColor', 'footer'],
    tier: 'frontier',
    wowWeight: 0.78,
    interactive: false,
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An assumption ledger pairing each belief with evidence or a test, confidence, and current state. Use to expose what a plan depends on and which unknown should be tested next.',
    itemShapes: [{ prop: 'assumptions', text: 'assumption', textAliases: ['belief', 'claim'] }],
    propHints: {
      'assumptions[].confidence': "'high'|'medium'|'low'|'untested'",
      'assumptions[].status': "'done'|'active'|'pending'|'blocked'|'unknown'",
    },
  }),
  createMeta('requirementboard', {
    family: 'briefs',
    dataShapes: ['list', 'status', 'comparison'],
    requires: ['title', 'groups'],
    optional: ['icon', 'iconColor', 'footer'],
    tier: 'base',
    wowWeight: 0.8,
    interactive: false,
    colDefault: 12,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A MoSCoW requirement board with acceptance criteria, owners, and state. Use to turn a product, event, purchase, or project brief into must/should/could/not-now scope.',
    itemShapes: [
      {
        prop: 'groups',
        requiredFields: ['priority', 'items'],
        closedVocabFields: ['priority'],
        children: {
          prop: 'items',
          text: 'requirement',
          textAliases: ['label', 'item', 'need'],
        },
      },
    ],
    propHints: {
      'groups[].priority': "'must'|'should'|'could'|'wont'",
      'groups[].items': 'array of { requirement, acceptance?, owner?, status? }',
      'groups[].items[].status': BRIEF_STATUS_HINT,
    },
  }),
  createMeta('experimentplan', {
    family: 'briefs',
    dataShapes: ['sequence', 'keyvalue', 'text'],
    requires: ['title', 'hypothesis', 'variables', 'steps'],
    optional: ['icon', 'iconColor', 'measures', 'guardrail', 'footer'],
    tier: 'frontier',
    wowWeight: 0.8,
    interactive: false,
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A testable experiment plan: hypothesis, input/outcome/control variables, ordered procedure, measures, and a safety or decision guardrail. Fits product tests, school labs, process trials, and research planning.',
    itemShapes: [
      {
        prop: 'variables',
        text: 'name',
        textAliases: ['variable', 'label'],
        requiredFields: ['role'],
        closedVocabFields: ['role'],
      },
    ],
    stringItems: ['steps', 'measures'],
    propHints: { 'variables[].role': "'input'|'outcome'|'control'" },
  }),
  createMeta('negotiationplan', {
    family: 'briefs',
    dataShapes: ['comparison', 'list', 'keyvalue'],
    requires: ['title', 'goal', 'walkAway', 'levers'],
    optional: ['icon', 'iconColor', 'concessions', 'guardrails', 'footer'],
    tier: 'base',
    wowWeight: 0.78,
    interactive: false,
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A negotiation prep sheet with target, walk-away, tradeable levers, planned concessions, and guardrails. Use for salary, vendor, rent, scope, schedule, or everyday negotiation preparation.',
    itemShapes: [{ prop: 'levers', text: 'label', textAliases: ['lever', 'term'] }],
    stringItems: ['concessions', 'guardrails'],
    propHints: { 'levers[].priority': "'high'|'medium'|'low'" },
  }),
  createMeta('stakeholdermap', {
    family: 'briefs',
    dataShapes: ['relationship', 'comparison', 'list'],
    requires: ['title', 'stakeholders'],
    optional: ['icon', 'iconColor', 'footer'],
    tier: 'frontier',
    wowWeight: 0.84,
    interactive: false,
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An influence-by-interest map that places people into manage-closely, keep-satisfied, keep-informed, or monitor quadrants with an engagement strategy. Use for projects, change management, community work, and events.',
    itemShapes: [
      {
        prop: 'stakeholders',
        text: 'name',
        textAliases: ['person', 'group'],
        requiredFields: ['influence', 'interest'],
        closedVocabFields: ['influence', 'interest'],
      },
    ],
    propHints: {
      'stakeholders[].influence': "'high'|'low'",
      'stakeholders[].interest': "'high'|'low'",
    },
  }),
  createMeta('serviceblueprint', {
    family: 'briefs',
    dataShapes: ['sequence', 'flow', 'tabular'],
    requires: ['title', 'stages'],
    optional: ['icon', 'iconColor', 'evidence', 'footer'],
    tier: 'frontier',
    wowWeight: 0.86,
    interactive: false,
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A service blueprint laid out by stage across customer action, frontstage, backstage, and support lanes. Use to design or diagnose a service experience; use journey for an experience-only emotional path.',
    itemShapes: [{ prop: 'stages', text: 'stage', textAliases: ['name', 'phase'] }],
    stringItems: ['evidence'],
  }),
  createMeta('approvalflow', {
    family: 'briefs',
    dataShapes: ['flow', 'status', 'sequence'],
    requires: ['title', 'request', 'approvers'],
    optional: ['icon', 'iconColor', 'status', 'due', 'footer'],
    tier: 'base',
    wowWeight: 0.76,
    interactive: false,
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A serial approval path showing the request, overall state, deadline, and each approver’s decision or blocker. Use for budgets, documents, access, purchases, creative reviews, and sign-off chains.',
    itemShapes: [
      {
        prop: 'approvers',
        text: 'name',
        textAliases: ['approver', 'owner'],
        requiredFields: ['status'],
        closedVocabFields: ['status'],
      },
    ],
    propHints: { status: BRIEF_STATUS_HINT, 'approvers[].status': BRIEF_STATUS_HINT },
  }),
  createMeta('resourceplan', {
    family: 'briefs',
    dataShapes: ['tabular', 'status', 'comparison'],
    requires: ['title', 'resources'],
    optional: ['icon', 'iconColor', 'period', 'footer'],
    tier: 'base',
    wowWeight: 0.74,
    interactive: false,
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A capacity-versus-demand resource plan with explicit gaps, owners, and state. Use for people, rooms, vehicles, equipment, inventory allocations, or volunteer coverage without inventing numeric precision.',
    itemShapes: [{ prop: 'resources', text: 'name', textAliases: ['resource', 'item'] }],
    propHints: { 'resources[].status': BRIEF_STATUS_HINT },
  }),
  createMeta('maintenanceplan', {
    family: 'briefs',
    dataShapes: ['sequence', 'status', 'list'],
    requires: ['title', 'assets'],
    optional: ['icon', 'iconColor', 'footer'],
    tier: 'base',
    wowWeight: 0.72,
    interactive: false,
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A recurring maintenance plan grouped by asset, with task, interval, last completion, next due date, owner, and status. Use for a home, car, equipment, facilities, software operations, or collections.',
    itemShapes: [
      {
        prop: 'assets',
        text: 'asset',
        textAliases: ['name', 'item'],
        requiredFields: ['tasks'],
        children: {
          prop: 'tasks',
          text: 'task',
          textAliases: ['name', 'item', 'maintenance'],
        },
      },
    ],
    propHints: {
      'assets[].tasks': 'array of { task, interval?, lastDone?, nextDue?, owner?, status? }',
      'assets[].tasks[].status': BRIEF_STATUS_HINT,
    },
  }),
  createMeta('contactdirectory', {
    family: 'briefs',
    dataShapes: ['list', 'keyvalue'],
    requires: ['title', 'entries'],
    optional: ['icon', 'iconColor', 'privacyNote', 'footer'],
    tier: 'base',
    wowWeight: 0.7,
    interactive: false,
    colDefault: 9,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A compact contact directory with role, organization, labeled contact methods, availability, notes, and a permanent privacy reminder. Use only for contact information the user supplied or explicitly asked to organize; never infer private details.',
    itemShapes: [
      {
        prop: 'entries',
        text: 'name',
        textAliases: ['person', 'contact'],
        requiredFields: ['methods'],
        children: {
          prop: 'methods',
          text: 'label',
          textAliases: ['type', 'method'],
          requiredFields: ['value'],
        },
      },
    ],
    propHints: { 'entries[].methods': 'array of { label, value }' },
  }),
  createMeta('tripbudget', {
    family: 'briefs',
    dataShapes: ['composition', 'tabular', 'comparison'],
    requires: ['title', 'lines'],
    optional: ['icon', 'iconColor', 'trip', 'currency', 'plannedTotal', 'actualTotal', 'footer'],
    tier: 'base',
    wowWeight: 0.76,
    interactive: false,
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A travel budget comparing planned and actual amounts by category, with trip context and optional totals. Use for vacations, business travel, group trips, or move planning; preserve the user’s currency formatting.',
    itemShapes: [
      {
        prop: 'lines',
        text: 'category',
        textAliases: ['name', 'item'],
        requiredFields: ['planned'],
      },
    ],
    caps: ['currency', 'total-row'],
  }),
  createMeta('careinstructions', {
    family: 'briefs',
    dataShapes: ['list', 'action', 'status'],
    requires: ['title', 'do'],
    optional: [
      'icon',
      'iconColor',
      'subject',
      'avoid',
      'warningSigns',
      'followUp',
      'source',
      'footer',
    ],
    tier: 'frontier',
    wowWeight: 0.74,
    interactive: false,
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A clearly scoped care-instruction handoff with do, avoid, warning-sign, and follow-up sections plus a permanent professional-care disclaimer. Use to organize supplied or sourced guidance, never to present a diagnosis.',
    stringItems: ['do', 'avoid', 'warningSigns'],
  }),
  createMeta('clausecompare', {
    family: 'briefs',
    dataShapes: ['comparison', 'text', 'list'],
    requires: ['title', 'left', 'right', 'differences'],
    optional: ['icon', 'iconColor', 'jurisdiction', 'footer'],
    tier: 'frontier',
    wowWeight: 0.8,
    interactive: false,
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A side-by-side clause comparison followed by topic-level changes and risk flags, with a permanent professional-review disclaimer. Use for summarizing supplied contract or policy language, never as a substitute for legal advice.',
    itemShapes: [
      {
        prop: 'differences',
        text: 'topic',
        textAliases: ['name', 'issue'],
        requiredFields: ['change'],
      },
    ],
    requiredPaths: ['left.label', 'left.text', 'right.label', 'right.text'],
    propHints: { 'differences[].risk': "'low'|'medium'|'high'" },
  }),
  createMeta('incidentbrief', {
    family: 'briefs',
    dataShapes: ['status', 'sequence', 'action'],
    requires: ['title', 'impact', 'timeline'],
    optional: [
      'icon',
      'iconColor',
      'severity',
      'status',
      'owners',
      'actions',
      'nextUpdate',
      'footer',
    ],
    tier: 'base',
    wowWeight: 0.8,
    interactive: false,
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A concise incident brief with impact, severity, current state, timestamped developments, owners, next actions, and the next communication time. Use for service, event, facility, travel, or operational incidents.',
    itemShapes: [
      {
        prop: 'timeline',
        text: 'event',
        textAliases: ['detail', 'message'],
        requiredFields: ['time'],
      },
    ],
    stringItems: ['owners', 'actions'],
    propHints: {
      severity: "'low'|'medium'|'high'|'critical'",
      status: BRIEF_STATUS_HINT,
      'timeline[].status': BRIEF_STATUS_HINT,
    },
  }),
  createMeta('coveragecheck', {
    family: 'briefs',
    dataShapes: ['status', 'tabular', 'list'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'policy', 'asOf', 'footer'],
    tier: 'frontier',
    wowWeight: 0.76,
    interactive: false,
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A coverage checklist marking items covered, conditional, excluded, or still unknown, with limits and evidence plus a permanent verify-the-policy disclaimer. Use for supplied insurance, warranty, benefit, or policy terms.',
    itemShapes: [
      {
        prop: 'rows',
        text: 'item',
        textAliases: ['name', 'coverage'],
        requiredFields: ['status'],
        closedVocabFields: ['status'],
      },
    ],
    propHints: { 'rows[].status': "'covered'|'conditional'|'excluded'|'unknown'" },
  }),
  createMeta('offerbreakdown', {
    family: 'briefs',
    dataShapes: ['composition', 'keyvalue', 'list'],
    requires: ['title', 'parts'],
    optional: ['icon', 'iconColor', 'employer', 'role', 'estimatedTotal', 'assumptions', 'footer'],
    tier: 'base',
    wowWeight: 0.78,
    interactive: false,
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A compensation-offer breakdown across base, bonus, equity, benefits, and one-time items, with a permanent verification note and explicit assumptions behind any estimated total. Use for understanding one offer; use compare for multiple offers side by side.',
    itemShapes: [
      {
        prop: 'parts',
        text: 'label',
        textAliases: ['name', 'component'],
        requiredFields: ['value'],
      },
    ],
    stringItems: ['assumptions'],
    propHints: { 'parts[].kind': "'base'|'bonus'|'equity'|'benefit'|'one-time'|'other'" },
    caps: ['currency', 'total-row'],
  }),
];
