// Catalog entries for the `charts2` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_CHARTS2: ComponentCatalog = [
  // — charts2 —
  createMeta('slopegraph', {
    family: 'charts2',
    dataShapes: ['comparison', 'series'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'unit', 'beforeLabel', 'afterLabel', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Before-and-after change lines with labels \u2014 shows trajectory or shift per category.',
  }),
  createMeta('dumbbell', {
    family: 'charts2',
    dataShapes: ['comparison', 'distribution'],
    requires: ['title', 'rows'],
    optional: [
      'icon',
      'iconColor',
      'unit',
      'startLabel',
      'endLabel',
      'startColor',
      'endColor',
      'domain',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Paired dots with connector bars \u2014 compare ranges or intervals across categories.',
  }),
  createMeta('lollipop', {
    family: 'charts2',
    dataShapes: ['ranking', 'comparison'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label' }],
    propHints: {
      'rows[].value':
        'a REAL number this row ranks by \u2014 required, never omit or leave non-numeric. If the items have no true magnitude to rank by (e.g. a plain checklist of categories), pick a checklist-shaped block instead of lollipop',
      'rows[].sub': 'optional short annotation shown on hover next to the value',
    },
    blurb: 'Stem-and-circle bars \u2014 cleaner bar chart alternative for ranked values.',
  }),
  createMeta('bulletchart', {
    family: 'charts2',
    dataShapes: ['status', 'comparison'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Actual vs a defined TARGET with qualitative bands \u2014 a performance gauge with context (revenue vs quota, latency vs SLA). Never for a plain category comparison with no target \u2014 use bars.',
  }),
  createMeta('candlestick', {
    family: 'charts2',
    dataShapes: ['series', 'distribution'],
    requires: ['title', 'candles'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'OHLC candles over time \u2014 requires a real open/high/low/close per period (stock/crypto/commodity prices). Never for a generic time series with a single value per point \u2014 use chart.',
  }),
  createMeta('gantt', {
    family: 'charts2',
    dataShapes: ['sequence', 'flow'],
    requires: ['title', 'cols', 'tasks'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Project schedule: task bars spanning DATE RANGES on a timeline, with completion and dependencies. Never for a single-point event timeline or a status list \u2014 use timeline or statustimeline.',
    stringItems: ['cols'],
  }),
  createMeta('bubble', {
    family: 'charts2',
    dataShapes: ['relationship', 'composition'],
    requires: ['title', 'categories', 'points'],
    optional: ['icon', 'iconColor', 'xLabel', 'yLabel', 'xDomain', 'yDomain', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Scatter plot with size and color \u2014 multivariate relationship explorer.',
  }),
  createMeta('arearange', {
    family: 'charts2',
    dataShapes: ['series', 'distribution'],
    requires: ['title', 'points'],
    optional: ['icon', 'iconColor', 'unit', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Line with confidence band \u2014 forecast or range trend over time.',
  }),
  createMeta('waffle', {
    family: 'charts2',
    dataShapes: ['composition'],
    requires: ['title', 'cats'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb: '10x10 grid of squares \u2014 composition breakdown or percentage at a glance.',
  }),
  createMeta('groupedbars', {
    family: 'charts2',
    dataShapes: ['comparison', 'series'],
    requires: ['title', 'groups', 'series'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Clustered bars by group \u2014 compare multiple series side-by-side.',
    stringItems: ['groups'],
  }),
  createMeta('stackedbars', {
    family: 'charts2',
    dataShapes: ['composition', 'comparison', 'series'],
    requires: ['title', 'groups', 'series'],
    optional: ['icon', 'iconColor', 'unit', 'mode', 'yLabel', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Stacked bar chart (stacked columns): one bar per category, split bottom-to-top into shared colour-keyed segments \u2014 revenue by region per quarter, hours by activity per day, spend by category per month. Each column reads as a whole AND as its parts; a value is printed in every segment tall enough to hold one, with the column total above the bar. mode:"percent" normalises every column to 100% to compare MIX alone. Use marimekko instead when column WIDTH should also carry the total, groupedbars when the series are compared side-by-side rather than summed, and stack for a single one-bar breakdown. Values must be \u2265 0 \u2014 for signed +/\u2212 contributions use bridge.',
    stringItems: ['groups'],
    // `series[].data` is index-aligned with `groups`, so it must be allowed to be as long: on the
    // shared default (16 items) a 20-group answer arrives with its last four columns silently
    // truncated to zero \u2014 data loss the chart would then render as a real, empty reading.
    contentBudget: { fields: { 'series[].data': { maxItems: 20 } } },
    itemShapes: [{ prop: 'series', text: 'name', textAliases: ['label', 'segment', 'category'] }],
    propHints: {
      groups: 'one category label per BAR, left \u2192 right (quarters, days, departments)',
      'series[].data':
        'one value per group, index-aligned with `groups`; \u2265 0 (a negative counts as 0)',
      'series[].name': 'segment name, shared across every bar \u2014 it keys the colour and legend',
      mode: "'absolute' (default, real totals on the y-axis) | 'percent' (each column = 100%)",
      yLabel: 'rotated value-axis title, e.g. "Revenue ($k)"',
    },
    intents: ['quantify', 'explain', 'decide'],
  }),
  createMeta('bridge', {
    family: 'charts2',
    dataShapes: ['composition', 'flow', 'comparison'],
    requires: ['title', 'start', 'end', 'steps'],
    optional: ['icon', 'iconColor', 'unit', 'prefix', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Waterfall bridge explaining why a number changed — a start, a sequence of signed +/- contributions, and an end, each step floating from the running total. For "what moved revenue/cost/score". Use bars for a plain comparison with no start→end story.',
    itemShapes: [{ prop: 'steps', text: 'label' }],
    intents: ['explain', 'quantify', 'decide'],
  }),
  createMeta('calheat', {
    family: 'charts2',
    dataShapes: ['series', 'distribution'],
    requires: ['title', 'days'],
    optional: ['icon', 'iconColor', 'color', 'weekdays', 'legend', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'GitHub-style activity calendar: daily intensity over weeks (streaks and gaps).',
    stringItems: ['weekdays'],
  }),
  createMeta('bump', {
    family: 'charts2',
    dataShapes: ['series', 'ranking'],
    requires: ['title', 'periods', 'series'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Rank-over-time lines; crossings show where things overtake each other.',
    stringItems: ['periods'],
  }),
  createMeta('marimekko', {
    family: 'charts2',
    dataShapes: ['composition', 'comparison'],
    requires: ['title', 'columns'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: true,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Mosaic: column width is the total, height is the share — magnitude and mix at once.',
  }),
  createMeta('plot', {
    family: 'charts2',
    dataShapes: ['series', 'relationship'],
    requires: ['title', 'curves'],
    optional: [
      'icon',
      'iconColor',
      'xLabel',
      'yLabel',
      'xDomain',
      'yDomain',
      'markers',
      'origin',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Cartesian plot of functions/curves on an x/y plane; axes through origin, gridlines, markers.',
  }),
  // — charts2 additions —
  createMeta('dualaxis', {
    family: 'charts2',
    dataShapes: ['series', 'comparison'],
    requires: ['title', 'categories', 'bar', 'line'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Two y-axes over the same x (e.g. revenue + margin); bars on left, line on right.',
    propHints: {
      'bar.unit': 'e.g. "$" or "units"',
      'line.unit': 'e.g. "%" or "bps"',
    },
    stringItems: ['categories'],
  }),
  createMeta('scatterregression', {
    family: 'charts2',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'points'],
    optional: ['icon', 'iconColor', 'xLabel', 'yLabel', 'color', 'fit', 'footer'],
    interactive: false,
    wowWeight: 0.81,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb: 'Scatter plot with an OLS regression line, R² annotation, and optional point labels.',
    // points items are {x,y} numeric pairs — no text field to normalize; itemShapes omitted
    // so coerceGeneric passes them through as-is instead of dropping all items.
  }),
  createMeta('dotplot', {
    family: 'charts2',
    dataShapes: ['distribution', 'relationship'],
    requires: ['title', 'values'],
    optional: ['label', 'color', 'note', 'sub'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A stacked-dot plot where each observation becomes one dot above a number line. Shows distribution shape, clusters, and outliers. Ideal for small datasets (≤ 30 values).',
    propHints: {
      values: 'raw numeric observations, e.g. [12, 15, 15, 18, 22]',
      label: 'x-axis label, e.g. "Test score"',
    },
  }),
  createMeta('controlchart', {
    family: 'charts2',
    dataShapes: ['series', 'comparison'],
    requires: ['title', 'points', 'ucl', 'lcl', 'centerLine'],
    optional: ['icon', 'iconColor', 'yLabel', 'note', 'sub'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A Shewhart process-control chart with upper/lower control limits and a center line. Out-of-control points are highlighted. Use for manufacturing quality, service metrics, or any process monitored over time.',
    propHints: {
      'points[].label': 'sample label, e.g. "Week 1"',
      'points[].value': 'measured value for that sample',
      ucl: 'upper control limit (mean + 3σ)',
      lcl: 'lower control limit (mean − 3σ)',
      centerLine: 'process mean',
    },
  }),
  createMeta('areaplot', {
    family: 'charts2',
    dataShapes: ['relationship', 'series', 'distribution'],
    requires: ['title', 'curves'],
    optional: [
      'icon',
      'iconColor',
      'xLabel',
      'yLabel',
      'xDomain',
      'yDomain',
      'shade',
      'rects',
      'areaLabel',
      'showArea',
      'origin',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Cartesian plot that shades a region — area under a curve to the x-axis or between two curves, with optional Riemann/trapezoid rectangles and the area value labeled. The integral/AUC visual: calculus areas, probability mass under a pdf, consumer/producer surplus, work under an F–x curve.',
    itemShapes: [{ prop: 'curves', textAliases: ['name', 'title'] }],
    propHints: {
      'curves[].points':
        'sampled points [{x,y}] in data coords (sample finely, e.g. ~30+ pts, for a smooth fill)',
      shade:
        "{ from: 'axis' | curveIndex, to: topCurveIndex, x0?, x1? } — 'axis' fills down to y=0; x0/x1 are the integration limits (default = the curves' sampled span)",
      rects:
        "{ n: number, rule: 'left'|'right'|'mid'|'trap' } — draws Riemann/trapezoid rectangles over the region and prints the estimate",
      areaLabel:
        'override the area badge (e.g. an exact symbolic value); omit to show the computed integral',
      origin: 'true (default) draws axes through (0,0) when in range; false = edge axes',
    },
    intents: ['explain', 'teach', 'quantify'],
    domains: ['math', 'science', 'data'],
  }),
  createMeta('supplydemand', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison'],
    requires: ['title', 'supply', 'demand'],
    optional: [
      'icon',
      'iconColor',
      'shift',
      'region',
      'qMax',
      'pMax',
      'priceLabel',
      'quantityLabel',
      'pricePrefix',
      'showEquilibrium',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'The economics supply×demand diagram: an upward supply line and downward demand line on price(y)×quantity(x) axes, the equilibrium marked P*/Q*, optional shaded consumer/producer surplus, and an optional shift of one curve (faded original + arrow). Pick it for market equilibrium, price controls, taxes, and comparative-statics questions.',
    propHints: {
      supply:
        'the supply line as { intercept, slope } where P = intercept + slope·Q with slope > 0 (e.g. { intercept: 2, slope: 0.5 }), OR { points: [{q,p},{q,p}] }',
      demand:
        'the demand line as { intercept, slope } where P = intercept + slope·Q with slope < 0 (e.g. { intercept: 14, slope: -0.7 }), OR { points: [{q,p},{q,p}] }',
      'shift.curve': "'supply'|'demand' — which curve moves",
      'shift.to':
        'the curve’s new position, same shape as supply/demand ({intercept,slope} or {points})',
      region: "'consumer'|'producer'|'none' — shade the surplus triangle at equilibrium",
      pricePrefix: "currency symbol on every price, e.g. '$'",
    },
    intents: ['explain', 'teach', 'quantify'],
    domains: ['business', 'data', 'education'],
  }),
  createMeta('bigo', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison', 'series'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'classes',
      'maxN',
      'highlight',
      'algorithm',
      'xLabel',
      'yLabel',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Big-O growth chart: operations vs input size n, the canonical complexity curves (O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n)) drawn together so the exponential visibly dwarfs the rest. Pick for "how fast does X grow" / comparing algorithm complexities; highlight one class or annotate "this algorithm" on a curve.',
    propHints: {
      classes:
        "subset of 'o-1'|'o-logn'|'o-n'|'o-nlogn'|'o-n2'|'o-2n' (drawn slow->fast; default all six)",
      highlight: "one of 'o-1'|'o-logn'|'o-n'|'o-nlogn'|'o-n2'|'o-2n'",
      maxN: 'integer largest input size on x-axis, 2..64 (default 16)',
      algorithm: "{ name: string, complexity: 'o-1'|'o-logn'|'o-n'|'o-nlogn'|'o-n2'|'o-2n' }",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'teach', 'reference', 'quantify'],
    domains: ['code', 'math', 'education'],
  }),
  createMeta('errorbars', {
    family: 'charts2',
    dataShapes: ['comparison', 'distribution', 'relationship'],
    requires: ['title', 'groups'],
    optional: ['icon', 'iconColor', 'unit', 'yLabel', 'bars', 'reference', 'bracket', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Group means with their uncertainty — each group a point (or bar) plus a confidence-interval whisker (mean ± ci, or explicit low/high). The #1 inferential-statistics graphic for comparing groups, and the standard way to report lab/experiment results. Use over plain bars whenever the spread or overlap of the estimates is the point.',
    itemShapes: [{ prop: 'groups', text: 'label', textAliases: ['name', 'group'] }],
    propHints: {
      'groups[].label': 'group name, e.g. "Placebo"',
      'groups[].mean': 'the group mean / central estimate (the point or bar height)',
      'groups[].ci': 'symmetric half-width of the interval (drawn as mean ± ci)',
      'groups[].low':
        'explicit lower interval bound (use low + high for asymmetric CIs instead of ci)',
      'groups[].high': 'explicit upper interval bound (pair with low)',
      'groups[].color': 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
      bars: 'true draws a bar from the baseline to each mean behind the whisker; false (default) = points',
      reference: '{ value: number, label?: string } — a horizontal target/baseline line',
      bracket:
        '{ from: number, to: number, label: string } — significance annotation between two groups by index, e.g. { from: 0, to: 2, label: "p < 0.001" }',
    },
    intents: ['quantify', 'explain', 'reference'],
    domains: ['data', 'science', 'education'],
  }),
  createMeta('eratimeline', {
    family: 'charts2',
    dataShapes: ['sequence', 'comparison', 'relationship'],
    requires: ['title', 'tracks'],
    optional: ['icon', 'iconColor', 'min', 'max', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Comparative multi-track timeline on ONE shared time axis: several parallel lanes (regions, fields, people), each with era BANDS (start→end spans) and point events, so synchronous history lines up vertically. For "what was happening in X vs Y at the same time", overlapping eras, side-by-side project/era comparison. Times are signed years (negative = BCE). Use gantt for a project schedule with dependencies; timeline for a single sequence of dated points.',
    itemShapes: [
      {
        prop: 'tracks',
        text: 'label',
        children: { prop: 'spans', text: 'label' },
      },
    ],
    propHints: {
      'tracks[].spans[].start':
        'signed year, negative = BCE (e.g. -509 for 509 BCE, 1492 for 1492 CE)',
      'tracks[].spans[].end': 'signed year >= start',
      'tracks[].events[].at': 'signed year of a single-moment event',
      color: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'teach', 'reference'],
    domains: ['education', 'business'],
  }),
  // — charts2 additions (long-tail academic) —
  createMeta('payoffdiagram', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison', 'distribution'],
    requires: ['title', 'legs'],
    optional: [
      'icon',
      'iconColor',
      'priceMin',
      'priceMax',
      'pricePrefix',
      'underlyingLabel',
      'pnlLabel',
      'spot',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.83,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Options / derivatives payoff diagram: profit-and-loss (y) vs the underlying price at expiration (x). The kinked payoff line is computed from the position legs (call/put × long/short × strike × premium), with breakeven prices marked where P/L crosses zero, profit (green) vs loss (red) zones shaded, a zero reference line, and max profit / max loss (incl. "unlimited") derived. Pick for a single call/put, a spread, a straddle, a collar — any options strategy P&L.',
    itemShapes: [{ prop: 'legs' }],
    propHints: {
      legs: "the position's legs: [{ type: 'call'|'put', position: 'long'|'short', strike: number, premium: number, qty?: number }] — payoff is summed across legs, so the curve bends at every strike",
      'legs[].type': "'call' | 'put'",
      'legs[].position': "'long' (bought, pays premium) | 'short' (written, collects premium)",
      priceMin: 'visible price-axis lower bound; auto-fit around the strikes when omitted',
      priceMax: 'visible price-axis upper bound; auto-fit around the strikes when omitted',
      pricePrefix: "currency symbol on prices and P/L, e.g. '$' (default '$')",
      spot: "today's underlying price; drawn as a vertical guide",
    },
    intents: ['explain', 'teach', 'quantify'],
    domains: ['finance', 'business', 'education'],
  }),
  createMeta('phasediagram', {
    family: 'charts2',
    dataShapes: ['relationship', 'structure', 'comparison'],
    requires: ['title', 'boundaries'],
    optional: [
      'icon',
      'iconColor',
      'triplePoint',
      'criticalPoint',
      'regions',
      'tLabel',
      'pLabel',
      'tUnit',
      'pUnit',
      'tDomain',
      'pDomain',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.83,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A pressure–temperature phase diagram: temperature (x) vs pressure (y), with the solid / liquid / gas (and optional supercritical-fluid) regions separated by phase-boundary curves (sublimation, fusion, vaporization), the triple point and critical point marked and labelled. Pick it for chemistry / thermodynamics / materials questions about states of matter, phase transitions, sublimation, melting/boiling under pressure — and water’s famous negative-slope fusion line (ice melts under pressure), which the boundary points can express directly.',
    itemShapes: [
      { prop: 'boundaries', text: 'label' },
      { prop: 'regions', text: 'label' },
    ],
    propHints: {
      'boundaries[].kind':
        "'sublimation' (solid⇌gas) | 'fusion' (solid⇌liquid) | 'vaporization' (liquid⇌gas)",
      'boundaries[].points':
        'sampled points [{t,p}] in data coords (temperature, pressure) along the curve; sample finely. Fusion can have NEGATIVE slope (e.g. water) — just supply points trending left as pressure rises.',
      'boundaries[].color':
        'var(--presence)|var(--insight)|var(--warning)|var(--danger)|var(--line-strong)',
      triplePoint:
        '{ t, p } — where all three phases coexist (e.g. water: {t:273.16, p:0.006} in K/atm)',
      criticalPoint:
        '{ t, p } — where the liquid⇌gas boundary ends and the supercritical fluid begins (e.g. water: {t:647.1, p:218} in K/atm)',
      'regions[]':
        "{ t, p, phase, label, color?, anchor? } — a label placed inside an area; phase is 'solid'|'liquid'|'gas'|'supercritical' (drives the tint), anchor is 'start'|'middle'|'end'",
      tUnit: "temperature unit, e.g. 'K' or '°C'",
      pUnit: "pressure unit, e.g. 'atm', 'kPa', 'bar'",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'teach', 'reference', 'quantify'],
    domains: ['science', 'education'],
  }),
  createMeta('indifferencecurve', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison'],
    requires: ['title', 'curves'],
    optional: [
      'icon',
      'iconColor',
      'budget',
      'optimal',
      'xLabel',
      'yLabel',
      'xMax',
      'yMax',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'The microeconomics indifference-curve map: good X (x) vs good Y (y), a family of convex, downward-sloping indifference curves (further from the origin = more utility, labelled U₁ < U₂ < U₃), with an optional budget line and the optimal consumption bundle marked where the budget line is tangent to the highest reachable curve. Pick it for consumer choice / utility theory, MRS = price-ratio tangency, and how a price or income change moves the optimum.',
    itemShapes: [{ prop: 'curves', textAliases: ['name', 'title'] }],
    propHints: {
      'curves[].points':
        'sampled points [{x,y}] left→right tracing ONE convex, downward-sloping curve (sample finely, ~8+ pts); higher-utility curves bow further from the origin and must NOT cross a lower one',
      'curves[].label': 'utility level, e.g. "U₁" (lowest) … "U₃" (highest)',
      budget:
        'the budget line as { intercept, slope } where Y = intercept + slope·X with slope < 0 (intercept = income ÷ price of Y, slope = −price of X ÷ price of Y), OR { points: [{x,y},{x,y}] }',
      optimal:
        '{ x, y, label? } the optimal bundle (tangency of the budget line with the highest reachable curve); make (x,y) an exact sampled point on that curve to highlight it',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'teach', 'quantify'],
    domains: ['business', 'data', 'education'],
  }),
  createMeta('breakeven', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison'],
    requires: ['fixedCost', 'pricePerUnit', 'costPerUnit'],
    optional: ['title', 'icon', 'iconColor', 'maxUnits', 'unit', 'currency', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'The cost-volume-profit (break-even) chart: a revenue line and a total-cost line on units(x) x money(y) axes that cross at the break-even volume, with the loss region (left of the crossing) shaded and the profit region (right) shaded. Computed entirely from fixed cost, price per unit, and variable cost per unit — it derives break-even units = fixed / (price - cost) and the per-unit contribution margin. Pick it for pricing, profitability, and "how many do we need to sell" questions.',
    propHints: {
      fixedCost: 'total fixed cost that does not change with volume (rent, salaries, tooling)',
      pricePerUnit: 'revenue earned per unit sold',
      costPerUnit:
        'variable cost per unit produced; must be < pricePerUnit for a finite break-even',
      maxUnits: 'right end of the units axis; auto-fits to ~2x the break-even volume when omitted',
      unit: "unit noun on the x-axis + readouts, e.g. 'units'|'subscriptions'|'seats'",
      currency: "currency symbol prefixing every money value (default '$')",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['quantify', 'explain', 'decide'],
    domains: ['money', 'business'],
  }),
  createMeta('burnrunway', {
    family: 'charts2',
    dataShapes: ['series', 'scalar'],
    requires: ['months'],
    optional: ['title', 'icon', 'iconColor', 'initialCash', 'runwayMonths', 'currency', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Cash balance + monthly burn rate chart with projected runway: a dual-axis view pairing the declining cash curve against the per-month burn bars. A runway horizon line and read-out show exactly how many months remain. Use for startup financials, seed-round planning, "how long does our cash last", and fundraising readiness discussions.',
    itemShapes: [{ prop: 'months', text: 'label', textAliases: ['month', 'period', 'name'] }],
    propHints: {
      months:
        'array of monthly data — each has label (e.g. "Jan 25"), burn (monthly spend), and optional balance (if omitted, computed as running total)',
      initialCash:
        'opening cash balance in the same units as burn (e.g. 1_200_000 for $1.2M); inferred from the first balance when omitted',
      currency: 'currency symbol prefix shown on all cash figures; default "$"',
    },
    domains: ['business', 'money'],
    intents: ['track', 'quantify', 'analyze'],
  }),
  createMeta('loaddiagram', {
    family: 'charts2',
    dataShapes: ['relationship', 'series', 'structure'],
    requires: ['title', 'span', 'supports', 'loads'],
    optional: ['icon', 'iconColor', 'unit', 'shear', 'moment', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A structural-engineering beam load diagram with its matched shear V(x) and bending-moment M(x) plots — three panels stacked on one shared position axis (distance along the beam), so a support, a load, the shear it produces, and the resulting moment all line up vertically. The top panel draws the beam with supports (pin/roller/fixed) and applied loads (point arrows, distributed bands); the V and M panels plot the supplied series with the peaks (Vmax, Mmax) marked. For statics, mechanics of materials, and structural-analysis explanations. Plots the V/M series it is given (it does not solve the statics); supply them alongside the loads.',
    itemShapes: [
      { prop: 'supports' },
      { prop: 'loads', text: 'label' },
      { prop: 'shear' },
      { prop: 'moment' },
    ],
    propHints: {
      span: 'total beam length; sets the shared distance axis [0, span]',
      'supports[].at': 'position along the span (0 … span) where the support sits',
      'supports[].kind': "'pin'|'roller'|'fixed' (default 'pin')",
      'loads[].kind':
        "'point' (concentrated force) | 'udl' (uniformly distributed load over [at, to])",
      'loads[].at': "the load's position (point) or its start (udl)",
      'loads[].to': "the udl's end position; required for kind 'udl', ignored for 'point'",
      'loads[].mag': "a point load's force, or a udl's intensity per unit length",
      'loads[].label': "caption drawn by the load, e.g. 'P = 12 kN' or 'w = 4 kN/m'",
      unit: "force unit suffix on labels + read-outs, e.g. 'kN', 'lbf'",
      shear:
        'the shear diagram V(x) as a sampled series [{x, v}] left→right (plotted, not computed) — include the jumps at point loads and the endpoints',
      moment:
        'the bending-moment diagram M(x) as a sampled series [{x, m}] left→right (plotted, not computed) — sample finely enough to show its curvature',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'teach', 'quantify', 'reference'],
    domains: ['science', 'math', 'education'],
  }),
  createMeta('ecgstrip', {
    family: 'charts2',
    dataShapes: ['series', 'status'],
    requires: [],
    optional: [
      'title',
      'icon',
      'iconColor',
      'samples',
      'rateBpm',
      'rhythm',
      'intervals',
      'abnormalities',
      'gridMs',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A physiologic ECG rhythm strip on the classic pink graticule (1 mm small squares grouped into 5 mm large squares). The P-QRS-T waveform is drawn from a sampled trace (normalized -1..2, baseline 0, R-wave peak near 2); when no samples are given a normal sinus beat is synthesized and repeated at rateBpm, so the strip stays honest to the stated rate. PR/QRS/QT interval brackets and abnormality pins (PVC, ST elevation…) are placed by millisecond and the rate + rhythm read out above. For cardiology, vitals, and clinical-teaching explanations. Plots the trace it is given — it never invents a measurement.',
    itemShapes: [
      { prop: 'intervals', text: 'label' },
      { prop: 'abnormalities', text: 'label' },
    ],
    propHints: {
      samples:
        'the waveform as numbers, one per gridMs, normalized -1..2 (0 = baseline, ~2 = R-wave peak); omit to synthesize a normal sinus beat at rateBpm',
      rateBpm:
        'heart rate in beats per minute; drives synthesized beat spacing + the rate read-out',
      rhythm: "rhythm interpretation shown beside the rate, e.g. 'Normal sinus rhythm'",
      'intervals[].label': "segment measured, e.g. 'PR', 'QRS', 'QT'",
      'intervals[].fromMs': "interval start, in ms from the strip's left edge",
      'intervals[].toMs': 'interval end, in ms (>= fromMs)',
      'abnormalities[].atMs': "time of the finding, in ms from the strip's left edge",
      'abnormalities[].label': "short caption pinned above the trace, e.g. 'PVC'",
      gridMs: 'ms represented by one small (1 mm) grid square (default 40, paper standard)',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'reference'],
    domains: ['health'],
  }),
  createMeta('vitalstrip', {
    family: 'charts2',
    dataShapes: ['series', 'status', 'keyvalue'],
    requires: ['channels'],
    optional: ['title', 'icon', 'iconColor', 'windowLabel', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A multi-channel patient-monitor panel. Each channel (HR, BP, SpO₂, RR, temp…) stacks a mini trend line with its normal-range band shaded behind it and a big current read-out; any value falling outside the channel’s normal range is flagged (the row glows, the value turns red). The trend geometry, the band, and the out-of-range detection are all computed from the supplied series + range — it plots the numbers it is given and never fabricates a reading. For bedside monitoring, triage, and clinical explanations.',
    itemShapes: [{ prop: 'channels', text: 'label' }],
    propHints: {
      'channels[].label': "channel name, e.g. 'HR', 'SpO₂', 'RR'",
      'channels[].unit': "unit suffix on the read-out, e.g. 'bpm', '%', '°C'",
      'channels[].series': 'the trend samples as numbers, oldest → newest (left → right)',
      'channels[].current': 'the headline current value; defaults to the last sample when omitted',
      'channels[].normal':
        'the channel’s normal range as [low, high]; the band is shaded and excursions flagged',
      'channels[].color': 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
      windowLabel: "the time window the trends cover, e.g. 'last 30 min'",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['track', 'explain'],
    domains: ['health'],
  }),
  createMeta('growthcurve', {
    family: 'charts2',
    dataShapes: ['series', 'relationship', 'status'],
    requires: ['metric', 'percentiles', 'plotted'],
    optional: ['title', 'icon', 'iconColor', 'unit', 'ageUnit', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A pediatric percentile growth chart. Reference percentile curves (p3 … p97) fan out over an age axis; the child’s measured points are plotted on top and each landing is tracked to a percentile by interpolating the fan AT that exact age, so the standing read-out is computed, never invented. The median curve is emphasised and the outer band tinted. Both the reference curves and the child’s track come from the data (real-data-only). For pediatrics, well-child visits, and growth-monitoring explanations.',
    propHints: {
      metric: "'weight'|'height'|'head' — drives the default y-axis title",
      unit: "value-axis unit suffix, e.g. 'kg', 'cm', 'lb'",
      ageUnit: "age-axis unit noun, e.g. 'months', 'years' (default 'months')",
      'percentiles[].p': 'the percentile this curve represents, e.g. 3, 15, 50, 85, 97',
      'percentiles[].points': 'the curve as {age, value} samples, ascending in age',
      'plotted[].age': 'the child’s age at this measurement, on the same scale as the curves',
      'plotted[].value': 'the measured weight / height / head circumference',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['track', 'quantify', 'explain'],
    domains: ['health'],
  }),
  createMeta('sleepcycle', {
    family: 'charts2',
    dataShapes: ['series', 'sequence', 'status'],
    requires: ['stages'],
    optional: ['title', 'icon', 'iconColor', 'bedtime', 'wake', 'cycles', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A one-night hypnogram. Sleep stages (Awake / REM / Light / Deep) on a categorical depth axis are traced as a stepped line across the hours of the night; REM spans are highlighted, bedtime and wake are marked, and the cycle count is reported. The step geometry, the time axis, the per-stage time totals, and the cycle count are all computed from the supplied spans — it plots the sleep architecture it is given and never fabricates a stage. For sleep science, sleep-tracker read-outs, and clinical explanations.',
    itemShapes: [{ prop: 'stages', text: 'stage', closedVocab: true }],
    propHints: {
      'stages[].stage': "'awake'|'rem'|'light'|'deep'",
      'stages[].fromMin': 'start of the span, in minutes from lights-out (= 0)',
      'stages[].toMin': 'end of the span, in minutes (>= fromMin)',
      bedtime: "clock label for lights-out under the left edge, e.g. '11:00 PM'",
      wake: "clock label for waking under the right edge, e.g. '7:00 AM'",
      cycles: 'number of completed sleep cycles; inferred from REM bouts when omitted',
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['explain', 'track'],
    domains: ['health'],
  }),
  createMeta('seasonband', {
    family: 'charts2',
    dataShapes: ['sequence', 'comparison', 'status'],
    requires: ['rows'],
    optional: ['title', 'icon', 'iconColor', 'nowMonth', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A 12-month seasonal calendar band. Each row (a crop, a flower, a fish) shows its active WINDOWS across a fixed Jan→Dec grid — in-season / planting / harvest / peak / bloom spans — with an optional "now" marker pinning today\'s month. Every x-position is computed from the month numbers (1=Jan…12=Dec); it never invents a month. For "what\'s in season when", planting/harvest calendars, bloom schedules, and any annually-recurring availability. Use gantt for a dated one-off project schedule, eratimeline for multi-year history.',
    itemShapes: [{ prop: 'rows', text: 'label' }],
    propHints: {
      'rows[].windows[].from': 'first active month, inclusive (1 = Jan … 12 = Dec)',
      'rows[].windows[].to': 'last active month, inclusive (>= from)',
      'rows[].windows[].kind':
        "'peak'|'available'|'planting'|'harvest'|'bloom' (default 'available')",
      nowMonth: "highlight today's month with a vertical marker, 1 (Jan) … 12 (Dec)",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)|var(--danger)',
    },
    intents: ['plan', 'reference'],
    domains: ['cooking', 'nature', 'home'],
  }),
  createMeta('roccurve', {
    family: 'charts2',
    dataShapes: ['series', 'comparison', 'relationship'],
    requires: ['curves'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'operatingPoint',
      'xLabel',
      'yLabel',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.84,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'ROC (Receiver Operating Characteristic) curve: TPR vs FPR at each decision threshold, with the chance diagonal, shaded AUC area, and a draggable operating-point marker. Compare multiple classifiers or diagnostic tests on the same axes. The model supplies the (fpr, tpr) point cloud and AUC; dragging explores trade-offs without fabricating data. Use for classifier evaluation, diagnostic test sensitivity/specificity, model selection.',
    itemShapes: [{ prop: 'curves', text: 'name', textAliases: ['label', 'model', 'classifier'] }],
    propHints: {
      'curves[].name': 'classifier or model name shown in the legend',
      'curves[].points': 'array of { fpr, tpr, threshold? } in ascending fpr order',
      'curves[].auc': 'area under curve 0-1 (model-supplied, not recomputed)',
      operatingPoint: '0-based index into the first curve points for the initial marker position',
    },
    intents: ['explain', 'compare', 'reference'],
    domains: ['data', 'code', 'science', 'health'],
  }),
  createMeta('surfaceplot', {
    family: 'charts2',
    dataShapes: ['relationship', 'distribution'],
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Scalar field z = f(x,y) rendered as a 2-D heatmap with optional marching-squares contour isolines (mode "contour", default), a flat heatmap without isolines (mode "filled"), or an oblique 3-D projection (mode "surface3d"). Color ramp goes from insight (low) through presence (mid) to warning (high). Use for multivariable calculus (gradient fields, saddle points, Lagrange multipliers), heat distribution, probability density surfaces, and topographic elevation. The model supplies a row-major grid of z-values; all geometry is computed.',
    requires: ['title', 'grid'],
    optional: ['mode', 'levels', 'xLabel', 'yLabel', 'zLabel', 'zRange', 'caption'],
    propHints: {
      grid: '2-D number[][] row-major array of z-values; grid[0] is the top row',
      mode: '"contour" (default) | "filled" | "surface3d"',
      levels: 'number of contour threshold bands (default 6)',
      zRange: '[min, max] override; omit to auto-compute from grid',
    },
    intents: ['explain', 'visualize', 'teach'],
    domains: ['math', 'science', 'data'],
  }),
  createMeta('gradientdescent', {
    family: 'charts2',
    dataShapes: ['relationship', 'sequence'],
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A loss surface — contour isolines over a 2-D grid of (x, y, z) samples — with an optimizer's actual descent path traced over it as a drawn-on trail with step markers. Use for gradient descent, learning-rate/convergence intuition, and optimization landscapes (saddle points, local minima, ravines). The model supplies both the real loss grid and the real visited points; no curve is fitted or fabricated.",
    requires: ['contour', 'path'],
    optional: ['title', 'icon', 'iconColor', 'learningRate', 'footer'],
    propHints: {
      contour:
        'row-major 2-D array of { x, y, z } loss samples — a rectilinear mesh, grid[0] is the top row',
      path: "array of { x, y, step } — the optimizer's actual visited points, in step order",
      learningRate: "the optimizer's step size, shown as a caption",
    },
    intents: ['explain', 'visualize', 'teach'],
    domains: ['math', 'science', 'data', 'code'],
  }),
  createMeta('biasvariance', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison'],
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'The canonical bias-variance tradeoff diagram: training error falling and test error forming a U-shape as model complexity rises, with an optional shaded "sweet spot" band at the best-generalizing complexity. Use for overfitting/underfitting intuition, model-selection and regularization discussions, and explaining the complexity/generalization tradeoff. Three parallel arrays plot straight through — nothing is curve-fit.',
    requires: ['complexity', 'trainError', 'testError'],
    optional: ['title', 'icon', 'iconColor', 'sweetSpot', 'footer'],
    propHints: {
      complexity: 'ascending model-complexity x-values, one per sample',
      trainError: 'training error at each complexity level, same length as complexity',
      testError: 'held-out/test error at each complexity level, same length as complexity',
      sweetSpot: 'complexity value to shade as the best-generalizing point, if known',
    },
    intents: ['explain', 'visualize', 'teach'],
    domains: ['math', 'science', 'data', 'code'],
  }),
  createMeta('timeseriesdecomposition', {
    family: 'charts2',
    dataShapes: ['series', 'structure'],
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "STL-style time series decomposition: observed, trend, seasonal, and residual plotted as four small panels stacked on one shared x-axis, each with its own y-scale so a small seasonal/residual swing stays readable next to a much larger observed series. Use for forecasting explainers, seasonality analysis, and anomaly discussions (residual spikes). All four series are the caller's real numbers — nothing is filtered or smoothed here.",
    requires: ['dates', 'observed', 'trend', 'seasonal', 'residual'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    propHints: {
      dates: 'x-axis labels, one per sample (only shown under the bottom panel)',
      observed: 'the raw series',
      trend: 'the long-run trend component, same length as dates',
      seasonal: 'the repeating seasonal component, same length as dates',
      residual: "what's left after removing trend and seasonal — the noise/anomaly component",
    },
    intents: ['explain', 'analyze', 'visualize'],
    domains: ['data', 'business', 'science'],
    stringItems: ['dates'],
  }),
  createMeta('precisionrecallcurve', {
    family: 'charts2',
    dataShapes: ['series', 'comparison', 'relationship'],
    requires: ['curves'],
    optional: ['title', 'icon', 'iconColor', 'avgPrecision', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "Precision-recall curve for classifier evaluation: precision (y) vs recall (x) across decision thresholds, with a shaded area-under-curve fill. Unlike ROC there is no chance-diagonal (a PR curve's no-skill baseline depends on class prevalence, which this component is never given, so none is drawn). Prefer this over ROC on imbalanced classes, where ROC can look misleadingly good. Compare multiple classifiers on the same axes; an optional average-precision badge summarizes the primary curve.",
    itemShapes: [{ prop: 'curves', text: 'label', textAliases: ['name', 'model', 'classifier'] }],
    propHints: {
      'curves[].label': 'classifier or model name shown in the legend',
      'curves[].points':
        'array of { precision, recall, threshold? } — any order, sorted by recall to draw',
      avgPrecision:
        'area under the PR curve, 0-1 (model-supplied, not recomputed) — shown as an AP badge',
    },
    intents: ['explain', 'compare', 'reference'],
    domains: ['data', 'code', 'science', 'health'],
  }),
  createMeta('chromatogram', {
    family: 'charts2',
    dataShapes: ['series', 'composition'],
    requires: ['title', 'peaks'],
    optional: ['icon', 'iconColor', 'method', 'trace', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'An HPLC/GC chromatography readout: detector signal over retention time with each eluting peak apex labeled (RT, compound, area%) and its real integrated region shaded between the valleys either side of it. Give `trace` for the full baseline; without it, only the peak results table renders — never a fabricated baseline shape. Use for analytical chemistry, purity checks, and separation science.',
    propHints: {
      method: 'instrument/method line, e.g. "HPLC · C18, 1.0 mL/min, 254 nm"',
      'trace[].t': 'retention time, in minutes unless stated otherwise',
      'trace[].signal': 'detector response (mAU or counts) at that time',
      'peaks[].rt': 'retention time of the peak apex',
      'peaks[].label': 'compound identity, e.g. "Caffeine"',
      'peaks[].areaPct': 'percent of total integrated area, 0-100',
      'peaks[].height': 'peak height in detector units',
    },
    intents: ['explain', 'reference', 'quantify'],
    domains: ['science', 'education'],
  }),
  createMeta('stressstraincurve', {
    family: 'charts2',
    dataShapes: ['series', 'relationship'],
    requires: ['title', 'curve'],
    optional: ['icon', 'iconColor', 'yieldPoint', 'ultimatePoint', 'fracturePoint', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A material's engineering stress-strain diagram, plotted straight from the tensile-test curve. When `yieldPoint` is given, the elastic region (up to yield) is shaded and a Young's-modulus slope is computed from the curve's own first sample and the yield point. Yield/ultimate-tensile/fracture points are each independently optional and called out with a labeled leader line. Use for materials science, mechanical engineering, and manufacturing QA — never for a curve the model hasn't actually sampled.",
    propHints: {
      'curve[].strain': 'engineering strain, dimensionless (e.g. 0.02 = 2%)',
      'curve[].stress':
        "engineering stress, in the material's own unit (MPa unless stated otherwise)",
      yieldPoint: '{ strain, stress } where plastic deformation begins',
      ultimatePoint: '{ strain, stress } at the curve peak — ultimate tensile strength',
      fracturePoint: '{ strain, stress } where the sample actually broke',
    },
    intents: ['explain', 'reference', 'quantify'],
    domains: ['science', 'engineering', 'education'],
  }),
  createMeta('gatingplot', {
    family: 'charts2',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'xLabel', 'yLabel', 'points'],
    optional: ['icon', 'iconColor', 'xScale', 'yScale', 'gates', 'footer'],
    interactive: true,
    wowWeight: 0.84,
    tier: 'cutting',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    blurb:
      "A flow-cytometry gating plot: the raw event point-cloud on linear or log axes, with translucent gate boundaries (ellipse or polygon) drawn over the populations they enclose, each labeled with its name and percent-of-parent. Click a gate or its legend chip to isolate that population. Use for immunology, cell biology, and clinical flow-cytometry panels — never invents a gate boundary the model wasn't given.",
    itemShapes: [{ prop: 'gates', text: 'name', textAliases: ['label', 'population', 'gateName'] }],
    propHints: {
      xScale: "'linear' (default) | 'log' — fluorescence channels commonly need log",
      yScale: "'linear' (default) | 'log'",
      'points[].gate': '0-based index into `gates` this event was assigned to; omit for ungated',
      'gates[].shape': "'ellipse' | 'polygon'",
      'gates[].region':
        'ellipse: exactly [[cx,cy],[rx,ry]] (center, then radii). polygon: 3+ [x,y] vertices in order.',
      'gates[].pctOfParent': 'percent of the parent population this gate captures, 0-100',
    },
    intents: ['explain', 'reference', 'quantify'],
    domains: ['science', 'health'],
  }),
  createMeta('gellane', {
    family: 'charts2',
    dataShapes: ['composition', 'comparison'],
    requires: ['title', 'lanes'],
    optional: ['icon', 'iconColor', 'ladder', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A gel electrophoresis lane readout: vertical sample lanes on a gel backdrop with blurred bands positioned by migration distance and shaded by intensity, plus an optional size ladder with tick labels. Use for molecular biology (DNA/RNA gels, Western blots, PCR product checks) — band position and darkness come straight from the data, nothing is fit or estimated.',
    itemShapes: [
      {
        prop: 'lanes',
        text: 'label',
        textAliases: ['name', 'sample'],
        children: { prop: 'bands' },
      },
    ],
    propHints: {
      'lanes[].bands[].pos':
        '0-1 migration distance from the well; 0 = top (well), 1 = bottom (dye front)',
      'lanes[].bands[].intensity': '0-1 band darkness/brightness',
      'lanes[].bands[].sizeLabel': 'size shown beside the band, e.g. "480 bp" or "42 kDa"',
      ladder:
        '{ unit: "bp"|"kDa", marks: [...] } — a standard ladder lane drawn first, any mark order',
    },
    intents: ['explain', 'reference', 'quantify'],
    domains: ['science', 'education'],
  }),
  createMeta('flightchart', {
    family: 'charts2',
    dataShapes: ['sequence', 'comparison'],
    requires: ['title', 'channels', 'flights'],
    optional: ['icon', 'iconColor', 'totalBudget', 'currency', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A media flight/budget chart: channels as horizontal lanes, each flight a bar across the timeline sized and labeled by spend, with a total-spend readout. Use for marketing/ad campaign planning across channels — never for a project schedule with dependencies, use gantt.',
    itemShapes: [
      { prop: 'channels', text: 'name', textAliases: ['label', 'channel'] },
      { prop: 'flights', text: 'channel', textAliases: ['lane', 'name'] },
    ],
    propHints: {
      'flights[].start': '0-based period index the flight starts in',
      'flights[].span': 'how many periods the flight runs, minimum 1',
      'flights[].budget': 'spend for that one flight',
      currency: 'ISO 4217 code, e.g. "USD" — defaults to USD',
    },
    intents: ['plan', 'quantify', 'reference'],
    domains: ['business'],
  }),
  createMeta('paybandchart', {
    family: 'charts2',
    dataShapes: ['comparison', 'status'],
    requires: ['title', 'role', 'min', 'mid', 'max', 'markers'],
    optional: ['icon', 'iconColor', 'currency', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An HR compensation band: a role’s min–mid–max range as a bullet-style track, with named offers/incumbents plotted inside it. A marker flagged as an equity-watch case (compression, off-cycle exception) gets a distinct accent. Use for comp bands, offer positioning, pay-equity review — never for a plain min/max range with no named people on it.',
    itemShapes: [{ prop: 'markers', text: 'name', textAliases: ['label', 'person', 'employee'] }],
    propHints: {
      'markers[].value': 'that person/offer’s comp, same unit as min/mid/max',
      'markers[].flag': 'true marks it an equity-watch case, drawn with the warning accent',
      currency: 'ISO 4217 code, e.g. "USD" — defaults to USD',
    },
    intents: ['reference', 'quantify', 'decide'],
    domains: ['business'],
  }),
  createMeta('linebalance', {
    family: 'charts2',
    dataShapes: ['comparison', 'series'],
    requires: ['title', 'takt', 'stations'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A manufacturing line-balance/takt chart: one bar per station’s real cycle time, with a dashed takt-time reference line spanning every bar. Any station whose cycle time clears takt flips to the warning tint and is labeled a bottleneck. Use for assembly-line balancing, station-by-station throughput — never for a generic time series, use chart.',
    itemShapes: [{ prop: 'stations', text: 'name', textAliases: ['label', 'station'] }],
    propHints: {
      takt: 'takt time — the pace demand sets, same unit as every station’s cycleTime',
      'stations[].cycleTime': 'that station’s measured cycle time',
      'stations[].bottleneck': 'true forces the bottleneck tint even if under takt',
    },
    intents: ['reference', 'quantify', 'track'],
    domains: ['business', 'design'],
  }),
  createMeta('epicurve', {
    family: 'charts2',
    dataShapes: ['series', 'composition'],
    requires: ['title', 'cases'],
    optional: ['icon', 'iconColor', 'threshold', 'phases', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'An epidemiological epi curve: case counts per period, stacked and colored by diagnostic classification (confirmed/probable/suspected), with an optional dashed alert-threshold line and dotted vertical markers for named interventions/events. Use for outbreak surveillance over time — never for a single running total, use chart.',
    itemShapes: [
      { prop: 'cases', text: 'period', textAliases: ['label', 'week', 'date', 'time'] },
      { prop: 'phases', text: 'label', textAliases: ['name', 'event'] },
    ],
    propHints: {
      'cases[].classification': "'confirmed' | 'probable' | 'suspected' — omit for unclassified",
      threshold: '{ value, label } — drawn as a dashed reference line',
      'phases[].period': 'must match one of cases[].period; a non-matching phase is dropped',
    },
    intents: ['reference', 'quantify', 'track'],
    domains: ['health', 'science'],
  }),
  createMeta('pareto', {
    family: 'charts2',
    dataShapes: ['ranking', 'composition'],
    requires: ['title', 'bars'],
    optional: ['icon', 'iconColor', 'cumulative', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'An 80/20 Pareto chart: bars sorted descending by frequency/value, with a cumulative-percent line on a dual right axis and an 80% guide line. The bars carrying the line up to that guide are highlighted. Use to find the vital few causes behind most of an effect — never for data with no meaningful "which few matter most" read, use bars.',
    itemShapes: [
      { prop: 'bars', text: 'label', textAliases: ['name', 'category', 'reason', 'cause'] },
    ],
    intents: ['reference', 'quantify', 'decide'],
    domains: ['business', 'data'],
  }),
  createMeta('populationpyramid', {
    family: 'charts2',
    dataShapes: ['comparison', 'composition'],
    requires: ['title', 'bands', 'leftLabel', 'rightLabel'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A demographic population pyramid: mirrored horizontal bars from a shared center axis, one row per age band, both sides sharing one scale so bar length is comparable across the whole chart. Use for age/sex population structure — never for a plain two-series comparison with no natural left/right split, use dumbbell.',
    itemShapes: [{ prop: 'bands', text: 'label', textAliases: ['age', 'group', 'range'] }],
    propHints: {
      leftLabel: 'header over the left bars, e.g. "Male"',
      rightLabel: 'header over the right bars, e.g. "Female"',
      'bands[].left': "the left side's real count for that age band",
      'bands[].right': "the right side's real count for that age band",
    },
    intents: ['reference', 'explain'],
    domains: ['science', 'business'],
  }),
  createMeta('parallelcoordinates', {
    family: 'charts2',
    dataShapes: ['relationship', 'comparison'],
    requires: ['title', 'axes', 'lines'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.79,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A parallel-coordinates plot: one vertical axis per variable, each observation drawn as a line connecting its own position on every axis, each axis normalized to its own real min/max. Hover a line or its legend chip to isolate it. Use to compare several options/observations across MANY variables at once — never for just two variables, use scatterregression.',
    itemShapes: [
      { prop: 'axes', text: 'key', textAliases: ['id', 'field', 'name'] },
      { prop: 'lines', text: 'label', textAliases: ['name', 'series'] },
    ],
    propHints: {
      'axes[].label': 'display name for the axis; falls back to its key when omitted',
      'axes[].domain': 'optional fixed [min,max]; omit to normalize from the real data',
      'lines[].values': 'object keyed by each axes[].key — a missing key just skips that axis',
    },
    intents: ['reference', 'decide', 'quantify'],
    domains: ['data', 'business', 'science'],
  }),
  createMeta('scatterplotmatrix', {
    family: 'charts2',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'vars', 'rows'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.77,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A scatterplot matrix (pairs plot): an NxN grid of small scatter plots, one per pair of variables, sharing each variable’s own real min/max whether it lands on a row or a column. Diagonal cells show the variable name instead of plotting it against itself. Use to eyeball correlations across MANY variables at once — never for just two, use scatterregression.',
    propHints: {
      vars: 'the variable names, in display order — every row/column of the grid',
      rows: 'one object per real observation, keyed by each name in vars to its numeric value',
    },
    intents: ['reference', 'quantify'],
    domains: ['data', 'science'],
    stringItems: ['vars'],
  }),
  createMeta('pictogramchart', {
    family: 'charts2',
    dataShapes: ['composition'],
    requires: ['title', 'categories'],
    optional: ['icon', 'iconColor', 'unitValue', 'footer'],
    interactive: false,
    wowWeight: 0.73,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A true icon-array (isotype) chart: the same 100-glyph grid as waffle, but each cell renders the category’s own icon instead of a plain color square, with a "1 glyph = N units" key. Use when the units being counted have a natural real-world glyph (people, votes, days, vehicles) — for a plain percentage breakdown with no meaningful per-unit icon, use waffle instead.',
    itemShapes: [{ prop: 'categories', text: 'label', textAliases: ['name', 'category'] }],
    propHints: {
      'categories[].icon':
        'an existing icon key, e.g. "sun"|"rain"|"walk"|"bus"|"car" — invalid keys fall back to a default glyph',
      unitValue: 'real units per glyph; omit to auto-fit the whole chart under 100 glyphs',
    },
    intents: ['reference', 'quantify'],
    domains: ['data', 'education'],
  }),
  createMeta('qqplot', {
    family: 'charts2',
    dataShapes: ['distribution', 'comparison'],
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'Quantile-quantile plot: sorts sample values and plots them against the theoretical quantiles of a reference distribution (default normal). The IQR-based reference line is drawn automatically. Points that hug the line indicate a good distributional fit; systematic deviations reveal skewness, heavy tails, or multimodality. Use for normality testing, residual diagnostics, and distribution comparison in statistics courses and data analysis.',
    requires: ['title', 'values'],
    optional: ['distribution', 'xlabel', 'ylabel'],
    propHints: {
      values: 'raw numeric sample data array — the component sorts and computes quantiles',
      distribution: '"normal" (default, only option currently supported)',
    },
    intents: ['analyze', 'visualize', 'explain'],
    domains: ['data', 'math', 'science'],
  }),
  createMeta('samplingdistribution', {
    family: 'charts2',
    dataShapes: ['distribution'],
    requires: [],
    optional: ['title', 'icon', 'iconColor', 'population', 'sampleSize', 'numSamples', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Central Limit Theorem demonstration — three linked panels: population histogram (top-left), a single sample dot strip (top-right), and the sampling distribution of sample means (bottom) with theoretical N(\u03bc, \u03c3\u00b2/n) overlay. Deterministic simulation (no Math.random) for stable renders.',
    propHints: {
      'population.shape': "'uniform' | 'skewed' | 'bimodal' — default skewed",
      sampleSize: 'n per sample, default 30',
      numSamples: 'number of simulated samples, default 200',
    },
    intents: ['teach', 'explain'],
    domains: ['education'],
  }),
  createMeta('hrdiagram', {
    family: 'charts2',
    dataShapes: ['distribution', 'comparison'],
    requires: ['title', 'stars'],
    optional: ['icon', 'iconColor', 'showRegions', 'highlight', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A Hertzsprung–Russell diagram: stars on an inverted log temperature axis (hot O/B stars left, cool K/M right) against log luminosity in solar units, with spectral-class letters, soft bands for the main sequence / giants / supergiants / white dwarfs, and the Sun as a fixed reference at 5772 K, 1 L☉. Use for stellar classification and stellar evolution. Never for a generic two-variable scatter — use scatterregression.',
    itemShapes: [{ prop: 'stars', text: 'name', textAliases: ['label', 'star'] }],
    propHints: {
      'stars[].tempK': 'surface temperature in Kelvin — must be > 0 (the axis is logarithmic)',
      'stars[].luminosity':
        'luminosity in SOLAR units (Sun = 1), e.g. Betelgeuse ~126000, Proxima ~0.0017 — must be > 0',
      'stars[].stage':
        "'main-sequence' | 'giant' | 'supergiant' | 'white-dwarf' — sizes and tints the dot; omit when unknown",
      highlight: 'name of ONE star (matching stars[].name) to ring and label persistently',
      showRegions: 'default true — the soft population bands carry most of the teaching value',
    },
    intents: ['teach', 'explain', 'reference'],
    domains: ['science', 'education'],
  }),
  createMeta('ternaryplot', {
    family: 'charts2',
    dataShapes: ['composition', 'comparison'],
    requires: ['title', 'axes', 'points'],
    optional: ['icon', 'iconColor', 'zones', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A ternary (barycentric) plot: three-part compositions inside an equilateral triangle, each point normalized by its own a+b+c sum so any raw scale works, with 20% gridlines parallel to every edge and optional translucent zone polygons (soil-texture classes, alloy phases, color mixes). Use when every observation is a three-component mixture of a whole. Never for a single part-to-whole breakdown — use piedonut.',
    itemShapes: [
      { prop: 'points', text: 'label', textAliases: ['name', 'sample'] },
      {
        prop: 'zones',
        text: 'label',
        textAliases: ['name', 'class'],
        children: { prop: 'vertices' },
      },
    ],
    propHints: {
      axes: '{ a, b, c } corner labels — a is the TOP apex, b bottom-left, c bottom-right',
      'points[].a':
        "that point's amount of component a (same for b/c) — any scale; each point is normalized by its own a+b+c sum",
      'zones[].vertices': '3+ {a,b,c} corners of a region polygon, normalized like points',
      unit: 'unit the raw values are in, e.g. "%" — appended to the corner labels',
    },
    intents: ['explain', 'quantify', 'reference'],
    domains: ['science', 'education'],
  }),
  createMeta('parliamentseats', {
    family: 'charts2',
    dataShapes: ['composition', 'ranking'],
    requires: ['title', 'parties'],
    optional: ['icon', 'iconColor', 'totalLabel', 'footer'],
    interactive: true,
    wowWeight: 0.84,
    tier: 'frontier',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A hemicycle parliament chart: one dot per seat packed into concentric arc rows, parties filling contiguous wedges left to right in array order, with a majority marker at the top-center aisle, a big center total, and clickable legend chips that isolate a party. Use for legislature/council/committee seat counts — real WHOLE seat numbers. Never for part-to-whole percentages — use piedonut/waffle.',
    itemShapes: [{ prop: 'parties', text: 'name', textAliases: ['label', 'party'] }],
    propHints: {
      'parties[].seats': 'whole number of seats won — a count, never a percentage',
      totalLabel: 'label under the big center total, defaults to "seats"',
    },
    intents: ['explain', 'quantify'],
    domains: ['education', 'business'],
  }),
];
