// Catalog entries for the `charts1` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_CHARTS1: ComponentCatalog = [
  // — charts1 —
  createMeta('treemap', {
    family: 'charts1',
    dataShapes: ['hierarchy', 'composition'],
    requires: ['title', 'root'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Nested hierarchical data as proportional rectangles; shows part-to-whole at multiple levels.',
  }),
  createMeta('sunburst', {
    family: 'charts1',
    dataShapes: ['hierarchy', 'composition'],
    requires: ['title', 'root'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Radial hierarchy; nested rings show multiple levels from center outward.',
  }),
  createMeta('sankey', {
    family: 'charts1',
    dataShapes: ['flow', 'relationship'],
    requires: ['title', 'nodes', 'links'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.85,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Flow diagram showing how quantities move between layered stages; reveals bottlenecks and splits.',
  }),
  createMeta('network', {
    family: 'charts1',
    dataShapes: ['relationship', 'hierarchy'],
    requires: ['title', 'nodes', 'edges'],
    optional: ['icon', 'iconColor', 'layout', 'footer'],
    interactive: false,
    wowWeight: 0.88,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Graph of interconnected entities with circle or grid layout; shows topology and clusters.',
  }),
  createMeta('radar', {
    family: 'charts1',
    dataShapes: ['comparison', 'series'],
    requires: ['title', 'axes', 'series'],
    optional: ['icon', 'iconColor', 'max', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Multi-axis comparison of one or more series; highlights strengths and gaps across dimensions.',
    stringItems: ['axes'],
  }),
  createMeta('waterfall', {
    family: 'charts1',
    dataShapes: ['flow', 'comparison'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Cascading bars showing incremental change; bridges starting value to ending total.',
  }),
  createMeta('funnel', {
    family: 'charts1',
    dataShapes: ['flow', 'ranking'],
    requires: ['title', 'stages'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Progressive narrowing through stages where each stage is a SUBSET of the one above — conversion/retention drop-off (signups → trials → paid). Never for a plain ranked list or unrelated categories — use leaderboard or bars.',
  }),
  createMeta('histogram', {
    family: 'charts1',
    dataShapes: ['distribution'],
    requires: ['title', 'bins'],
    optional: ['icon', 'iconColor', 'unit', 'color', 'marker', 'markerLabel', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Frequency distribution; bin-based view with optional reference marker (mean, median, etc).',
  }),
  createMeta('boxplot', {
    family: 'charts1',
    dataShapes: ['distribution', 'comparison'],
    requires: ['title', 'groups'],
    optional: ['icon', 'iconColor', 'unit', 'domain', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Quartile-based summary (min/Q1/median/Q3/max + outliers) per group; compares spread and skew.',
  }),
  createMeta('streamgraph', {
    family: 'charts1',
    dataShapes: ['series', 'composition'],
    requires: ['title', 'ticks', 'series'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.79,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Stacked flow over time; smooth curves reveal how composition evolves and peaks shift.',
    stringItems: ['ticks'],
  }),
  createMeta('correlationheatmap', {
    family: 'charts1',
    dataShapes: ['relationship', 'tabular'],
    requires: ['title', 'variables', 'matrix'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Numeric correlation matrix (Pearson/Spearman/etc.) between N variables, diverging color by strength and sign — red for negative, presence-blue for positive, neutral near zero. For pairwise relationships across many variables at once, not a single x-vs-y scatter.',
    propHints: {
      variables: 'ordered variable names, same order on both axes',
      matrix:
        'square N×N array, matrix[i][j] = correlation of variables[i] with variables[j], each in [-1, 1]',
    },
    stringItems: ['variables'],
  }),
  createMeta('bcgmatrix', {
    family: 'charts1',
    dataShapes: ['comparison', 'relationship'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'BCG growth-share matrix: a portfolio of products or business units scattered by market growth (y) vs. relative market share (x), split into Star/Question-Mark/Cash-Cow/Dog by the portfolio median. Bubble size carries revenue when given. Use for product-portfolio strategy, investment prioritization across business lines, "which bets to double down on vs. divest".',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'product'] }],
    propHints: {
      'items[].growth': 'market growth rate in percent, e.g. 18 for +18% YoY; can be negative',
      'items[].share':
        'relative market share vs. the category leader, e.g. 1.4 = 1.4x the #2 player',
      'items[].revenue': 'optional — sizes the bubble; omit and every bubble matches',
      'items[].note': 'optional one-line context shown on hover',
    },
    intents: ['decide', 'analyze', 'compare'],
    domains: ['business'],
  }),
  createMeta('flowchord', {
    family: 'charts1',
    dataShapes: ['flow', 'relationship'],
    requires: ['title', 'nodes', 'flows'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Circular relationship/flow diagram: named entities ring the perimeter, and flows between them draw as arced ribbons sized by value — like a Sankey bent into a circle. Reads two-way movement between the SAME nodes (a gain and a loss) cleanly, which a layered Sankey cannot. Use for trade/migration between regions, budget movement between departments, account movement between tiers, traffic between services.',
    itemShapes: [{ prop: 'nodes', text: 'label', textAliases: ['name', 'title', 'id'] }],
    propHints: {
      'nodes[].id': 'a short stable key, referenced by flows[].from/to',
      'nodes[].label': 'the display name shown on the ring',
      'flows[].from': "a nodes[].id — the flow's source",
      'flows[].to': "a nodes[].id — the flow's destination",
      'flows[].value': 'numeric flow size; ribbon width scales with it',
    },
  }),
  createMeta('venn', {
    family: 'charts1',
    dataShapes: ['relationship', 'comparison'],
    requires: ['title', 'sets'],
    optional: ['icon', 'iconColor', 'overlaps', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Two or three overlapping circles; unique versus shared, with counts.',
  }),
  // — charts1 additions —
  createMeta('quadrant', {
    family: 'charts1',
    dataShapes: ['comparison'],
    requires: ['title', 'items'],
    optional: [
      'icon',
      'iconColor',
      'xLabel',
      'yLabel',
      'topRight',
      'topLeft',
      'bottomLeft',
      'bottomRight',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      '2×2 matrix — SWOT, Eisenhower, impact-effort; plots items by position in four labeled quadrants.',
    itemShapes: [
      {
        prop: 'items',
        text: 'label',
        textAliases: ['name', 'title', 'text'],
        requiredFields: ['quadrant'],
      },
    ],
    propHints: {
      'items[].quadrant': "'topRight'|'topLeft'|'bottomRight'|'bottomLeft'",
    },
  }),
  // — charts1 additions (pie/distribution) —
  createMeta('piedonut', {
    family: 'charts1',
    dataShapes: ['composition'],
    requires: ['title', 'slices'],
    optional: ['icon', 'iconColor', 'unit', 'hole', 'centerValue', 'centerLabel', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    coercer: 'generic',
    blurb: 'Pie or donut chart split; each slice is a named portion with value and optional label.',
    itemShapes: [{ prop: 'slices', text: 'label', textAliases: ['name', 'category', 'segment'] }],
  }),
  createMeta('distributioncurve', {
    family: 'charts1',
    dataShapes: ['distribution'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'kind',
      'mean',
      'sd',
      'points',
      'shadeFrom',
      'shadeBetween',
      'markers',
      'unit',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Smooth bell curve with mean/±σ bands; shades a highlight region under the curve.',
    propHints: {
      kind: "'normal'|'custom'",
      'markers[].color': 'optional accent for marker line',
    },
  }),
  createMeta('latencydist', {
    family: 'charts1',
    dataShapes: ['distribution'],
    requires: ['title', 'bins'],
    optional: [
      'icon',
      'iconColor',
      'unit',
      'p50',
      'p90',
      'p95',
      'p99',
      'slo',
      'sloLabel',
      'caption',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Latency distribution histogram with p50/p90/p95/p99 markers and an SLO threshold line that turns red when the p99 tail breaches it — the classic latency-vs-SLO view for an API or dashboard.',
    propHints: {
      unit: "latency unit, usually 'ms' (default) or 's'",
      sloLabel: "short label for the SLO line, e.g. 'SLO 200ms'",
      iconColor: 'var(--presence)|var(--insight)|var(--warning)',
    },
    domains: ['data', 'code', 'tech'],
    intents: ['quantify', 'explain'],
  }),
  createMeta('captable', {
    family: 'charts1',
    dataShapes: ['composition', 'tabular'],
    requires: ['title', 'holders'],
    optional: ['icon', 'iconColor', 'totalShares', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Startup capitalization table: a stacked ownership bar over a ledger of holders (founders, ESOP, investors) with share counts and fully-diluted %. FD% is computed from shares when not given.',
    itemShapes: [
      {
        prop: 'holders',
        text: 'name',
        textAliases: ['holder', 'label', 'who', 'investor'],
      },
    ],
    propHints: {
      'holders[].class': "share class, e.g. 'Common', 'Preferred Seed', 'Series A', 'Options'",
      'holders[].fdPct': 'fully-diluted percent (0..100); omit to derive from shares',
      totalShares: 'fully-diluted total for the % base; defaults to the sum of holder shares',
    },
    domains: ['money', 'business'],
    intents: ['quantify', 'explain'],
  }),
  createMeta('lifewheel', {
    family: 'charts1',
    dataShapes: ['comparison', 'composition'],
    requires: ['domains'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Wheel-of-life radial self-assessment: one spoke per life domain rated 0–10, a filled polygon whose roundness shows balance vs imbalance, and the felt score on each spoke. Reads how full and how even a life is at a glance.',
    itemShapes: [
      {
        prop: 'domains',
        text: 'label',
        textAliases: ['name', 'area', 'domain'],
      },
    ],
    propHints: {
      'domains[].score': 'felt rating 0..10 (clamped on render)',
      'domains[].note': 'optional one-line reflection shown on hover',
    },
    domains: ['health', 'business'],
    intents: ['reflect', 'track'],
  }),
  createMeta('violinplot', {
    family: 'charts1',
    dataShapes: ['distribution', 'comparison'],
    requires: ['groups'],
    optional: ['title', 'icon', 'iconColor', 'showBox', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Mirrored kernel-density estimate (KDE) per group with an embedded box plot — reveals full distribution shape, modes, and spread across multiple groups in one view. Better than a boxplot when the shape matters (bimodal, skewed). Each group is a {label, values, color?} object.',
    propHints: {
      'groups[].values': 'raw numeric array — at least 5 values per group',
      'groups[].color': 'optional CSS variable, e.g. var(--presence)',
      'groups[].label': 'group name shown on the axis',
      showBox: 'overlay embedded box plot, default true',
    },
    intents: ['compare', 'analyze', 'teach'],
    domains: ['education', 'science', 'data'],
  }),
  createMeta('stemleafplot', {
    family: 'charts1',
    dataShapes: ['distribution'],
    requires: ['values'],
    optional: ['title', 'icon', 'iconColor', 'title2', 'values2', 'leafUnit', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'Classic stem-and-leaf display — preserves exact data values while showing distribution shape in monospace. Optional back-to-back layout for side-by-side group comparison. Best for small integer datasets (n < 100). leafUnit adjusts which digit is the leaf.',
    propHints: {
      values: 'numeric array (integers work best)',
      leafUnit: 'each leaf represents this unit; default 1 (ones digit)',
      title2: 'label for the second dataset in back-to-back mode',
      values2: 'optional second dataset for back-to-back comparison',
    },
    intents: ['analyze', 'teach'],
    domains: ['education'],
  }),
  createMeta('tamsam', {
    family: 'charts1',
    dataShapes: ['composition', 'comparison'],
    requires: ['markets'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'TAM/SAM/SOM concentric ring chart: nested circles sized by market value, labelled with the acronym and dollar amount. Use for market-sizing decks, startup pitch slides, and investor materials where you need to show total addressable market vs. serviceable addressable vs. serviceable obtainable.',
    propHints: {
      'markets[]': '{label, value, unit?} — outermost ring first (TAM → SAM → SOM)',
      'markets[].label': 'e.g. "TAM", "SAM", "SOM"',
      'markets[].value': 'numeric market size',
      'markets[].unit': 'optional suffix — "B" for billions, "T" for trillions',
    },
    intents: ['analyze', 'compare'],
    domains: ['business', 'startup'],
  }),
];
