// Catalog entries for the `core` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_CORE: ComponentCatalog = [
  // — core —
  createMeta('insight', {
    family: 'core',
    dataShapes: ['scalar'],
    requires: ['title'],
    optional: ['summary', 'stat', 'delta', 'deltaDir', 'conf', 'sources'],
    interactive: false,
    wowWeight: 0.35,
    tier: 'base',
    colDefault: 4,
    colMin: 3,
    coercer: 'custom',
    blurb: 'A headline number with optional delta and confidence \u2014 the primary insight unit.',
  }),
  createMeta('chart', {
    family: 'core',
    dataShapes: ['series'],
    requires: ['title', 'labels', 'series'],
    optional: ['unit', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    blurb: 'Time-series trend chart with multiple series, areas, and optional axes.',
  }),
  createMeta('breakdown', {
    family: 'core',
    dataShapes: ['composition'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'conf'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'custom',
    blurb: 'A split of parts with percentages, values, tags, and heat indicators.',
  }),
  createMeta('timeline', {
    family: 'core',
    dataShapes: ['sequence'],
    requires: ['events'],
    optional: ['eyebrow', 'title', 'footer'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    blurb: 'Ordered steps or events with times, tags, and colors.',
  }),
  createMeta('list', {
    family: 'core',
    dataShapes: ['list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor'],
    interactive: false,
    wowWeight: 0.3,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'custom',
    blurb: 'A title with bullet points, tips, or plain-text items.',
  }),
  createMeta('compare', {
    family: 'core',
    dataShapes: ['comparison'],
    requires: ['options', 'criteria'],
    optional: ['eyebrow', 'recommendation'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'custom',
    blurb: 'Side-by-side options scored against criteria with a pick state and recommendation.',
  }),
  createMeta('ring', {
    family: 'core',
    dataShapes: ['composition', 'status'],
    requires: ['title', 'rings'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'custom',
    blurb: 'Concentric rings showing completion, health, or multi-metric progress.',
  }),
  createMeta('bars', {
    family: 'core',
    dataShapes: ['ranking', 'comparison'],
    requires: ['title', 'bars'],
    optional: ['icon', 'iconColor', 'unit', 'goal', 'goalLabel', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    blurb: 'Vertical bars with optional goal line and heat indicators.',
  }),
  createMeta('stack', {
    family: 'core',
    dataShapes: ['composition'],
    requires: ['title', 'segments'],
    optional: ['icon', 'iconColor', 'total', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    blurb: 'A horizontal bar split into colored segments with labels and totals.',
  }),
  createMeta('scatter', {
    family: 'core',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'points'],
    optional: ['icon', 'iconColor', 'xLabel', 'yLabel', 'xDomain', 'yDomain', 'trend', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'X/Y point cloud with optional domains, trend line, and heat.',
  }),
  createMeta('heat', {
    family: 'core',
    dataShapes: ['tabular', 'distribution'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'cols', 'levelColor', 'legend', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'custom',
    blurb: 'A 2D grid of heat-colored cells with row/column headers and optional marks.',
  }),
  createMeta('flow', {
    family: 'core',
    dataShapes: ['flow'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'A process or funnel with sequential steps, subtitles, and colors.',
  }),
  createMeta('web', {
    family: 'core',
    dataShapes: ['list', 'text'],
    requires: ['results'],
    optional: ['title', 'live', 'footer'],
    interactive: false,
    wowWeight: 0.45,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Search results with titles, domains, excerpts, and optional live refresh.',
  }),
  createMeta('gallery', {
    family: 'core',
    dataShapes: ['media'],
    requires: ['items'],
    optional: ['title', 'eyebrow', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'A grid of images with captions, tags, and optional headers.',
  }),
  createMeta('codemap', {
    family: 'core',
    dataShapes: ['code', 'hierarchy'],
    requires: ['center', 'nodes'],
    optional: ['title', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'A central concept with related code nodes, notes, and heat.',
  }),
  createMeta('diff', {
    family: 'core',
    dataShapes: ['code', 'text'],
    requires: ['file', 'add', 'del', 'lines'],
    optional: ['title', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'A code diff with add/del counts and highlighted lines.',
  }),
  createMeta('checks', {
    family: 'core',
    dataShapes: ['status'],
    requires: ['items'],
    optional: ['title', 'summary', 'footer'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Test or validation results with pass/fail/skip status and notes.',
  }),
  createMeta('donut', {
    family: 'core',
    dataShapes: ['composition'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'size', 'thickness', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'custom',
    blurb: 'A pie or donut split into colored wedges with percentages.',
  }),
  createMeta('gauge', {
    family: 'core',
    dataShapes: ['scalar', 'status'],
    requires: ['title', 'value'],
    optional: ['icon', 'iconColor', 'max', 'size', 'color', 'band', 'driver', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'custom',
    blurb: 'A radial dial showing progress, NPS, or readiness with optional driver text.',
  }),
  createMeta('scoreboard', {
    family: 'core',
    dataShapes: ['comparison', 'keyvalue'],
    requires: ['games'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Sports game scores with away/home teams, status, and heat.',
  }),
  createMeta('standings', {
    family: 'core',
    dataShapes: ['ranking', 'tabular'],
    requires: ['rows'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'A league table with team, record, and games-behind columns.',
  }),
  createMeta('pipeline', {
    family: 'core',
    dataShapes: ['flow', 'composition'],
    requires: ['stages'],
    optional: ['title', 'icon', 'iconColor', 'headline', 'sub', 'unit', 'suffix', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'A deal funnel or stage breakdown with volumes and optional metrics.',
  }),
  createMeta('kpi', {
    family: 'core',
    dataShapes: ['keyvalue'],
    requires: ['title', 'kpis'],
    optional: ['icon', 'iconColor', 'cols', 'footer', 'conf'],
    interactive: false,
    wowWeight: 0.4,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    blurb: 'A grid of labeled stat cards (facts, metrics, values).',
    propHints: {
      'kpis[].trend': "'up'|'down'|'flat'|'none'",
      'kpis[].status': "'good'|'warn'|'bad'|'neutral'",
    },
  }),
  createMeta('quotes', {
    family: 'core',
    dataShapes: ['text'],
    requires: ['quotes'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Customer testimonials or quotes with attribution and tone.',
  }),
  createMeta('checklist', {
    family: 'core',
    dataShapes: ['list', 'status'],
    requires: ['rows'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'A progress checklist with done/doing/todo items.',
  }),
  createMeta('understand', {
    family: 'core',
    dataShapes: ['text'],
    requires: ['items'],
    optional: ['title', 'conf', 'footer'],
    interactive: false,
    wowWeight: 0.45,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Cited learning points that users can correct, with confidence.',
  }),
  createMeta('schema', {
    family: 'core',
    dataShapes: ['hierarchy', 'relationship'],
    requires: ['entities'],
    optional: ['title', 'relations', 'footer'],
    interactive: false,
    wowWeight: 0.85,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'custom',
    blurb: 'An ER diagram showing entities, fields, and relationships.',
  }),
  createMeta('screenmap', {
    family: 'core',
    dataShapes: ['navigation'],
    requires: ['screens'],
    optional: ['title', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Wireframe thumbnails of generated screens (dashboard, table, detail, etc).',
  }),
  createMeta('buildprog', {
    family: 'core',
    dataShapes: ['flow', 'status'],
    requires: ['steps'],
    optional: ['title', 'footer'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Build or creation steps with status and explanatory subtitles.',
  }),
  createMeta('preview', {
    family: 'core',
    dataShapes: ['media', 'tabular'],
    requires: ['app', 'nav', 'stages', 'rows', 'kpis', 'columns'],
    optional: [
      'seededFrom',
      'groupColumns',
      'pipelineLabel',
      'agg',
      'createdNote',
      'activities',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.95,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'custom',
    blurb:
      'A live, clickable app the AI built\u2014shows dashboard, table, board, and activity views.',
  }),
];
