// Catalog entries for the `display` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_DISPLAY: ComponentCatalog = [
  // — display —
  createMeta('avatar', {
    family: 'display',
    dataShapes: ['media'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'name',
      'src',
      'glyph',
      'initials',
      'size',
      'status',
      'ring',
      'color',
      'role',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'User avatar with name, initials, or image; clickable to cycle size and presence status.',
    propHints: {
      status: "'online'|'away'|'busy'|'offline' (presence dot)",
      size: "'sm'|'md'|'lg'",
    },
  }),
  createMeta('avatargroup', {
    family: 'display',
    dataShapes: ['composition'],
    requires: ['title', 'members'],
    optional: ['icon', 'iconColor', 'max', 'size', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'members', text: 'name', textAliases: ['label', 'title'] }],
    blurb: 'Overlapping stack of avatars with +N overflow; hover to see all members.',
    propHints: {
      'members[].status': "'online'|'away'|'busy'|'offline'",
      size: "'sm'|'md'|'lg'",
    },
  }),
  createMeta('badgeset', {
    family: 'display',
    dataShapes: ['keyvalue', 'status'],
    requires: ['title', 'badges'],
    optional: ['icon', 'iconColor', 'countIcon', 'count', 'countColor', 'footer'],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'badges', text: 'label', textAliases: ['name', 'text', 'title'] }],
    blurb:
      'Short status/label badges in soft/outline/dot/solid variants with an optional count notification (statuses, tags, counts). Never for key→value facts — use deflist or kpi.',
    propHints: {
      'badges[].variant': "'solid'|'soft'|'outline'|'dot'",
    },
  }),
  createMeta('chipset', {
    family: 'display',
    dataShapes: ['selection'],
    requires: ['title', 'chips'],
    optional: ['icon', 'iconColor', 'mode', 'summary', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'chips', text: 'label', textAliases: ['name', 'text', 'title'] }],
    blurb: 'Selectable and removable tags with icons or avatars; single or multi-select.',
  }),
  createMeta('kbd', {
    family: 'display',
    dataShapes: ['list', 'navigation'],
    requires: ['title', 'shortcuts'],
    optional: ['icon', 'iconColor', 'active', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'shortcuts', text: 'label', textAliases: ['name', 'title', 'action'] }],
    blurb:
      'Actual KEYBOARD shortcuts shown as key-caps (⌘K, Ctrl+C) with hover highlight. Never for generic key→value facts or labels — use deflist or kpi.',
  }),
  createMeta('codeblock', {
    family: 'display',
    dataShapes: ['code', 'text'],
    requires: ['title', 'code'],
    optional: [
      'icon',
      'iconColor',
      'lang',
      'filename',
      'lines',
      'lineNumbers',
      'highlight',
      'runnable',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Real syntax-highlighted code. Put the raw source in `code` (one string, with real newlines) and the language in `lang` (e.g. "ts", "python", "rust") — we highlight it. Do NOT pre-tokenize or escape it.',
    propHints: {
      runnable:
        'true ONLY for a complete dependency-free JavaScript/TypeScript snippet that needs no imports, DOM/browser APIs, server globals, credentials, or omitted setup; otherwise omit (default false)',
    },
  }),
  createMeta('banner', {
    family: 'display',
    dataShapes: ['action', 'text'],
    requires: ['title', 'message'],
    optional: [
      'icon',
      'iconColor',
      'tone',
      'bannerIcon',
      'detail',
      'action',
      'dismissible',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Full-width banner alert or promo with tone, action button, and dismiss.',
    propHints: {
      tone: "'info'|'success'|'warning'|'promo' (also sets the default banner icon)",
    },
  }),
  createMeta('toaststack', {
    family: 'display',
    dataShapes: ['action', 'status'],
    requires: ['title', 'toasts'],
    optional: ['icon', 'iconColor', 'pool', 'duration', 'pushLabel', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 5,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'toasts', text: 'title', textAliases: ['label', 'name', 'heading'] }],
    blurb:
      'Stacked toast notifications with auto-dismiss and a push button to cycle through a pool.',
    propHints: {
      'toasts[].kind': "'success'|'error'|'info'|'warning'",
    },
  }),
  createMeta('spinner', {
    family: 'display',
    dataShapes: ['status'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'caption', 'buttonLabel', 'loadingLabel', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Animated spinners, indeterminate bar, and loading button; click to toggle state.',
  }),
  createMeta('notification', {
    family: 'display',
    dataShapes: ['list', 'action'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'markAllLabel', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [
      { prop: 'items', text: 'title', textAliases: ['label', 'name', 'heading', 'text'] },
    ],
    blurb:
      'Notification list with avatars, time-ago stamps, unread dots, and mark-all-read action.',
  }),
];
