// Catalog entries for the `docs` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_DOCS: ComponentCatalog = [
  createMeta('eligibilitycheck', {
    family: 'docs',
    dataShapes: ['status', 'list', 'comparison'],
    requires: ['title', 'requirements'],
    optional: ['icon', 'iconColor', 'overall', 'caveat', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Rules judged against MY situation: each requirement gets a met / not-met / needs-info verdict vs the user’s stated facts, the specific gap named and how to confirm it, then an honest "likely qualify / do not yet / depends" overall and a "verify with the official source" caveat. For "do I qualify for X" (grants, loans, programs, roles); a checklist only lists items to tick, this weighs each rule against real facts.',
    itemShapes: [
      {
        prop: 'requirements',
        text: 'rule',
        textAliases: ['requirement', 'criterion', 'label', 'text'],
      },
    ],
    propHints: {
      'requirements[].status':
        "'pass'|'fail'|'needs-info' — pass only when the stated facts clearly meet it, needs-info when a required fact is unknown",
      'requirements[].detail':
        'how this rule was judged against the situation, citing the stated fact',
      'requirements[].fix':
        'for a fail: what would make it qualify; for needs-info: how to confirm the missing fact',
      overall: "'likely'|'not-yet'|'depends' — use 'depends' whenever any rule is needs-info",
      caveat:
        'a "verify with the official source" reminder — this is guidance, not an official ruling',
    },
    intents: ['decide', 'reference', 'explain'],
  }),
  createMeta('evidencetrace', {
    family: 'docs',
    dataShapes: ['list', 'text'],
    requires: ['title', 'claim', 'items'],
    optional: ['icon', 'iconColor', 'summary', 'caveat', 'footer'],
    interactive: true,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'The raw records behind a claim or number — the headline claim up top, then the literal underlying data enumerated verbatim (real quotes/rows/tickets), each with its source and timing, plus an honest provenance line ("12 of 240 customers"). The "how do you KNOW that — show me" surface; renders only real given records, never invented ones. Pick over sourcelist (ranked links, not the data itself) or citationchain (a nested claim tree).',
    itemShapes: [{ prop: 'items', text: 'text', textAliases: ['quote', 'record', 'row', 'label'] }],
    propHints: {
      claim:
        'the one claim or number these records back, e.g. "Onboarding is the top churn driver"',
      summary:
        'short count/provenance of the records, e.g. "12 of 240 customers" or "from 18 support tickets"',
      'items[].source':
        'where the record came from, e.g. "ticket #4821" | "Survey Q3" | "ledger row 14"',
      caveat:
        'an honest limitation of this evidence, e.g. "self-reported; not a representative sample"',
    },
    intents: ['reference', 'explain', 'quantify'],
  }),
  createMeta('reviewsynth', {
    family: 'docs',
    dataShapes: ['composition', 'distribution', 'comparison'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'rating',
      'count',
      'distribution',
      'loves',
      'complaints',
      'dealbreaker',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 7,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'loves', text: 'theme', textAliases: ['label', 'name', 'title'] },
      { prop: 'complaints', text: 'theme', textAliases: ['label', 'name', 'title'] },
    ],
    blurb:
      'Distills MANY real customer reviews into an aggregate rating + 5→1 star distribution, then a what-people-love vs complaints split (each theme with rough frequency + one verbatim quote) and the single biggest dealbreaker. For "what do reviews say about X"; use worthit for one reviewer’s verdict, proscons for the model’s own ledger. Themes and quotes must come from real reviews only.',
    propHints: {
      distribution: 'star counts as [5★, 4★, 3★, 2★, 1★]',
      'loves[].freq': 'rough frequency across reviews, e.g. "62% mention" or "common"',
      'complaints[].freq': 'rough frequency across reviews, e.g. "1 in 4" or "occasional"',
      'loves[].quote': 'one verbatim quote from a real review',
      'complaints[].quote': 'one verbatim quote from a real review',
    },
    intents: ['decide', 'reference', 'compare'],
  }),
  // — docs —
  createMeta('annotateddoc', {
    family: 'docs',
    dataShapes: ['text'],
    requires: ['title', 'paragraphs', 'highlights'],
    optional: ['icon', 'iconColor', 'docName', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Prose with highlighted passages and margin notes (hover/click marks to reveal)',
    stringItems: ['paragraphs'],
  }),
  createMeta('redline', {
    family: 'docs',
    dataShapes: ['text'],
    requires: ['title', 'tokens'],
    optional: ['icon', 'iconColor', 'docName', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Tracked changes with tabs to view tracked/final/original copy',
  }),
  createMeta('citationchain', {
    family: 'docs',
    dataShapes: ['hierarchy'],
    requires: ['title', 'root'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Claim to source to evidence as an expandable tree with strength indicators',
    propHints: {
      'root.strength': "'strong'|'partial'|'weak'",
    },
  }),
  createMeta('factcheck', {
    family: 'docs',
    dataShapes: ['list'],
    requires: ['title', 'claims'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'claims', text: 'claim', textAliases: ['text', 'statement', 'label'] }],
    blurb: 'Claims with verdicts, confidence scores, and expandable sources/details',
    propHints: {
      'claims[].verdict': "'true'|'partly'|'false'|'unverified'",
    },
  }),
  createMeta('confidencemeter', {
    family: 'docs',
    dataShapes: ['composition'],
    requires: ['title', 'segments'],
    optional: ['icon', 'iconColor', 'claim', 'overall', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'segments', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Confidence breakdown by segments with hover tooltips on supporting basis',
    propHints: {
      'segments[].band': "'strong'|'partial'|'weak'|'none'",
    },
  }),
  createMeta('highlightsnippet', {
    family: 'docs',
    dataShapes: ['text'],
    requires: ['title', 'quote', 'phrase'],
    optional: ['icon', 'iconColor', 'source', 'locator', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Quoted source excerpt with highlighted phrase and toggle button',
  }),
  createMeta('annotcallouts', {
    family: 'docs',
    dataShapes: ['media'],
    requires: ['title', 'callouts'],
    optional: ['icon', 'iconColor', 'caption', 'ratio', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Numbered pins on a surface schematic (click pins to read callout notes)',
  }),
  createMeta('sourcelist', {
    family: 'docs',
    dataShapes: ['ranking'],
    requires: ['title', 'sources'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'sources', text: 'titleText', textAliases: ['title', 'label', 'name'] }],
    blurb: 'Ranked sources with relevance sorting and expandable snippets',
  }),
  createMeta('claimgrid', {
    family: 'docs',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'columns', 'rows'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Claims by evidence grid with check/cross/partial cells and hover tooltips',
    propHints: {
      'rows[].cells[].state': "'yes'|'no'|'partial'|'na'",
    },
    stringItems: ['columns'],
  }),
  createMeta('docoutline', {
    family: 'docs',
    dataShapes: ['hierarchy'],
    requires: ['title', 'sections'],
    optional: ['icon', 'iconColor', 'docName', 'activeIndex', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'cutting',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Collapsible document outline with section jumping and progress indicator',
  }),
  createMeta('docview', {
    family: 'docs',
    dataShapes: ['text', 'media'],
    requires: ['title', 'blocks'],
    optional: ['icon', 'iconColor', 'source', 'page', 'note', 'footer'],
    tier: 'frontier',
    wowWeight: 0.65,
    blurb:
      'PDF/page-style document viewer with in-document spotlight—focus one passage while the rest dims.',
    colDefault: 8,
    coercer: 'generic',
    propHints: {
      'blocks[].kind': "'h1'|'h2'|'p'|'caption'|'eq'",
    },
  }),
  createMeta('pdfreader', {
    family: 'docs',
    dataShapes: ['text', 'media'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'source', 'file', 'footer'],
    tier: 'frontier',
    wowWeight: 0.6,
    blurb: 'Scrollable multi-page PDF reader with live page counter—browse the full document.',
    colDefault: 12,
    coercer: 'generic',
    propHints: {
      'pages[].blocks[].kind': "'h1'|'h2'|'p'|'caption'|'eq'",
    },
  }),
  // — docs additions —
  createMeta('diffviewer', {
    family: 'docs',
    dataShapes: ['comparison', 'text'],
    requires: ['title', 'lines'],
    optional: ['icon', 'iconColor', 'leftLabel', 'rightLabel', 'split', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Side-by-side or inline diff view; added lines green, removed red, context grey.',
    itemShapes: [{ prop: 'lines', text: 'text', textAliases: ['content', 'line', 'code'] }],
    propHints: {
      'lines[].kind': "'add'|'del'|'ctx'",
    },
  }),
  // docs — health + legal
  createMeta('clinicaltimeline', {
    family: 'docs',
    dataShapes: ['sequence', 'status'],
    requires: ['title', 'events'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A health/medical event timeline — symptoms, diagnoses, treatments, tests, and results in chronological order. Use for patient history, care coordination, or health-journey asks.',
    itemShapes: [{ prop: 'events', text: 'label', textAliases: ['event', 'entry', 'note'] }],
    propHints: {
      'events[].type': '"symptom"|"diagnosis"|"treatment"|"test"|"result"|"visit"',
    },
  }),
  createMeta('researchsummary', {
    family: 'docs',
    dataShapes: ['text', 'list'],
    requires: ['title', 'question', 'findings', 'conclusion'],
    optional: [
      'icon',
      'iconColor',
      'method',
      'sampleSize',
      'limitations',
      'source',
      'year',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A structured research/study summary — question, method, key findings, conclusion, and limitations. Use for academic papers, scientific studies, clinical research, or any "what does the research say about X" ask.',
    propHints: {
      question: 'the core research question or hypothesis',
      method: 'study design, e.g. "randomized controlled trial", "meta-analysis"',
      sampleSize: 'e.g. "n = 1,200 adults"',
    },
    stringItems: ['findings'],
  }),
  createMeta('hypothesiscard', {
    family: 'docs',
    dataShapes: ['comparison', 'status'],
    requires: ['h0', 'h1'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'direction',
      'alpha',
      'variables',
      'rejected',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 7,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A formal null/alternative hypothesis statement (H0 vs H1) for a significance test, with an optional pass/fail verdict once the test has run. Use for statistics write-ups, A/B tests, or any "state the hypothesis" ask — distinct from researchsummary, whose `question` field is loose free text rather than formal H0/H1.',
    propHints: {
      h0: 'the null hypothesis, stated precisely, e.g. "There is no difference in mean recovery time between the two treatments."',
      h1: 'the alternative hypothesis, e.g. "Treatment B reduces mean recovery time versus Treatment A."',
      direction: '"two-tailed"|"greater"|"less"',
      alpha: 'the significance threshold the test was run against, e.g. 0.05',
      'variables.iv': 'the manipulated/predictor variable, e.g. "dosage (mg)"',
      'variables.dv': 'the measured/outcome variable, e.g. "systolic blood pressure"',
      rejected:
        'true once a test has actually run and rejected the null (evidence supports H1); false = failed to reject; omit while just stating the hypotheses',
    },
  }),
  createMeta('paralleltext', {
    family: 'docs',
    dataShapes: ['text', 'tabular'],
    requires: ['columns', 'rows'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 10,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Two or more texts aligned line-by-line in parallel columns (original vs translations), with per-line notes and divergence highlights',
    itemShapes: [
      { prop: 'columns', text: 'label', textAliases: ['name', 'title', 'heading'] },
      { prop: 'rows', text: 'note' },
    ],
    propHints: {
      'columns[].lang': "short language/script tag, e.g. 'la' | 'Old English' | 'fr'",
      'rows[].cells': 'one string per column, index-aligned to columns (column 0 = source)',
      'rows[].diverge':
        'true when the renderings meaningfully differ on this line (adds a subtle highlight)',
    },
    domains: ['language'],
    intents: ['reference', 'explain'],
  }),
  createMeta('resume', {
    family: 'docs',
    dataShapes: ['text', 'sequence'],
    requires: ['name', 'experience'],
    optional: ['title', 'icon', 'iconColor', 'contact', 'summary', 'education', 'skills', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A formatted CV — name/title letterhead, then Experience, Education, and Skills as labeled sections, most recent role first. Use for 'my resume', 'my CV', or 'my work history'; not for a single-job cover letter or a bio.",
    itemShapes: [
      { prop: 'experience', text: 'role', textAliases: ['title', 'position', 'jobTitle'] },
      { prop: 'education', text: 'school', textAliases: ['institution', 'university', 'college'] },
    ],
    propHints: {
      'experience[].start': 'e.g. "2019" or "Jan 2019"',
      'experience[].end': 'omit, or leave blank, for a current role — renders as "Present"',
      'education[].credential': 'e.g. "B.S. Computer Science" or "M.B.A."',
    },
    intents: ['draft', 'reference'],
    domains: ['career', 'business'],
    stringItems: ['contact', 'skills'],
  }),
  createMeta('changelog', {
    family: 'docs',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'versions'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "Versioned release notes — one section per version (version + date), each entry badge-tagged added/changed/fixed/removed/deprecated/security. Use for 'what changed in vX', a product's release history, or a changelog file; not for a single unversioned list of updates (use takeaways or a timeline instead).",
    itemShapes: [
      {
        prop: 'versions',
        text: 'version',
        textAliases: ['name', 'label', 'tag'],
        children: { prop: 'entries', text: 'text', textAliases: ['label', 'description', 'note'] },
      },
    ],
    propHints: {
      'versions[].version': 'e.g. "v2.4.0" — keep the same style across every version in the list',
      'entries[].kind': "'added'|'changed'|'fixed'|'removed'|'deprecated'|'security'",
    },
    intents: ['reference', 'track'],
    domains: ['code', 'tech', 'business'],
  }),
  createMeta('lessonplan', {
    family: 'docs',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'objectives', 'procedure'],
    optional: [
      'icon',
      'iconColor',
      'subject',
      'gradeLevel',
      'duration',
      'materials',
      'assessment',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A teacher's lesson plan — subject/grade/duration, learning Objectives, Materials, a numbered Procedure with per-step minute budgets, and an Assessment. Use for 'plan a lesson on X' or 'build a class for Y'; not for a student's own study schedule (use planner or timeline).",
    itemShapes: [{ prop: 'procedure', text: 'step', textAliases: ['title', 'label', 'activity'] }],
    propHints: {
      duration:
        'overall class length, e.g. "50 min" — derived from the procedure minutes if omitted',
      'procedure[].minutes': 'time budget for that step, in minutes — omit rather than guess',
    },
    intents: ['plan', 'teach', 'draft'],
    domains: ['education'],
    stringItems: ['objectives', 'materials'],
  }),
  createMeta('casebrief', {
    family: 'docs',
    dataShapes: ['text'],
    requires: ['title', 'parties', 'facts', 'issue', 'holding', 'reasoning'],
    optional: ['icon', 'iconColor', 'citation', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A legal case brief — Parties, Facts, Issue, Holding, and Reasoning as labeled sections, with the reporter citation as a caption under the title. Use for 'brief this case' or summarizing a court opinion; not for a contract review (use docview) or a general legal Q&A.",
    propHints: {
      citation: 'reporter citation, e.g. "410 U.S. 113 (1973)" — omit if unknown, never invent one',
      holding: "the court's actual ruling, stated as one plain sentence",
    },
    intents: ['reference', 'explain'],
    domains: ['legal', 'education'],
  }),
  createMeta('patentclaimchart', {
    family: 'docs',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'claimElements', 'references', 'cells'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.76,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      "A patent claim chart — the claim's own numbered elements down the rows, prior art or an accused product across the columns, each intersection marked disclosed / not-disclosed / disputed with the supporting quote on hover. Use for patent infringement/invalidity analysis or licensing diligence; not for a general claims-vs-evidence grid (use claimgrid).",
    itemShapes: [
      {
        prop: 'claimElements',
        text: 'text',
        textAliases: ['label', 'claim', 'limitation', 'description'],
      },
    ],
    propHints: {
      'claimElements[].id':
        'the claim\'s own element number/letter, e.g. "1.1" or "[a]" — omit only if truly unnumbered',
      'cells[][].state':
        "'disclosed'|'not-disclosed'|'disputed', one verdict per element × reference pairing (cells[elementIndex][referenceIndex])",
      'cells[][].quote':
        'the supporting passage from that reference — omit for not-disclosed cells, never invent one',
    },
    intents: ['analyze', 'reference'],
    domains: ['legal'],
    stringItems: ['references'],
  }),
  createMeta('storystructure', {
    family: 'docs',
    dataShapes: ['text', 'sequence'],
    requires: ['title', 'lede', 'nutGraf', 'body'],
    optional: ['icon', 'iconColor', 'background', 'wordCountBudget', 'wordCount', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A journalism inverted-pyramid draft — the lede and nut graf called out in a highlighted block up top, body paragraphs in reading order below, and secondary background held behind a collapsible toggle. Use for 'draft this as a news story' or 'write it inverted-pyramid style'; not for a general article/blog draft (use pullquote, casestudy, or plain prose).",
    propHints: {
      lede: 'the opening sentence — the single most newsworthy fact, stated first, not buried',
      nutGraf: 'the paragraph right after the lede supplying the essential who/what/why/so-what',
      wordCount: "the draft's actual word count — derived from lede+nutGraf+body if omitted",
    },
    intents: ['draft', 'organize'],
    domains: ['writing', 'media'],
    stringItems: ['body', 'background'],
  }),
  createMeta('vetpatientchart', {
    family: 'docs',
    dataShapes: ['keyvalue', 'status'],
    requires: ['title', 'species', 'name'],
    optional: [
      'icon',
      'iconColor',
      'breed',
      'sex',
      'ageYears',
      'weightKg',
      'vitals',
      'problems',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 7,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A veterinary patient chart — the signalment (species/breed/sex/age/weight) as identity chips atop a vitals strip and the active problem list. Use for 'my dog's checkup', 'vet visit summary', or any single-visit animal chart; not for a treatment history over time (use clinicaltimeline).",
    itemShapes: [{ prop: 'vitals', text: 'label', textAliases: ['name', 'vital', 'metric'] }],
    propHints: {
      'vitals[].value':
        'most readings are numeric ("101.5"); a few are qualitative ("Pink", "CRT <2s") — give whichever the real reading is',
      'vitals[].abnormal':
        'true only when the reading is genuinely outside normal for this patient — never guess',
    },
    intents: ['reference', 'track'],
    domains: ['health'],
    stringItems: ['problems'],
  }),
  createMeta('scoutingreport', {
    family: 'docs',
    dataShapes: ['list', 'text'],
    requires: ['title', 'opponent', 'tendencies'],
    optional: ['icon', 'iconColor', 'matchupNotes', 'keyPlayers', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A sports opponent scouting report — the opponent's tendencies as a prose list, per-matchup notes, and the key players to game-plan around. Use for 'scout our next opponent' or pre-game prep; not for a live in-game recap (use scoreboard, statustimeline, or a gameday-style narrative).",
    itemShapes: [
      { prop: 'matchupNotes', text: 'note', textAliases: ['detail', 'text', 'description'] },
      { prop: 'keyPlayers', text: 'name', textAliases: ['player', 'who'] },
    ],
    propHints: {
      'matchupNotes[].label':
        'the matchup dimension this note covers, e.g. "Pace", "3-point defense"',
      'keyPlayers[].role': 'position/role, e.g. "PG", "closer", "left tackle"',
    },
    intents: ['analyze', 'plan'],
    domains: ['sports'],
    stringItems: ['tendencies'],
  }),
];
