// Catalog entries for the `everyday` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_EVERYDAY: ComponentCatalog = [
  createMeta('allocatepeople', {
    family: 'everyday',
    dataShapes: ['composition', 'list', 'comparison'],
    requires: ['title', 'people', 'assignments'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Split tasks or chores fairly among NAMED people — one column per person with their tasks and a load bar that makes an uneven split obvious. Use for "divide the chores between us", roommate rotas, group-project work, or on-call duty.',
    itemShapes: [
      { prop: 'assignments', text: 'task', textAliases: ['chore', 'duty', 'job', 'item', 'label'] },
    ],
    propHints: {
      people: 'array of person names, e.g. ["Sam", "Alex", "Jordan"]',
      'assignments[].who': 'a person — should match one of the `people` names',
      'assignments[].weight':
        'effort this task carries, 1 (light) to 5 (heavy); optional, defaults to 1',
    },
    intents: ['plan', 'decide', 'compare'],
    stringItems: ['people'],
  }),
  // ── everyday family ─────────────────────────────────────────────────────────
  createMeta('forecast', {
    family: 'everyday',
    dataShapes: ['series', 'list'],
    requires: ['title', 'days'],
    optional: ['icon', 'iconColor', 'location', 'unit', 'asOf', 'summary', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A multi-day weather or prediction grid — icon, hi/lo, condition, precipitation per day — with location and timestamp.',
    itemShapes: [
      { prop: 'days', text: 'condition', textAliases: ['weather', 'forecast', 'summary', 'label'] },
    ],
    propHints: {
      unit: "'F'|'C'",
      'days[].icon': "'sun'|'cloud'|'rain'|'snow'|'storm'|'fog'|'partly-cloudy'",
    },
  }),
  createMeta('agenda', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'date', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'base',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A schedule, itinerary, or meeting agenda — time-ordered items with locations, durations, and notes.',
    itemShapes: [{ prop: 'items', text: 'title', textAliases: ['name', 'label', 'task', 'event'] }],
    propHints: {
      'items[].time': '"9:00 AM" | "14:30" — start time for this item',
      'items[].duration': '"45 min" | "2 hours" — how long the item lasts',
      'items[].location': '"Museum of Fine Arts" — place name or address',
      'items[].note': '"Book tickets in advance" — tip, note, or detail',
      'items[].done': 'true|false',
    },
  }),
  createMeta('picks', {
    family: 'everyday',
    dataShapes: ['list', 'ranking'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'category', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'base',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A curated ranked recommendation list — products, books, places — each with tagline, reasoning, price, rating, and a badge.',
    itemShapes: [{ prop: 'items', text: 'name', textAliases: ['title', 'label', 'product'] }],
  }),
  createMeta('timezones', {
    family: 'everyday',
    dataShapes: ['comparison', 'list'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'baseTime', 'footer'],
    interactive: false,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'World-clock comparison — cities, UTC offsets, and local times shown side-by-side; home timezone highlighted.',
    itemShapes: [{ prop: 'rows', text: 'city', textAliases: ['name', 'label', 'location'] }],
  }),
  createMeta('transitroute', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'origin', 'destination', 'steps'],
    optional: ['icon', 'iconColor', 'totalTime', 'totalDistance', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A turn-by-turn transit or driving route — mode icons, instructions, line names, and a total time summary.',
    itemShapes: [
      { prop: 'steps', text: 'instruction', textAliases: ['description', 'text', 'step'] },
    ],
    propHints: {
      'steps[].mode': "'walk'|'bus'|'subway'|'train'|'bike'|'car'|'ferry'",
    },
  }),
  createMeta('amortization', {
    family: 'everyday',
    dataShapes: ['tabular', 'list'],
    requires: ['title', 'principal', 'rate', 'term', 'monthlyPayment', 'rows'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A loan or mortgage amortization table — per-period principal/interest split with a running balance that pays DOWN to zero. Never for a generic financial table or budget — use datatable.',
    itemShapes: [{ prop: 'rows', text: 'period', textAliases: ['label', 'month', 'year'] }],
  }),
  createMeta('receipt', {
    family: 'everyday',
    dataShapes: ['tabular', 'list'],
    requires: ['title', 'lines', 'total'],
    optional: ['icon', 'iconColor', 'merchant', 'date', 'subtotal', 'tax', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'An itemized PURCHASE receipt — money only: line items with quantity and price, subtotal, tax, and a currency grand total. Never for workouts, schedules, or generic item lists with non-money "totals" (use workoutplan for exercises, agenda for plans, checklist/datatable otherwise).',
    itemShapes: [{ prop: 'lines', text: 'item', textAliases: ['name', 'description', 'label'] }],
  }),
  createMeta('settleup', {
    family: 'everyday',
    dataShapes: ['list', 'comparison'],
    requires: ['title', 'settlements'],
    optional: ['icon', 'iconColor', 'people', 'expenses', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Group expense split — who paid what, who owes who, and the minimum transfers to settle up.',
    itemShapes: [{ prop: 'settlements', text: 'from', textAliases: ['payer', 'name'] }],
    stringItems: ['people'],
  }),
  createMeta('bracketbar', {
    family: 'everyday',
    dataShapes: ['ranking', 'comparison'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'metric', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Numbered leaderboard bars — top-N ranked items each with a score and optional badge. Use for "rank the top N …", best/worst lists, poll results, popularity rankings.',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title'] }],
  }),
  // everyday — cooking / fitness / health / nutrition
  createMeta('recipecard', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'ingredients', 'steps'],
    optional: [
      'icon',
      'iconColor',
      'servings',
      'prepTime',
      'cookTime',
      'difficulty',
      'tips',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A cooking recipe card — ingredients with quantities, numbered steps, and pro tips. Use for any "how do I make X" or "recipe for Y" ask.',
    itemShapes: [{ prop: 'ingredients', text: 'name', textAliases: ['ingredient', 'item'] }],
    propHints: {
      difficulty: '"easy"|"medium"|"hard"',
      'ingredients[].qty': 'amount, e.g. "2", "¼ cup", "a pinch"',
    },
    stringItems: ['steps', 'tips'],
  }),
  createMeta('workoutplan', {
    family: 'everyday',
    dataShapes: ['sequence', 'tabular'],
    requires: ['title', 'sessions'],
    optional: ['icon', 'iconColor', 'goal', 'weeks', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A structured workout plan with sessions, exercises, sets, reps, and rest periods. Use for any "gym plan", "workout routine", or "training program" ask.',
    propHints: {
      'sessions[].exercises[].reps': '"10–12"|"to failure"|"30 sec"',
      'sessions[].exercises[].rest': '"60 sec"|"90 sec"|"2 min"',
    },
  }),
  createMeta('medicationschedule', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'medications'],
    optional: ['icon', 'iconColor', 'startDate', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A medication schedule — drug names, doses, dosing times, and instructions. Use for medication tracking, prescription management, or post-surgery care asks.',
    itemShapes: [{ prop: 'medications', text: 'name', textAliases: ['drug', 'medication', 'med'] }],
    propHints: {
      'medications[].times': 'array of time strings, e.g. ["8:00 AM", "8:00 PM"]',
      'medications[].withFood': 'true if the medication must be taken with food',
    },
  }),
  createMeta('macrobreakdown', {
    family: 'everyday',
    dataShapes: ['composition', 'scalar'],
    requires: ['title', 'calories', 'protein', 'carbs', 'fat'],
    optional: ['icon', 'iconColor', 'fiber', 'items', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Nutritional macros — calorie headline, protein/carbs/fat/fiber split with a stacked bar, and optional per-item breakdown. Use for any nutrition, diet, or food content ask.',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['food', 'name', 'ingredient'] }],
  }),
  createMeta('plangrid', {
    family: 'everyday',
    dataShapes: ['sequence', 'tabular', 'keyvalue'],
    requires: ['title', 'columns', 'rows'],
    optional: ['icon', 'iconColor', 'summary', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A forward days×slots planning grid — meal plan, study schedule, habit tracker, weekly routine. One cell per slot per column; free slots show empty. Distinct from agenda (one day) and calheat (past streaks).',
    itemShapes: [
      {
        prop: 'rows',
        text: 'slot',
        textAliases: ['label', 'name', 'row'],
        children: { prop: 'cells', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    propHints: {
      columns:
        'the grid columns, e.g. ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] or ["Week 1","Week 2"]',
      'rows[].cells[].col':
        'must match one of the `columns` strings (case-insensitive); omit a column for a free slot',
      'rows[].cells[].accent': "'var(--presence)'|'var(--insight)'|'var(--warning)'",
    },
    intents: ['plan', 'track', 'organize'],
    domains: ['cooking', 'fitness', 'education', 'productivity', 'travel'],
    stringItems: ['columns', 'summary'],
  }),
  createMeta('budgetallocator', {
    family: 'everyday',
    dataShapes: ['composition', 'scalar'],
    requires: ['title', 'income', 'envelopes'],
    optional: ['icon', 'iconColor', 'unit', 'incomeLabel', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A forward envelope / zero-based budget — income at the top, category bars, and a live "left to allocate" (or "over by") meter. Use to BUILD a budget or allocate a pot; for splitting a PAST total use breakdown/donut.',
    itemShapes: [{ prop: 'envelopes', text: 'label', textAliases: ['name', 'category'] }],
    propHints: {
      income: 'the total pot to allocate, a number (e.g. 4200)',
      'envelopes[].amount': 'amount assigned, a number in the same unit as income',
      'envelopes[].group': "'fixed'|'flexible'|'savings'",
      'envelopes[].accent': "'var(--presence)'|'var(--insight)'|'var(--warning)'",
      unit: "currency prefix, e.g. '$' (default), '£', '€'",
    },
    intents: ['plan', 'decide', 'organize', 'track'],
    domains: ['money', 'business', 'productivity'],
  }),
  createMeta('howtosteps', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'time', 'difficulty', 'warning', 'tools', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A hands-on how-to / procedure — prep meta (time, difficulty), an optional safety warning, the tools needed, then numbered steps each with detail, a caution, a tip, and a "done when" check. For physical/practical how-tos (repairs, setup, DIY); use recipecard for cooking, processflow for abstract flows.',
    itemShapes: [
      { prop: 'steps', text: 'action', textAliases: ['step', 'instruction', 'text', 'title'] },
    ],
    propHints: {
      difficulty: "'easy'|'medium'|'hard'",
      warning:
        'a one-line safety warning shown prominently at the top, e.g. "Switch off the power first"',
      tools: 'array of tools/materials needed, e.g. ["Phillips screwdriver","plunger","bucket"]',
    },
    intents: ['howto', 'explain', 'plan'],
    domains: ['home', 'tech', 'fitness', 'productivity'],
    stringItems: ['tools'],
  }),
  createMeta('livecompute', {
    family: 'everyday',
    dataShapes: ['scalar', 'relationship'],
    requires: ['title', 'inputs', 'formula', 'output'],
    optional: ['icon', 'iconColor', 'caveat', 'footer'],
    interactive: true,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A stateful what-if: drag the levers and one honest projected number updates live, from a transparent arithmetic formula over the inputs. For "what would my mortgage be", "how long does runway last", "calories for my goal". Real values only — it recomputes what you set, never invents data.',
    itemShapes: [{ prop: 'inputs', text: 'label', textAliases: ['name', 'lever'] }],
    propHints: {
      'inputs[].key': 'short variable name (letters/digits/_) used verbatim in the formula',
      formula:
        'arithmetic over the input keys using + - * / ^ and ( ) only — e.g. "principal * (rate/1200) / (1 - (1 + rate/1200)^(-years*12))". No function calls.',
      'output.decimals': 'decimal places for the result (default 0)',
    },
    intents: ['decide', 'quantify', 'plan'],
  }),
  createMeta('countdown', {
    family: 'everyday',
    dataShapes: ['scalar', 'status'],
    requires: ['title', 'target'],
    optional: ['icon', 'iconColor', 'label', 'dueWhat', 'consequence', 'footer'],
    interactive: true,
    wowWeight: 0.64,
    tier: 'frontier',
    colDefault: 5,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A live ticking countdown to a real deadline — days/hours/minutes/seconds remaining, what is due, and the consequence of missing it. Only use with a real, known date.',
    propHints: {
      target:
        'the real date/time the countdown runs to, ISO preferred, e.g. "2026-09-01T17:00:00" or "2026-09-01"',
    },
    intents: ['plan', 'track'],
  }),
  createMeta('livescore', {
    family: 'everyday',
    dataShapes: ['ranking'],
    requires: ['title', 'entries'],
    optional: ['icon', 'iconColor', 'unit', 'step', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'frontier',
    colDefault: 5,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'An interactive scorekeeper — tap +/- on each side and the ranking recomputes live, leader highlighted. For game night, classroom points, or trivia; the user drives it, nothing is invented.',
    itemShapes: [{ prop: 'entries', text: 'name', textAliases: ['player', 'team', 'label'] }],
    propHints: {
      'entries[].score': 'starting score as a number (0 to begin)',
      step: 'points added or removed per tap (default 1)',
    },
    intents: ['track'],
  }),
  createMeta('nutritionlabel', {
    family: 'everyday',
    dataShapes: ['composition', 'tabular', 'keyvalue'],
    requires: ['servingSize', 'calories', 'nutrients'],
    optional: ['title', 'icon', 'iconColor', 'servings', 'allergens', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 5,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A faithful FDA-style Nutrition Facts panel — the boxed label with serving size, a big Calories number, nutrient rows with a right-aligned %DV column (major nutrients bold, sub-nutrients indented), and an allergen line. For reading or showing a food label; for a macro split use macrobreakdown.',
    itemShapes: [{ prop: 'nutrients', text: 'name', textAliases: ['nutrient', 'label'] }],
    propHints: {
      servingSize: 'the serving size as printed, e.g. "1 cup (55g)"',
      'nutrients[].amount': 'the printed amount, e.g. "8g", "230mg"',
      'nutrients[].dv':
        'percent Daily Value as a number (0–100+); omit where the label prints none',
      'nutrients[].indent': 'true for a sub-nutrient (Saturated Fat under Total Fat)',
      'nutrients[].bold': 'true for a major nutrient line printed in bold',
      allergens: 'array of allergens, e.g. ["wheat", "milk", "soy"]',
    },
    intents: ['reference', 'explain'],
    domains: ['cooking', 'health'],
    stringItems: ['allergens'],
  }),
  createMeta('unitconvert', {
    family: 'everyday',
    dataShapes: ['keyvalue', 'scalar'],
    requires: ['quantity', 'from', 'equivalents'],
    optional: ['title', 'icon', 'iconColor', 'category', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'base',
    colDefault: 4,
    colMin: 3,
    coercer: 'generic',
    blurb:
      'A measurement-conversion panel — a from-amount shown prominently, then aligned "= value unit" equivalent rows (1 cup = 240 ml = 16 tbsp), tagged by category (volume / weight / length / temperature). For "how many X in a Y" or "convert A to B" asks.',
    itemShapes: [{ prop: 'equivalents', text: 'unit', textAliases: ['name', 'label'] }],
    propHints: {
      quantity: 'the from-amount as a number, e.g. 1',
      from: 'the from-unit, e.g. "cup"',
      'equivalents[].value': 'the equivalent amount as a string, e.g. "240", "16"',
      category: "'volume'|'weight'|'length'|'temperature'",
    },
    intents: ['quantify', 'reference'],
    domains: ['cooking', 'home'],
  }),
  createMeta('packlist', {
    family: 'everyday',
    dataShapes: ['list', 'status', 'composition'],
    requires: ['groups'],
    optional: ['title', 'icon', 'iconColor', 'context', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A category-grouped packing checklist — sections (Clothes, Toiletries, Tech) of counted items with a packed-vs-total meter per group and overall, headed by the trip context (duration, weather). For "what to pack for X" asks.',
    itemShapes: [
      {
        prop: 'groups',
        text: 'name',
        textAliases: ['category', 'label'],
        children: { prop: 'items', text: 'label', textAliases: ['name', 'item', 'text'] },
      },
    ],
    propHints: {
      context: 'trip context header, e.g. "3 days · mild, light rain"',
      'groups[].items[].count': 'how many to bring as a number, e.g. 3',
      'groups[].items[].packed': 'true once the item is packed (drives the meters)',
    },
    intents: ['plan', 'reference'],
    domains: ['travel', 'home'],
  }),
  createMeta('pregnancyweek', {
    family: 'everyday',
    dataShapes: ['status', 'scalar', 'list'],
    requires: ['week'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'trimester',
      'fruitSize',
      'lengthCm',
      'weightG',
      'milestones',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A week-by-week pregnancy card — the gestational week with a trimester progress bar (week/40), a to-scale fruit-size comparison, the baby\'s length/weight, and milestone bullets. For "what\'s happening at N weeks" / "how big is the baby now" asks.',
    propHints: {
      week: 'gestational week as a number, 1–40',
      trimester: '1|2|3 (derived from the week when omitted)',
      fruitSize: 'the size comparison, e.g. "banana", "pomegranate"',
      lengthCm: 'length in cm as a number',
      weightG: 'estimated weight in grams as a number',
    },
    intents: ['explain', 'track', 'reference'],
    domains: ['health'],
    stringItems: ['milestones'],
  }),
  createMeta('cycletrack', {
    family: 'everyday',
    dataShapes: ['sequence', 'status', 'series'],
    requires: ['cycleLength', 'periodDays'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'currentDay',
      'fertileWindow',
      'ovulationDay',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A menstrual / fertility calendar band — one cell per cycle day, shading the period days, the fertile window, the ovulation day, and a "today" marker, all positioned by day number against the cycle length. For cycle-tracking, fertility-window, or period-calendar asks.',
    propHints: {
      cycleLength: 'total days in the cycle as a number, e.g. 28',
      periodDays: 'number of period days from day 1, e.g. 5',
      currentDay: "today's day-of-cycle (1-based) as a number",
      fertileWindow: 'two day numbers [start, end], e.g. [11, 16]',
      ovulationDay: 'the estimated ovulation day number, e.g. 14',
    },
    intents: ['track', 'explain'],
    domains: ['health'],
  }),
  createMeta('contractiontimer', {
    family: 'everyday',
    dataShapes: ['series', 'sequence', 'status'],
    requires: ['contractions'],
    optional: ['title', 'icon', 'iconColor', 'rule', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A labor-contraction interval strip — a DISPLAY of logged contractions (not a live timer): each is a bar sized by its duration and spaced by its interval, with avg duration / frequency read-outs and a "time to go in" rule hint (e.g. 5-1-1). For tracking or reviewing contraction timing.',
    itemShapes: [{ prop: 'contractions', text: 'start', textAliases: ['time', 'label'] }],
    propHints: {
      'contractions[].start': 'wall-clock start of the contraction, e.g. "2:14 PM"',
      'contractions[].durationSec': 'how long the contraction lasted, in seconds',
      'contractions[].intervalMin':
        'minutes from the start of this contraction to the start of the next',
      rule: "the go-in rule of thumb, e.g. '5-1-1'",
    },
    intents: ['track', 'reference'],
    domains: ['health'],
  }),
  createMeta('prayertimes', {
    family: 'everyday',
    dataShapes: ['sequence', 'status'],
    requires: ['slots'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'date',
      'location',
      'next',
      'sunArc',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 5,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A daily devotional-times card — the named time slots (five salah, sunrise/sunset, liturgical hours, candle-lighting) plotted along a dawn-to-dusk sun arc, each positioned by its clock time, with the next one highlighted and read out countdown-style. For prayer-times, salah-schedule, sunrise/sunset, or daily-liturgy asks.',
    itemShapes: [
      {
        prop: 'slots',
        text: 'name',
        textAliases: ['label', 'prayer', 'slot'],
        requiredFields: ['time'],
      },
    ],
    propHints: {
      slots:
        'the named times in order, each { name, time } — time a clock string like "5:42 AM" or "17:03"',
      next: "the name of the upcoming slot to highlight, must match one slot's name",
      sunArc: 'true to draw the dawn-to-dusk sun-arc strip (default), false for a plain time list',
    },
    intents: ['reference', 'track'],
    domains: ['nature', 'home'],
  }),
  createMeta('labprotocol', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'reagents', 'equipment', 'cycles', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A lab-bench procedure/SOP — hazard-tagged reagents and equipment beside numbered steps, ' +
      'each with an optional duration/temperature condition and an inline caution. General enough ' +
      'for a chemistry synthesis prep or a molecular-biology protocol (PCR, Western blot); an ' +
      'optional `cycles` group renders a bracketed "repeat ×N" block for thermal-cycling steps. ' +
      'Use for "protocol for X", "PCR steps", "synthesis procedure", "SOP for Y". For cooking use ' +
      'recipecard instead.',
    itemShapes: [
      { prop: 'reagents', text: 'name', textAliases: ['reagent', 'chemical'] },
      { prop: 'steps', text: 'text', textAliases: ['step', 'instruction', 'description'] },
    ],
    propHints: {
      'reagents[].hazard': "'flammable'|'corrosive'|'toxic'|'oxidizer'|'irritant'",
      'reagents[].amount': 'e.g. "50 mL", "2.5 µL", "10 g"',
      'reagents[].conc': 'e.g. "1 M", "10x buffer", "0.1% w/v"',
      'steps[].duration': 'e.g. "5 min", "30 sec"',
      'steps[].temp': 'e.g. "95°C", "4°C", "room temp"',
      'steps[].caution': 'a short safety note specific to this step, shown in warning tone',
      cycles:
        'a repeated sub-procedure, e.g. PCR thermal cycling: { repeat: 30, steps: [{ text, duration, temp }] }',
    },
    intents: ['howto', 'reference'],
    domains: ['science', 'health'],
    stringItems: ['equipment'],
  }),
  createMeta('caregivercoord', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'personName', 'relation'],
    optional: ['icon', 'iconColor', 'medications', 'appointments', 'contacts', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An eldercare / multi-person care-team coordination card — a named person\'s medications (with who administers each), appointments, and care-team contacts. The COORDINATOR\'s view, not the patient\'s own dosing view (use medicationschedule for that). Use for "coordinate mom\'s care", "who\'s handling dad\'s appointments", "caregiver schedule for X".',
    itemShapes: [
      { prop: 'medications', text: 'name', textAliases: ['medication', 'drug', 'med'] },
      { prop: 'appointments', text: 'purpose', textAliases: ['reason', 'title', 'type'] },
      { prop: 'contacts', text: 'name', textAliases: ['contact'] },
    ],
    propHints: {
      relation: 'the caregiver\'s relation to the person, e.g. "Mom", "Dad", "Grandmother"',
      'medications[].times': 'array of dosing time strings, e.g. ["8:00 AM", "6:00 PM"]',
      'medications[].takenBy': 'who administers/checks the dose, e.g. "Home aide", "Priya"',
      'appointments[].date': 'e.g. "Jun 20, 2026", "Thu 2pm"',
      'appointments[].provider': 'e.g. "Dr. Alvarez", "Maple Physical Therapy"',
      'contacts[].role': 'e.g. "Home aide", "Primary care physician", "Son (backup)"',
    },
    intents: ['plan', 'track', 'organize'],
    domains: ['health', 'home'],
  }),
  createMeta('readinglist', {
    family: 'everyday',
    dataShapes: ['list', 'status'],
    requires: ['title', 'books'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A book-club or personal reading tracker — a cover swatch, author, and status (reading/queued/done) per book, an optional star rating, and expandable book-club discussion questions. Use for "my reading list", "book club picks", "what am I reading".',
    itemShapes: [{ prop: 'books', text: 'title', textAliases: ['name', 'book'] }],
    propHints: {
      'books[].status': "'reading'|'queued'|'done'",
      'books[].rating': 'a number 0–5, halves allowed (e.g. 4.5)',
      'books[].discussionQuestions': 'array of open-ended discussion question strings',
    },
    intents: ['track', 'reference'],
    domains: ['home'],
  }),
  createMeta('cocktailcard', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'pours'],
    optional: ['icon', 'iconColor', 'notes', 'rating', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A drink recipe / tasting card — a numbered pour list (the order IS the build steps) closed by flavor notes (aroma/taste/finish) and a star rating. recipecard\'s sibling for cocktails and other mixed drinks; use recipecard for food. Use for "recipe for a negroni", "how do I make an old fashioned".',
    itemShapes: [{ prop: 'pours', text: 'item', textAliases: ['ingredient', 'name'] }],
    propHints: {
      rating: 'a number 0–5, halves allowed (e.g. 4.5)',
      'pours[].qty': 'e.g. "1.5 oz", "a dash", "1"',
    },
    intents: ['howto', 'reference'],
    domains: ['cooking', 'home'],
  }),
  createMeta('runninglog', {
    family: 'everyday',
    dataShapes: ['series', 'sequence', 'list'],
    requires: ['title', 'entries'],
    optional: ['icon', 'iconColor', 'unit', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A running/cycling training log — a dated entry list (distance, pace, route, elevation) plus a distance/pace trend chart built from those same entries. Distinct from workoutplan (gym sessions of sets/reps). Use for "log of my runs", "how\'s my training going", "my cycling mileage".',
    itemShapes: [{ prop: 'entries', text: 'date', textAliases: ['day', 'when'] }],
    propHints: {
      unit: "'mi'|'km' (default 'mi')",
      'entries[].pace': '"8:32" min:sec per unit — only this exact mm:ss shape is charted',
      'entries[].elevationGainM': 'a number in meters',
    },
    intents: ['track', 'quantify'],
    domains: ['fitness'],
  }),
  createMeta('userpersona', {
    family: 'everyday',
    dataShapes: ['list', 'text'],
    requires: ['title', 'name', 'goals', 'frustrations'],
    optional: ['icon', 'iconColor', 'role', 'quote', 'behaviors', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A UX research persona card — an initials portrait and role header, goals (insight tint) and frustrations (warning tint) as two bullet columns, an italic pull-quote, and optional observed behaviors. Use for "build a persona for X", "who are we designing for", "UX research summary".',
    propHints: {
      role: 'a short role/descriptor line, e.g. "Integrating partner engineer", "Busy parent, 34"',
      quote: 'a short first-person line that captures their attitude, shown as a pull-quote',
    },
    intents: ['explain', 'reference'],
    domains: ['business', 'productivity'],
    stringItems: ['goals', 'frustrations', 'behaviors'],
  }),
  createMeta('runofshow', {
    family: 'everyday',
    dataShapes: ['sequence', 'status'],
    requires: ['title', 'cues'],
    optional: ['icon', 'iconColor', 'eventDate', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An event-production timeline / cue sheet — a vertical cue list with the live cue pinned and glowing, each tagged with an initials chip for its owner. Use for "run of show for the shoot", "cue sheet for the show", "production timeline for the launch event".',
    itemShapes: [{ prop: 'cues', text: 'cue', textAliases: ['title', 'action', 'description'] }],
    propHints: {
      'cues[].state': "'done'|'live'|'next'|'pending'",
      'cues[].owner': "a person's name — shown as an initials chip",
    },
    intents: ['plan', 'track'],
    domains: ['business', 'creative'],
  }),
  createMeta('podcastplanner', {
    family: 'everyday',
    dataShapes: ['sequence', 'list'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'guest', 'topics', 'chapters', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'An episode-planning card — a guest header atop a numbered topic outline, each topic tagged with its chapter timecode when one lines up. Use for "plan next week\'s episode", "outline for the podcast", "episode with X".',
    propHints: {
      chapters:
        'array of { timecode, label } paired to `topics` BY POSITION (chapters[i] tags topics[i]) — omit an index rather than guess a timecode',
    },
    intents: ['plan', 'draft'],
    domains: ['creative', 'business'],
    stringItems: ['topics'],
  }),
  createMeta('vaxschedule', {
    family: 'everyday',
    dataShapes: ['sequence', 'status'],
    requires: ['title', 'doses'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A vaccination schedule, generalized for a pet OR a person — dose chips plotted along a horizontal age/date axis by due date, colored by status (done/due/overdue). Use for "vaccine schedule for X", "when\'s the next booster due", "puppy shot schedule".',
    itemShapes: [{ prop: 'doses', text: 'vaccine', textAliases: ['name', 'shot'] }],
    propHints: {
      'doses[].dueAt':
        'a real date ("2026-08-01") OR a relative age ("8 weeks", "6 months") — keep one style across the whole list',
      'doses[].status': "'done'|'due'|'overdue'",
    },
    intents: ['track', 'reference'],
    domains: ['health'],
  }),
  createMeta('claimagecompare', {
    family: 'everyday',
    dataShapes: ['comparison', 'series', 'scalar'],
    requires: ['title', 'ages'],
    optional: ['icon', 'iconColor', 'breakeven', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'The Social Security claim-age tradeoff — KPI chips for each claiming age (62/67/70) and a cumulative-payout line chart computed from the given monthly benefit at each age, with an optional marked breakeven point. Use for "when should I claim Social Security", "62 vs 67 vs 70", "claim-age tradeoff".',
    propHints: {
      'ages[].age': '62|67|70 — exactly one of these three',
      'ages[].monthlyBenefit': 'the monthly dollar amount at that claiming age, a number',
      breakeven: 'only include this if you can name a specific crossover age — never guessed',
    },
    intents: ['decide', 'quantify', 'plan'],
    domains: ['money'],
  }),
  // ── everyday coverage batch — weathernow / tierlist / paystub / taxbracket / menucard /
  //    familytree / seatingchart / relationshipmap / meetingnotes / stickerchart ──────────────
  createMeta('weathernow', {
    family: 'everyday',
    dataShapes: ['scalar', 'keyvalue'],
    requires: ['title', 'tempF', 'condition', 'asOf'],
    optional: [
      'icon',
      'iconColor',
      'location',
      'feelsLikeF',
      'hi',
      'lo',
      'hourly',
      'tiles',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Present-moment weather — big current reading, an hourly scroll strip, and small stat tiles (UV, air quality, wind). Distinct from forecast (a multi-day grid); always give a real asOf timestamp.',
    itemShapes: [
      { prop: 'hourly', text: 'time' },
      { prop: 'tiles', text: 'label', textAliases: ['name'] },
    ],
    propHints: {
      'hourly[].icon': "'sun'|'cloud'|'rain'|'snow'|'storm'|'wind'",
      'hourly[].precipPct': 'chance of precipitation, 0-100',
      asOf: 'REQUIRED — a real freshness timestamp, e.g. "2:14 PM"',
    },
    intents: ['reference', 'track'],
    domains: ['travel'],
  }),
  createMeta('tierlist', {
    family: 'everyday',
    dataShapes: ['ranking', 'list'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'An S/A/B/C tier-list ranking — a colored tier rail per row with ranked items as chips. Use for "tier list of X", "rank these S to C". An intentionally empty tier still renders as its own row.',
    itemShapes: [{ prop: 'rows', text: 'tier', textAliases: ['label', 'name', 'rank'] }],
    propHints: {
      'rows[].color': "'var(--danger)'|'var(--warning)'|'var(--insight)'|'var(--presence)'",
      'rows[].items': 'plain array of item names in this tier, e.g. ["Item A","Item B"]',
    },
    intents: ['decide', 'reference'],
  }),
  createMeta('paystub', {
    family: 'everyday',
    dataShapes: ['tabular', 'list'],
    requires: ['title', 'payPeriod', 'grossPay', 'earnings', 'deductions', 'netPay'],
    optional: ['icon', 'iconColor', 'employer', 'payDate', 'ytdNet', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A payslip: gross pay, itemized earnings, itemized deductions (shown subtracted), and a net-pay total. Use for "explain my paycheck", "what got deducted", "breakdown of this payslip".',
    itemShapes: [
      { prop: 'earnings', text: 'label', textAliases: ['name', 'description'] },
      { prop: 'deductions', text: 'label', textAliases: ['name', 'description'] },
    ],
  }),
  createMeta('taxbracket', {
    family: 'everyday',
    dataShapes: ['composition', 'scalar'],
    requires: ['title', 'bands', 'income'],
    optional: [
      'icon',
      'iconColor',
      'filingStatus',
      'effectiveRate',
      'marginalRate',
      'currency',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A progressive income-tax bracket bar — segments sized to each bracket\'s real dollar span, a needle marking where the given income lands, and effective-vs-marginal rate readouts computed from the bands. Use for "what tax bracket am I in", "explain marginal vs effective rate".',
    propHints: {
      'bands[].rate': "this band's rate as a percent, e.g. 22 for 22% (not a 0-1 fraction)",
      'bands[].max': 'omit on the last band for an open-ended top bracket',
      currency: "prefix, default '$'",
    },
    intents: ['explain', 'quantify'],
    domains: ['money'],
  }),
  createMeta('menucard', {
    family: 'everyday',
    dataShapes: ['list', 'hierarchy'],
    requires: ['title', 'sections'],
    optional: ['icon', 'iconColor', 'venue', 'subtitle', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A restaurant or event menu — named sections, each item priced with a dotted leader and tagged with dietary chips. Use for "make a menu for X", "dinner party menu", "coffee shop menu board".',
    itemShapes: [
      {
        prop: 'sections',
        text: 'name',
        textAliases: ['category', 'title'],
        children: { prop: 'items', text: 'name', textAliases: ['label', 'dish'] },
      },
    ],
    propHints: {
      'sections[].items[].tags': 'dietary/allergen tags, e.g. ["vegan","gluten-free","spicy"]',
    },
    intents: ['reference', 'plan'],
    domains: ['cooking'],
  }),
  createMeta('familytree', {
    family: 'everyday',
    dataShapes: ['hierarchy', 'structure'],
    requires: ['title', 'people'],
    optional: ['icon', 'iconColor', 'rootId', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A genealogy chart — name/date cards laid out by generation with mating lines and sibship bars. No photos. Use for "draw my family tree", "who are my grandparents", "family tree for X".',
    itemShapes: [{ prop: 'people', text: 'name' }],
    propHints: {
      'people[].parents': 'one or two parent ids, e.g. ["mom-id","dad-id"] or ["mom-id"]',
      'people[].partner': 'a spouse/partner id, only needed if they share no child of record',
      'people[].death': 'a year or date; its presence alone marks the person deceased',
      rootId: 'the id of the person the tree is centered on — highlights their card',
    },
    intents: ['reference', 'explain'],
  }),
  createMeta('seatingchart', {
    family: 'everyday',
    dataShapes: ['geo', 'list'],
    requires: ['title', 'tables', 'assignments'],
    optional: ['icon', 'iconColor', 'venue', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'An event floor plan — round or rectangular tables auto-arranged on a grid, each seat plotted around its table and filled with the assigned guest\'s initials. Use for "seat my wedding guests", "table plan for the gala", "who\'s sitting where".',
    itemShapes: [
      { prop: 'tables', text: 'label', textAliases: ['name'] },
      { prop: 'assignments', text: 'guest', textAliases: ['name'] },
    ],
    propHints: {
      'tables[].shape': "'round'|'rect', default 'round'",
      'tables[].x': 'omit on EVERY table to auto-arrange the whole floor on a grid',
      'assignments[].seatIndex': "0-based, must be less than that table's seats",
    },
    intents: ['plan', 'reference'],
  }),
  createMeta('relationshipmap', {
    family: 'everyday',
    dataShapes: ['relationship', 'hierarchy'],
    requires: ['title', 'people', 'ties'],
    optional: ['icon', 'iconColor', 'layout', 'footer'],
    interactive: false,
    wowWeight: 0.84,
    tier: 'cutting',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A typed people graph — who\'s connected to whom and how (family/ally/rival/romance/colleague), with a kind-keyed legend below. Use for "map the relationships in this story", "who\'s connected to who", "family/rivalry web".',
    itemShapes: [{ prop: 'people', text: 'name', textAliases: ['label'] }],
    propHints: {
      'ties[].kind': "'family'|'ally'|'rival'|'romance'|'colleague'|'other'",
      layout: "'circle'|'grid', default 'circle'",
    },
    intents: ['explain', 'reference'],
  }),
  createMeta('meetingnotes', {
    family: 'everyday',
    dataShapes: ['list', 'sequence'],
    requires: ['title', 'actionItems'],
    optional: [
      'icon',
      'iconColor',
      'meetingDate',
      'attendees',
      'discussionPoints',
      'decisions',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A post-meeting recap — attendees, what was discussed, what got decided, and a checklist of action items with owners and due dates. Distinct from agenda (PRE-meeting scheduling only). Use for "summarize this meeting", "what did we decide and who owns what".',
    itemShapes: [{ prop: 'actionItems', text: 'task', textAliases: ['title', 'label'] }],
    propHints: {
      attendees: 'plain array of names, e.g. ["Sam","Priya"]',
      discussionPoints: 'plain array of short prose points, no sub-objects',
      decisions: 'plain array of short prose decisions, no sub-objects',
      'actionItems[].dueDate': '"Fri", "Jun 20" — a short date/day string',
    },
    intents: ['reference', 'track'],
    domains: ['business'],
    stringItems: ['attendees', 'discussionPoints', 'decisions'],
  }),
  createMeta('stickerchart', {
    family: 'everyday',
    dataShapes: ['status', 'tabular'],
    requires: ['title', 'days', 'marks'],
    optional: ['icon', 'iconColor', 'behavior', 'people', 'rewardAt', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A behavior/reward chart — one row per person (or a single shared row), a star for each earned day, and progress toward a reward threshold. Use for "sticker chart for brushing teeth", "reward chart for the kids", "chore streak with a reward".',
    propHints: {
      days: 'plain array of column labels, e.g. ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]',
      people: 'plain array of names; omit entirely for a single shared row',
      'marks[].person': 'must match a `people` entry when `people` is given; omit otherwise',
      'marks[].day': 'must match a `days` entry',
      rewardAt: 'total stickers needed across the WHOLE chart to earn the reward',
    },
    intents: ['track', 'reference'],
    domains: ['health'],
    stringItems: ['days', 'people'],
  }),
  createMeta('statblock', {
    family: 'everyday',
    dataShapes: ['keyvalue', 'status'],
    requires: ['name', 'ac', 'hp', 'abilities'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'meta',
      'hpFormula',
      'speed',
      'saves',
      'skills',
      'senses',
      'languages',
      'challenge',
      'traits',
      'actions',
      'reactions',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A tabletop-RPG creature/character stat block, D&D / Pathfinder shaped — name and italic type line, Armor Class / Hit Points / Speed, the six-ability table with modifiers computed from the raw scores, then bold-lead-in traits, actions, and reactions between tapered rules. `abilities` is an object of the six raw scores { str, dex, con, int, wis, cha }. Use for "stat block for X", homebrew monsters, or campaign NPC sheets. Never for real-person profiles — use userpersona.',
    itemShapes: [
      {
        prop: 'traits',
        text: 'text',
        textAliases: ['description', 'desc', 'detail'],
        requiredFields: ['name'],
      },
      {
        prop: 'actions',
        text: 'text',
        textAliases: ['description', 'desc', 'detail'],
        requiredFields: ['name'],
      },
      {
        prop: 'reactions',
        text: 'text',
        textAliases: ['description', 'desc', 'detail'],
        requiredFields: ['name'],
      },
    ],
    propHints: {
      abilities:
        'object of the six raw scores, e.g. { "str": 14, "dex": 16, "con": 15, "int": 8, "wis": 12, "cha": 13 } — modifiers are computed from these, never supplied',
      meta: 'the type line, e.g. "Medium humanoid, neutral good"',
      hpFormula: 'the hit-dice formula printed beside the hit points, e.g. "8d8+16"',
      speed: 'e.g. "30 ft., fly 60 ft."',
      saves: 'plain array of save bonuses, e.g. ["Dex +5", "Con +4"]',
      skills: 'plain array of skill bonuses, e.g. ["Stealth +5", "Perception +3"]',
      challenge: 'challenge rating with XP, e.g. "3 (700 XP)"',
    },
    intents: ['reference', 'draft'],
    domains: ['games', 'creative'],
    stringItems: ['saves', 'skills'],
  }),
];
