// Catalog entries for the `finance` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_FINANCE: ComponentCatalog = [
  // — finance —
  createMeta('vestingschedule', {
    family: 'finance',
    dataShapes: ['sequence', 'status'],
    requires: ['title', 'grants'],
    optional: ['icon', 'iconColor', 'asOf', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'Equity vesting timeline: one bar per grant on a shared calendar, flat through the cliff then a computed linear ramp to fully vested, with a "today" needle and a live % vested per holder. Use for founder/employee equity, option grants, RSU schedules.',
    itemShapes: [
      { prop: 'grants', text: 'holder', textAliases: ['name', 'who', 'person', 'employee'] },
    ],
    propHints: {
      'grants[].grantDate': 'ISO date the grant started, e.g. "2023-03-01"',
      'grants[].cliffMonths': 'months from grantDate before anything vests (0 for no cliff)',
      'grants[].vestMonths': 'months from grantDate to fully vested (100%)',
      asOf: 'ISO date the "today" needle marks; omit to use the real current date',
    },
    intents: ['quantify', 'explain', 'track'],
    domains: ['money', 'business'],
  }),
  createMeta('termsheet', {
    family: 'finance',
    dataShapes: ['keyvalue', 'text'],
    requires: ['title', 'terms'],
    optional: ['icon', 'iconColor', 'company', 'round', 'date', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      "Investment term sheet summary: a company/round/date header over a two-column list of deal terms (valuation, board seats, liquidation preference, pro-rata…). Use to summarize a term sheet or offer letter's key clauses.",
    itemShapes: [{ prop: 'terms', text: 'label', textAliases: ['term', 'name', 'key'] }],
    propHints: {
      round: "e.g. 'Series A', 'Seed', 'Series B extension'",
      date: 'ISO date the term sheet is dated',
    },
    intents: ['reference', 'explain', 'decide'],
    domains: ['money', 'business'],
  }),
  createMeta('fundraisingrounds', {
    family: 'finance',
    dataShapes: ['series', 'comparison'],
    requires: ['title', 'rounds'],
    optional: ['icon', 'iconColor', 'currency', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'Round-by-round fundraising history: one stacked column per round (pre-money base + raised segment reaching post-money), left-to-right in round order, with lead investor and step-up multiple as captions. Use for "how has the company raised over time".',
    itemShapes: [{ prop: 'rounds', text: 'name', textAliases: ['round', 'label'] }],
    propHints: {
      currency: 'ISO 4217 code, e.g. "USD" (default USD)',
      'rounds[].stepUp':
        "valuation step-up vs. the prior round's post-money, e.g. 2.4 for a '2.4x' caption — only include when you can compute it from the prior round",
    },
    intents: ['quantify', 'explain', 'track'],
    domains: ['money', 'business'],
  }),
  createMeta('saferterms', {
    family: 'finance',
    dataShapes: ['keyvalue', 'scalar'],
    requires: ['title', 'instrument', 'principal'],
    optional: [
      'icon',
      'iconColor',
      'investor',
      'valuationCap',
      'discountPct',
      'mfn',
      'interestRate',
      'maturityDate',
      'conversionNote',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      "A SAFE or convertible note's headline terms: valuation cap, discount, and MFN as stat tiles, plus an interest-rate/maturity row for a note. Set instrument to 'safe' or 'note' — the rate/maturity row only shows for a note.",
    propHints: {
      instrument: "'safe'|'note'",
      principal: 'the investment amount',
      valuationCap: 'the SAFE/note valuation cap; omit if the round has none',
      discountPct: "conversion discount, 0-100 (e.g. 20 for 20% off the next round's price)",
      mfn: 'true if this holder gets the best terms of any later SAFE/note before it converts',
      interestRate: "note-only: annual interest rate, 0-100. Don't set for a SAFE.",
      maturityDate: "note-only: ISO date the note matures. Don't set for a SAFE.",
      conversionNote: 'one plain-language sentence on how/when this converts to equity',
    },
    intents: ['quantify', 'explain', 'reference'],
    domains: ['money', 'business'],
  }),
  createMeta('dilutionwaterfall', {
    family: 'finance',
    dataShapes: ['composition', 'sequence'],
    requires: ['title', 'rounds'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'Ownership dilution across financing rounds: a 100%-stacked column per round, each holder keeping one consistent color with a thin ribbon connecting its segment to the next round. Use for "how did dilution play out across our rounds", cap-table evolution over time.',
    itemShapes: [
      {
        prop: 'rounds',
        text: 'round',
        textAliases: ['name', 'label'],
        children: { prop: 'holders', text: 'holder', textAliases: ['name', 'who', 'investor'] },
      },
    ],
    propHints: {
      'rounds[].holders[].pct': 'ownership % this round, 0-100; need not sum to exactly 100',
    },
    intents: ['quantify', 'explain', 'track'],
    domains: ['money', 'business'],
  }),
  createMeta('threestatementlink', {
    family: 'finance',
    dataShapes: ['tabular', 'flow'],
    requires: ['title', 'period', 'statements'],
    optional: ['icon', 'iconColor', 'links', 'currency', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 12,
    colMin: 9,
    coercer: 'generic',
    blurb:
      "The three linked financial statements side by side (income statement, balance sheet, cash flow) with 2-3 curved connectors showing where a line on one feeds another (net income → retained earnings, net income → cash flow's own net income). `statements` is EXACTLY 3 entries in that order.",
    itemShapes: [
      {
        prop: 'statements',
        text: 'name',
        children: { prop: 'rows', text: 'label', textAliases: ['line', 'item'] },
      },
      { prop: 'links', text: 'label' },
    ],
    propHints: {
      'statements[]':
        "exactly 3 objects, name in order: 'Income Statement','Balance Sheet','Cash Flow'",
      'statements[].rows[].value': 'use a negative for a cost/outflow — rendered in parentheses',
      'statements[].rows[].indent': 'integer ≥0 — indent the label under a subtotal',
      'statements[].rows[].bold': 'true for a subtotal/total row (rule + tint)',
      'links[].from': "a row label to connect from, e.g. 'Net income'",
      'links[].to': 'a row label in a LATER statement to connect to',
      currency: 'ISO 4217 code, e.g. "USD" (default USD)',
    },
    intents: ['explain', 'reference', 'quantify'],
    domains: ['money', 'business'],
  }),
  createMeta('yieldcurve', {
    family: 'finance',
    dataShapes: ['series', 'relationship'],
    requires: ['title', 'curve'],
    optional: ['icon', 'iconColor', 'compareCurve', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Interest rate by tenor (1M through 30Y) on a categorical axis, with any inverted stretch — a longer tenor paying less than a shorter one — auto-shaded. Optional second curve for comparison (e.g. a year ago). Use for "is the yield curve inverted", rate-environment questions.',
    itemShapes: [
      { prop: 'curve', text: 'tenor' },
      { prop: 'compareCurve', text: 'tenor' },
    ],
    propHints: {
      'curve[].tenor': 'a short maturity label in increasing order, e.g. "1M","3M","1Y","10Y"',
      'curve[].rate': 'the yield, in percent (7 for 7%, not 0.07)',
    },
    intents: ['explain', 'quantify', 'reference'],
    domains: ['money', 'business'],
  }),
  createMeta('efficientfrontier', {
    family: 'finance',
    dataShapes: ['relationship', 'distribution'],
    requires: ['title', 'assets', 'frontier'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.77,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Risk/return scatter of individual assets with the efficient frontier drawn as a curve — the frontier is drawn exactly as given, never fitted or computed here, so only pass points you actually believe trace it. Use for portfolio-construction and risk/return comparison questions.',
    itemShapes: [{ prop: 'assets', text: 'label' }],
    propHints: {
      'assets[].risk': 'volatility, in percent (15 for 15%)',
      'assets[].return': 'expected return, in percent',
      'assets[].highlight': "true for the one asset/portfolio you're calling out with a ring",
      frontier: 'points ALREADY ordered along the curve — this block draws them, never fits a line',
    },
    intents: ['explain', 'decide', 'quantify'],
    domains: ['money', 'business'],
  }),
  createMeta('bondladder', {
    family: 'finance',
    dataShapes: ['sequence', 'comparison'],
    requires: ['title', 'rungs'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A bond ladder: one leader-style bar per rung, ordered by maturity (earliest first, never resorted by yield), with a face-value figure trailing each row. Use for laddered fixed-income holdings, CD/Treasury ladders.',
    itemShapes: [{ prop: 'rungs', text: 'label', textAliases: ['name', 'bond'] }],
    propHints: {
      'rungs[].maturity':
        "an ISO date or short label like '3Y' — sets the row order, not authored order",
      'rungs[].yieldPct': 'yield to maturity, in percent',
      'rungs[].faceValue': 'par/face value of this rung',
    },
    intents: ['quantify', 'reference', 'track'],
    domains: ['money', 'business'],
  }),
  createMeta('cashflowtimeline', {
    family: 'finance',
    dataShapes: ['series', 'flow'],
    requires: ['title', 'flows'],
    optional: ['icon', 'iconColor', 'periodLabel', 'discountRate', 'currency', 'footer'],
    interactive: true,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'The engineering-economics cash-flow diagram: a horizontal period axis (0..N) with an upward arrow per inflow and a downward arrow per outflow, arrow length scaled to the amount on one shared scale, plus a computed NPV row when a discount rate is given. flows is [{period, amount, label?}] with SIGNED amounts (+ in, − out). Never for a running balance over time — use plot. Never for loan amortization schedules — use amortization.',
    itemShapes: [{ prop: 'flows', requiredFields: ['period', 'amount'] }],
    propHints: {
      'flows[].period':
        'integer period index ≥ 0 (0 = now); repeats allowed — same-period flows stack side by side',
      'flows[].amount': 'signed: positive = inflow (arrow up), negative = outflow (arrow down)',
      'flows[].label': 'short name shown on hover, e.g. "Salvage value"',
      periodLabel: "the unit of one period, e.g. 'Year' (default), 'Month', 'Quarter'",
      discountRate: 'per-period rate as a FRACTION, e.g. 0.08 for 8% — adds the computed NPV row',
      currency: 'currency symbol prefixed to amounts, default "$"',
    },
    intents: ['quantify', 'explain', 'decide'],
    domains: ['money', 'business', 'education'],
  }),
];
