// Catalog entries for the `flows` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_FLOWS: ComponentCatalog = [
  createMeta('trustmap', {
    family: 'flows',
    dataShapes: ['flow', 'relationship', 'list'],
    requires: ['title', 'flows'],
    optional: ['icon', 'iconColor', 'checklist', 'note', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Privacy map of where each kind of data is stored and who can see it, with an optional security checklist.',
    itemShapes: [
      { prop: 'flows', text: 'data', textAliases: ['what', 'kind', 'label'] },
      { prop: 'checklist', text: 'label', textAliases: ['text', 'item', 'name'] },
    ],
    propHints: {
      'flows[]':
        '{ data, location, access, retention? } — data=what it is, location=where stored, access=who can see it',
      'checklist[].ok': 'true (satisfied, green check) | false (a gap, amber alert)',
    },
    intents: ['reference', 'explain', 'decide'],
  }),
  // — flows —
  createMeta('kanban', {
    family: 'flows',
    dataShapes: ['flow', 'status'],
    requires: ['title', 'stages'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Multi-stage workflow board with cards, assignees, and progress tags.',
  }),
  createMeta('wizard', {
    family: 'flows',
    dataShapes: ['sequence', 'navigation'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'activeStep', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Step-by-step guide or onboarding flow with status indicators.',
    propHints: {
      'steps[].status': "'done'|'active'|'todo'|'blocked'|'risk'",
    },
  }),
  createMeta('decisiontree', {
    family: 'flows',
    dataShapes: ['flow', 'hierarchy'],
    requires: ['title', 'rootId', 'nodes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      "Branching yes/no decision logic tree leading to outcomes. Optionally an ML classifier tree: a node's splitFeature+threshold renders as a learned split ('feature ≤ threshold') instead of a plain question, and classDistribution (className+count per class) renders as a class-count bar + legend at that node, the way a trained decision-tree classifier is diagrammed.",
    propHints: {
      'nodes[].impurityMetric': "'gini'|'entropy'",
    },
  }),
  createMeta('goaltree', {
    family: 'flows',
    dataShapes: ['hierarchy', 'status'],
    requires: ['title', 'objectives'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'OKR tree: objectives with key results and progress tracking.',
  }),
  createMeta('plandag', {
    family: 'flows',
    dataShapes: ['flow', 'hierarchy'],
    requires: ['title', 'nodes', 'edges'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.85,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Directed acyclic graph: dependencies, tasks, and x/y layout.',
    propHints: {
      'nodes[].status': "'done'|'active'|'todo'|'blocked'|'risk'",
    },
  }),
  createMeta('milestones', {
    family: 'flows',
    dataShapes: ['sequence'],
    requires: ['title', 'milestones'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Chronological timeline of events with dates and status.',
  }),
  createMeta('processflow', {
    family: 'flows',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Linear process steps with branching notes and details.',
  }),
  createMeta('journeymap', {
    family: 'flows',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'stages'],
    optional: ['icon', 'iconColor', 'persona', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Customer/user journey with emotions, actions, and touchpoints.',
  }),
  createMeta('logicmodel', {
    family: 'flows',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'columns'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 12,
    colMin: 9,
    coercer: 'generic',
    blurb:
      'Program logic model: five locked columns (inputs, activities, outputs, outcomes, impact), each a short bullet list, read left to right as a causal chain.',
    // `stage` is the column's join key — the renderer buckets by it and silently discards any
    // column without one of the five, so it must be repaired (label/name/phase → stage) and
    // required here rather than validating absent and rendering an all-placeholder card.
    itemShapes: [
      {
        prop: 'columns',
        text: 'stage',
        textAliases: ['label', 'name', 'phase'],
        closedVocab: true,
      },
    ],
    propHints: {
      'columns[].stage': "'inputs'|'activities'|'outputs'|'outcomes'|'impact', exactly 5 entries",
    },
  }),
  createMeta('orgchart', {
    family: 'flows',
    dataShapes: ['hierarchy'],
    requires: ['title', 'rootId', 'nodes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Recursive org structure with parent-child relationships.',
  }),
  createMeta('issuetree', {
    family: 'flows',
    dataShapes: ['hierarchy'],
    requires: ['title', 'rootQuestion', 'nodes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'nodes', text: 'label', textAliases: ['name', 'question', 'title'] }],
    blurb:
      "McKinsey-style MECE issue tree: rootQuestion broken left-to-right into mutually exclusive branches down to leaf boxes carrying a finding. nodes:[{id,label,children?(ids),isLeaf?,finding?}] — a node's top-level branches are inferred as whichever ids no other node claims as a child.",
  }),
  createMeta('roadmap', {
    family: 'flows',
    dataShapes: ['sequence', 'flow', 'comparison'],
    requires: ['title', 'quarters', 'lanes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Multi-lane quarterly roadmap with item spans and statuses.',
    propHints: {
      'lanes[].items[].status': "'done'|'active'|'todo'|'blocked'|'risk'",
    },
    stringItems: ['quarters'],
  }),
  createMeta('contentcalendar', {
    family: 'flows',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'platforms', 'weeks', 'cells'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Creator/marketing content calendar: platforms × weeks grid of status-colored post tiles. cells:[{platform,week,status,title?,format?}] — one entry per planned post; an unlisted (platform, week) pair renders as an empty slot.',
    propHints: {
      'cells[].status': "'idea'|'drafted'|'scheduled'|'posted'",
    },
    stringItems: ['platforms', 'weeks'],
  }),
  createMeta('headcountplan', {
    family: 'flows',
    dataShapes: ['status', 'composition'],
    requires: ['title', 'depts'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'depts', text: 'name', textAliases: ['dept', 'department', 'team', 'group'] },
    ],
    blurb:
      'HR headcount plan: a filled-vs-budgeted meter per department, open reqs, and a totals row.',
  }),
  // — flows additions —
  createMeta('chronologicaltimeline', {
    family: 'flows',
    dataShapes: ['sequence'],
    requires: ['title', 'events'],
    optional: ['icon', 'iconColor', 'startLabel', 'endLabel', 'eras', 'footer'],
    interactive: false,
    wowWeight: 0.71,
    tier: 'frontier',
    colDefault: 10,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Vertical or horizontal timeline of dated events with icons, descriptions, and status.',
    itemShapes: [{ prop: 'events', text: 'title', textAliases: ['label', 'name', 'heading'] }],
    propHints: {
      'events[].at': 'position 0..100 along the axis',
    },
  }),
  createMeta('skilltree', {
    family: 'flows',
    dataShapes: ['hierarchy', 'status'],
    requires: ['nodes'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Tiered progression / tech tree: skills in tier bands with prerequisite edges, point costs, and locked/unlocked states.',
    intents: ['plan', 'explain', 'reference'],
    domains: ['sports', 'education', 'productivity'],
    propHints: {
      'nodes[].state': "'locked'|'available'|'unlocked'|'maxed'",
      'nodes[].tier': 'integer band, 0-based (0 = foundation row at top)',
      'nodes[].requires': 'array of node ids that must be unlocked first',
    },
  }),
  createMeta('businesscanvas', {
    family: 'flows',
    dataShapes: ['keyvalue', 'composition'],
    requires: ['valueProposition'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'variant',
      'keyPartners',
      'keyActivities',
      'keyResources',
      'customerRelationships',
      'channels',
      'customerSegments',
      'costStructure',
      'revenueStreams',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Business Model Canvas / Lean Canvas: the canonical nine-box strategy grid — partners | activities over resources | value proposition (center) | relationships over channels | segments, with cost structure and revenue streams splitting the bottom row. Each region is a short bullet list (string array); unfilled regions stay visible but dimmed. Never for a value chain or process sequence — use processflow. Never for org structure — use orgchart.',
    stringItems: [
      'keyPartners',
      'keyActivities',
      'keyResources',
      'valueProposition',
      'customerRelationships',
      'channels',
      'customerSegments',
      'costStructure',
      'revenueStreams',
    ],
    propHints: {
      variant:
        "'bmc' | 'lean' — 'lean' relabels the same nine props onto Lean Canvas slots: keyPartners→Problem, keyActivities→Solution, keyResources→Key Metrics, valueProposition→Unique Value Proposition, customerRelationships→Unfair Advantage; channels, customerSegments, costStructure, revenueStreams keep their labels",
    },
    intents: ['plan', 'explain', 'decide'],
    domains: ['business'],
  }),
];
