// Catalog entries for the `forms` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_FORMS: ComponentCatalog = [
  // — forms —
  createMeta('blanks', {
    family: 'forms',
    dataShapes: ['selection', 'comparison'],
    requires: ['title', 'slots'],
    optional: ['icon', 'iconColor', 'intro', 'footer'],
    interactive: true,
    wowWeight: 0.85,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'custom',
    propHints: {
      'slots[].label': 'the hole label shown to the user',
      'slots[].kind': "'date'|'number'|'text'|'choice'",
      'slots[].key': "lowercase slug, unique, e.g. 'deadline'",
      'slots[].prompt': 'the one question this hole replaces',
      'slots[].accent': 'var(--presence)|var(--insight)|var(--warning)',
    },
    blurb:
      'Leave glowing holes for the 1–3 values only the user can give (a real deadline, their energy, what would make it a no) instead of guessing them.',
  }),
  createMeta('buttonbar', {
    family: 'forms',
    dataShapes: ['selection', 'action'],
    requires: ['title', 'buttons'],
    optional: ['icon', 'iconColor', 'hint', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'buttons', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Gallery of button variants with ripple feedback and state tracking.',
  }),
  createMeta('textfield', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'fields'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'fields', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Labeled text inputs with validation states and helper text.',
    propHints: {
      'fields[].state': "'default'|'error'|'success'",
    },
  }),
  createMeta('textarea', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'label',
      'placeholder',
      'value',
      'max',
      'minRows',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Auto-growing textarea with live character counter.',
  }),
  createMeta('select', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'options'],
    optional: ['icon', 'iconColor', 'label', 'placeholder', 'selected', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.58,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Styled single-select dropdown with optional icons and captions.',
  }),
  createMeta('combobox', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'label', 'placeholder', 'selected', 'noun', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Searchable autocomplete with metadata hints and live filtering.',
  }),
  createMeta('checkboxgroup', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'allLabel', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Multi-select checkboxes with indeterminate select-all toggle.',
  }),
  createMeta('actionchecklist', {
    family: 'forms',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'subtitle', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['task', 'step', 'text', 'name'] }],
    blurb:
      'Checkable next-steps the user ticks off — a plan or 30-day checklist with priority + due tags.',
    propHints: {
      'items[].priority': "'high'|'medium'|'low'",
    },
  }),
  createMeta('radiogroup', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'options'],
    optional: ['icon', 'iconColor', 'layout', 'selected', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.62,
    tier: 'base',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Radio cards or rows with icons, captions, and value badges.',
  }),
  createMeta('switchset', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.58,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Rows of labeled toggle switches with descriptions.',
  }),
  createMeta('togglegroup', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'mode', 'hint', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.63,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Multi or single-mode button toggle group (text formatting, alignment).',
  }),
  createMeta('otp', {
    family: 'forms',
    dataShapes: ['selection'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'prompt', 'length', 'code', 'resendLabel', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Segmented one-time-passcode input with verification and resend.',
  }),
  createMeta('preflightchecklist', {
    family: 'forms',
    dataShapes: ['sequence', 'list'],
    requires: ['title', 'sections'],
    optional: ['icon', 'iconColor', 'aircraft', 'footer'],
    interactive: true,
    wowWeight: 0.5,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'sections',
        text: 'name',
        textAliases: ['title', 'phase', 'label'],
        children: {
          prop: 'items',
          text: 'label',
          textAliases: ['task', 'step', 'text', 'name'],
        },
      },
    ],
    blurb:
      'Aviation preflight walk-around ticked off by phase (Before Start, Before Takeoff, Shutdown…), critical items flagged.',
  }),
  createMeta('estateplanchecklist', {
    family: 'forms',
    dataShapes: ['status', 'list'],
    requires: ['title', 'documents'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [
      { prop: 'documents', text: 'category', textAliases: ['type', 'document', 'name', 'label'] },
    ],
    blurb:
      'Estate-planning status board — Will, POA, Healthcare Proxy, Beneficiary designations, Digital assets — grouped, each flagged done/missing/needs-update.',
    propHints: {
      'documents[].category':
        "'Will'|'POA'|'Healthcare Proxy'|'Beneficiary designations'|'Digital assets'",
      'documents[].status': "'done'|'missing'|'needs-update'",
      'documents[].lastReviewed': 'when it was last reviewed, e.g. "March 2023" (omit if never)',
    },
  }),
  createMeta('visachecklist', {
    family: 'forms',
    dataShapes: ['status', 'list'],
    requires: ['title', 'documents'],
    optional: ['icon', 'iconColor', 'caseType', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'documents', text: 'name', textAliases: ['document', 'label', 'title'] }],
    blurb:
      'Immigration filing checklist for a specific case type (H-1B, I-485…) — required documents set apart from optional ones, each flagged done/pending/missing.',
    propHints: {
      caseType: 'the filing this is for, e.g. "H-1B change of status", "I-485 adjustment"',
      'documents[].required': 'true unless the document is genuinely optional for this filing',
      'documents[].status': "'done'|'pending'|'missing'",
    },
  }),
];
