// Catalog entries for the `layout` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_LAYOUT: ComponentCatalog = [
  // — layout —
  createMeta('callout', {
    family: 'layout',
    dataShapes: ['text'],
    requires: ['title', 'body'],
    optional: ['icon', 'iconColor', 'tone', 'kicker', 'points', 'collapsed', 'footer'],
    interactive: true,
    wowWeight: 0.45,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Emphasized aside with optional collapsible body and tone-based accent bar.',
    propHints: {
      tone: "'info'|'success'|'warn'|'danger'|'neutral'",
    },
  }),
  createMeta('verdictcard', {
    family: 'layout',
    dataShapes: ['comparison', 'text'],
    requires: ['title', 'verdict'],
    optional: ['icon', 'iconColor', 'stance', 'label', 'reason', 'caveat', 'confidence', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Opening verdict — a yes/no/maybe stance badge, a bold one-line call, the reason, and an honest caveat.',
    propHints: {
      stance: "'yes'|'no'|'maybe'|'caution' (drives the badge word, icon, and accent)",
      confidence: "'high'|'medium'|'low' — qualitative only, never a fabricated percentage",
    },
  }),
  createMeta('scenarioset', {
    family: 'layout',
    dataShapes: ['comparison', 'distribution'],
    requires: ['title', 'scenarios'],
    optional: ['icon', 'iconColor', 'metric', 'highlight', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'scenarios', text: 'value', textAliases: ['outcome', 'result', 'label'] }],
    blurb:
      'Best / likely / worst outcome panels — a decision’s range without faking one precise number.',
    propHints: {
      'scenarios[].kind': "'best'|'likely'|'worst'",
    },
  }),
  createMeta('worthit', {
    family: 'layout',
    dataShapes: ['comparison', 'scalar'],
    requires: ['title', 'verdict'],
    optional: [
      'icon',
      'iconColor',
      'product',
      'price',
      'priceNote',
      'worthItIf',
      'skipIf',
      'dealBreaker',
      'forWho',
      'bottomLine',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A single-product "is it worth it for YOU" verdict — a worth-it/skip/depends call with honest price-vs-typical, a worth-it-IF / skip-IF fit split, the one deal-breaker, and who it is for. For ONE option; use compare for several, verdictcard for a generic yes/no.',
    propHints: {
      verdict: "'worth-it'|'skip'|'depends'",
      priceNote:
        'honest price context, e.g. "vs ~$180 typical" — or say plainly if no reliable price was found',
      worthItIf: 'array of conditions where buying is the right call',
      skipIf: 'array of conditions where they should pass',
    },
    intents: ['decide', 'compare'],
    stringItems: ['worthItIf', 'skipIf'],
  }),
  createMeta('companionnote', {
    family: 'layout',
    dataShapes: ['text'],
    requires: ['reflection'],
    optional: ['follow', 'chip'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A low-chrome "I\'m here with you" reflection that mirrors the feeling in the user\'s words — one warm line, no advice, metrics, icons, or bullets. For emotional moments where being heard matters more than information; reframecard offers a cognitive move instead, and an acute crisis needs a dedicated safety surface, not this.',
    propHints: {
      reflection:
        'one warm second-person reflection of what the user is feeling, drawn ONLY from their words — never advice or invented facts',
      chip: 'optional soft cue, e.g. "I\'m here" or "take your time"',
    },
    intents: ['comfort', 'reflect'],
  }),
  createMeta('positioncard', {
    family: 'layout',
    dataShapes: ['status', 'scalar'],
    requires: ['title', 'levels'],
    optional: ['icon', 'iconColor', 'atLevel', 'marker', 'reason', 'watchFor', 'caveat', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A calibrated normal→concerning scale placing a situation on a low→high continuum with the current level marked, an honest read, and concrete escalation triggers. Merges triage / normal-spectrum / reassure-watch — shows a RANGE, never a fake verdict. For "how worried should I be / is this normal / how bad is this".',
    itemShapes: [{ prop: 'levels', text: 'label', textAliases: ['name', 'level'] }],
    propHints: {
      'levels[].tone': "'good'|'caution'|'bad' (low→high)",
      atLevel: '0-based index of the level where the situation currently falls',
      watchFor: 'concrete escalation triggers, e.g. ["pain spreads to your arm","fever over 39°C"]',
    },
    intents: ['explain', 'decide', 'reflect'],
    stringItems: ['watchFor'],
  }),
  createMeta('differential', {
    family: 'layout',
    dataShapes: ['ranking', 'comparison'],
    requires: ['title', 'causes'],
    optional: ['icon', 'iconColor', 'prompt', 'caveat', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Ranked plausible explanations for a symptom, fault, or result — each with an honest likelihood band (common / less-common / rare), the tell-tale that fits, what points elsewhere, and a can\'t-miss-serious flag. For "what could be causing X"; shows possibilities with honest odds, never one confident answer.',
    itemShapes: [{ prop: 'causes', text: 'name', textAliases: ['cause', 'label', 'explanation'] }],
    propHints: {
      'causes[].likelihood': "'common'|'less-common'|'rare'",
      'causes[].serious': 'true to flag a must-not-miss serious possibility even if rare',
      prompt:
        'one concrete way to narrow it down, e.g. "check whether it worsens when you breathe in"',
    },
    intents: ['explain', 'decide'],
  }),
  createMeta('reframecard', {
    family: 'layout',
    dataShapes: ['text'],
    requires: ['thought', 'reframe'],
    optional: ['title', 'icon', 'iconColor', 'distortion', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A cognitive reframe of ONE stuck thought: the harsh thought shown VERBATIM, a gently-named distortion, then a warmer, truer counter-thought — the visual weight is on the shift, not a scoreboard. Offers a cognitive MOVE; companionnote only mirrors the feeling with no move, and verdictcard answers a yes/no decision.',
    propHints: {
      thought:
        'the harsh thought in the user’s OWN words, verbatim — never paraphrased or invented',
      distortion:
        'gentle name for the thinking pattern, e.g. ‘catastrophizing’ | ‘mind-reading’ | ‘all-or-nothing’ | ‘fortune-telling’ | ‘overgeneralizing’',
      reframe:
        'the warmer, truer counter-thought — kinder but honest, grounded in what is also true, not toxic positivity',
    },
    intents: ['comfort', 'reflect'],
  }),
  createMeta('breathpacer', {
    family: 'layout',
    dataShapes: ['sequence', 'status'],
    requires: [],
    optional: ['title', 'icon', 'iconColor', 'pattern', 'inhale', 'hold', 'exhale', 'note'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 5,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'A paced breathing exercise the user does WITH the canvas: a soft orb expands on the inhale, holds, and settles on the exhale in a continuous pure-CSS loop, with a phase caption. For acute stress or overwhelm where a moment of regulation helps more than words; companionnote reflects the feeling, this gives the body something calming to do. Set a named pattern or explicit inhale/hold/exhale seconds.',
    propHints: {
      pattern:
        "'478' (4-7-8 relaxing breath) | 'box' (4-4-4 even square) | 'calm' (gentle 4 in / 6 out, default)",
      inhale: 'inhale seconds (overrides the pattern); kept within a calm 2–12s range',
      hold: 'hold seconds, 0 for no hold (overrides the pattern)',
      exhale: 'exhale seconds (overrides the pattern); kept within a calm 2–14s range',
    },
    intents: ['comfort', 'reflect'],
  }),
  createMeta('copingmenu', {
    family: 'layout',
    dataShapes: ['list', 'selection'],
    requires: ['options'],
    optional: ['title', 'icon', 'iconColor', 'intro', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A permission-giving menu of doable-now coping options, each tagged by CAPACITY (effort + time) so an overwhelmed person can pick what feels possible — no pressure to do all of them. For comfort/overwhelm moments; use a plain checklist for neutral to-dos, companionnote when being heard matters more than doing anything.',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'action', 'title'] }],
    propHints: {
      'options[].effort': "'low'|'medium'|'high'",
      'options[].time': 'a small honest commitment, e.g. "2 min" or "10 min"',
      intro:
        'a gentle permission line, e.g. “Pick whatever feels possible — you don’t have to do all of them.”',
    },
    intents: ['comfort', 'plan', 'howto'],
  }),
  createMeta('subtextdecode', {
    family: 'layout',
    dataShapes: ['ranking', 'text', 'comparison'],
    requires: ['title', 'message', 'readings'],
    optional: ['icon', 'iconColor', 'flavor', 'cantKnow', 'reply', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'Decodes a received message the user is unsure about: the verbatim message pinned at top, then 2–3 ranked interpretations each with an honest likelihood band and the exact textual cue it rests on, a "you can\'t know for sure" line, and one clarifying reply to send. The caution flavor reframes the readings as red flags for a scam/manipulation screen. For "what did they mean by this / is this a scam"; differential is for causes of a fault or symptom, not tone in someone\'s words.',
    itemShapes: [
      { prop: 'readings', text: 'interpretation', textAliases: ['meaning', 'reading', 'label'] },
    ],
    propHints: {
      flavor:
        "'tone' (decode intent/feeling) | 'caution' (reframe readings as red flags / scam screen)",
      'readings[].likelihood': "'most likely'|'possible'|'less likely'",
      message: 'the received message reproduced VERBATIM — never paraphrased or invented',
      'readings[].cue':
        'the exact word or phrasing in the message this reading rests on (or, with flavor:caution, the red flag)',
      cantKnow: 'an honest line that you cannot be certain of intent from text alone',
      reply: 'one short clarifying message the user could send to find out',
    },
    intents: ['reflect', 'decide', 'draft', 'comfort'],
  }),
  createMeta('rehearsal', {
    family: 'layout',
    dataShapes: ['flow', 'sequence', 'text'],
    requires: ['title', 'opener', 'branches'],
    optional: ['icon', 'iconColor', 'exit', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A branching playbook for a hard conversation: a quotable opener, then 2-3 likely reactions as branches (each with a coached reply and why it works) and a graceful exit line. Framed as rehearsal, not prediction. For "how do I bring this up / what do I say if they react badly"; dialogue gives a fixed scripted exchange and decisiontree a logic flowchart instead.',
    itemShapes: [{ prop: 'branches', text: 'reaction', textAliases: ['response', 'objection'] }],
    propHints: {
      opener: 'the quotable line to START the conversation, in the user’s own voice',
      'branches[].reaction':
        'how the other person might react, completing "If they …" (e.g. "get defensive", "go quiet", "say it is not a big deal")',
      'branches[].say': 'the coached, quotable response to THAT reaction',
      'branches[].why': 'optional one line on why that response works',
      exit: 'a graceful line to wrap up if it stalls, e.g. "Let us pick this up after dinner"',
    },
    intents: ['draft', 'plan', 'comfort', 'reflect'],
  }),
  createMeta('messagescriptset', {
    family: 'layout',
    dataShapes: ['list', 'text'],
    requires: ['title', 'scripts'],
    optional: ['icon', 'iconColor', 'intro', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A bundle of ready-to-send messages aimed at SEVERAL targets at once — each a card with a channel chip, the exact copy-friendly line to send, and an optional "if they push back" rebuttal. For "write me what to say to cancel / dispute / ask X across these N places"; use compose’s messagedraft for ONE polished message to ONE recipient.',
    itemShapes: [{ prop: 'scripts', text: 'message', textAliases: ['line', 'script', 'text'] }],
    propHints: {
      'scripts[].channel': "'email'|'phone'|'in-app'|'chat'",
      'scripts[].target': 'who the line is for: the recipient, vendor, or service',
      'scripts[].message':
        'the exact line to send, in the user’s own words — never an invented fact',
      'scripts[].rebuttal': 'what to say if they push back or counter-offer',
    },
    intents: ['draft', 'plan', 'howto'],
  }),
  createMeta('talktrack', {
    family: 'layout',
    dataShapes: ['sequence', 'text'],
    requires: ['title', 'lines'],
    optional: ['icon', 'iconColor', 'totalTime', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A speakable, word-for-word talk-track / teleprompter — the literal sentences to SAY, in order, each large and calm, with a small delivery beat ("pause here", "~15s") beside it. For a toast, pitch, interview answer, or hard phone call. Distinct from takeaways (bullets to remember): these are spoken lines to read aloud.',
    itemShapes: [{ prop: 'lines', text: 'say', textAliases: ['line', 'text', 'words'] }],
    propHints: {
      'lines[].say': 'the literal words to say for this line — one sentence or beat at a time',
      'lines[].beat': 'a short delivery/timing note, e.g. "pause here", "slow down", or "~15s"',
      totalTime: 'honest overall length, e.g. "~90s" — never invented precision',
    },
    intents: ['draft', 'plan', 'comfort', 'howto'],
  }),
  createMeta('lifeline', {
    family: 'layout',
    dataShapes: ['text', 'list'],
    requires: ['resources'],
    optional: ['title', 'message', 'safetyQuestion', 'grounding', 'reassurance'],
    interactive: false,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A calm crisis-support surface: a warm opener, REAL verified helplines (region-appropriate) made prominent and tappable, an honest note that Mavéa is not a substitute for a person, and an optional grounding offer. Mavéa leads with this on an acute self-harm / abuse / emergency turn — never a chart or a reflection.',
    itemShapes: [{ prop: 'resources', text: 'name', textAliases: ['service', 'line', 'label'] }],
    propHints: {
      'resources[].contact': 'how to reach them, e.g. "Call or text 988"',
      'resources[].href': 'a tel: or sms: link, e.g. "tel:988" or "sms:741741"',
      message: "a warm, validating opener for the user's situation — never clinical or alarming",
      resources: "REAL, verified crisis helplines for the user's region — never invented numbers",
    },
    intents: ['comfort'],
  }),
  createMeta('proscons', {
    family: 'layout',
    dataShapes: ['comparison'],
    requires: ['title', 'pros', 'cons'],
    optional: ['icon', 'iconColor', 'prosLabel', 'consLabel', 'verdict', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      { prop: 'pros', text: 'text', textAliases: ['label', 'name', 'title'] },
      { prop: 'cons', text: 'text', textAliases: ['label', 'name', 'title'] },
    ],
    blurb:
      'A decision weighed as two opposing columns — PROS vs CONS — with weight indicators and an optional verdict tally. Never for a neutral side-by-side feature comparison — use compare or datatable.',
  }),
  createMeta('takeaways', {
    family: 'layout',
    dataShapes: ['list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'heading', 'footer'],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'text', textAliases: ['label', 'name', 'title', 'point'] }],
    blurb: 'Numbered key takeaway list with optional detail per item; click to mark done.',
  }),
  createMeta('faq', {
    family: 'layout',
    dataShapes: ['list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'defaultOpen', 'multi', 'footer'],
    interactive: true,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'q', textAliases: ['question', 'title', 'label'] }],
    blurb: 'Accordion of Q&A pairs; click to expand/collapse, optionally multi-open.',
  }),
  createMeta('tabs', {
    family: 'layout',
    dataShapes: ['navigation'],
    requires: ['title', 'tabs'],
    optional: ['icon', 'iconColor', 'defaultTab', 'accent', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [{ prop: 'tabs', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Tabbed panel switcher with labeled tabs, optional icons and count badges.',
  }),
  createMeta('divider', {
    family: 'layout',
    dataShapes: ['navigation'],
    requires: ['title', 'heading'],
    optional: ['icon', 'iconColor', 'eyebrow', 'sub', 'badge', 'badgeColor', 'chips', 'footer'],
    interactive: false,
    wowWeight: 0.35,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'chips', text: 'label', textAliases: ['name', 'text', 'title'] }],
    blurb: 'Section divider with heading, optional eyebrow, count badge, and jump chips.',
  }),
  createMeta('pullquote', {
    family: 'layout',
    dataShapes: ['text'],
    requires: ['title', 'quote'],
    optional: ['icon', 'iconColor', 'author', 'role', 'tone', 'variants', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'variants', text: 'quote', textAliases: ['text', 'quote', 'body'] }],
    blurb: 'Large attributed quote with tone accent bar; cycle through variant quotes.',
    propHints: {
      tone: "'info'|'success'|'warn'|'danger'|'neutral'",
    },
  }),
  createMeta('storystrip', {
    family: 'layout',
    dataShapes: ['sequence'],
    requires: ['title', 'panels'],
    optional: ['icon', 'iconColor', 'start', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'panels', text: 'heading', textAliases: ['title', 'label', 'name'] }],
    blurb: 'Sequential narrative panels (comic-strip style); stepper advances through story.',
  }),
  createMeta('casestudy', {
    family: 'layout',
    dataShapes: ['sequence'],
    requires: ['title', 'subject', 'setup', 'action', 'result', 'lesson'],
    optional: ['icon', 'iconColor', 'defaultStage', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Case study with setup\u2192action\u2192result\u2192lesson sections; expand each to drill in.',
    propHints: {
      defaultStage: "'setup'|'action'|'result'|'lesson'",
    },
  }),
  createMeta('deflist', {
    family: 'layout',
    dataShapes: ['list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'placeholder', 'footer'],
    interactive: true,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'term', textAliases: ['label', 'name', 'title', 'word'] }],
    blurb: 'Definition/glossary list with live search box to filter terms.',
  }),
  // — new components shipped by the gallery session (metadata they drafted) —
  createMeta('accordion', {
    family: 'layout',
    dataShapes: ['list', 'text'],
    requires: ['title', 'sections'],
    optional: ['icon', 'iconColor', 'defaultOpen', 'multi', 'footer'],
    interactive: true,
    wowWeight: 0.52,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'sections', text: 'label', textAliases: ['title', 'name', 'heading'] }],
    blurb: 'Expandable content sections; click to open and close each one.',
  }),
  createMeta('scansionmark', {
    family: 'layout',
    dataShapes: ['sequence', 'text'],
    requires: ['lines'],
    optional: ['title', 'icon', 'iconColor', 'meter', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Poetry scansion / prosody markup — stress marks (´/˘) above each syllable, foot-divider bars, rhyme letters in the margin under a named meter.',
    propHints: {
      meter: "the named metre, e.g. 'iambic pentameter' | 'trochaic tetrameter'",
      'lines[].syllables[].stress': "'stressed'|'unstressed'",
      'lines[].feet': 'syllable indices where a foot boundary falls, e.g. [2,4,6,8]',
      'lines[].rhyme': "the rhyme-scheme letter, e.g. 'a' | 'b'",
    },
    domains: ['language'],
    intents: ['explain', 'reference'],
  }),
  createMeta('typespec', {
    family: 'layout',
    dataShapes: ['list', 'tabular'],
    requires: ['styles'],
    optional: ['title', 'icon', 'iconColor', 'pairing', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'styles', text: 'name', textAliases: ['role', 'label', 'title'] }],
    blurb:
      'Typography specimen / type-scale sheet — each role rendered at its real size beside spec chips (typeface, weight, size, line-height, tracking), plus an optional font-pairing showcase.',
    propHints: {
      'styles[].sizePx':
        'the font size in px the row renders at, e.g. 40 (display) down to 12 (caption)',
      'styles[].weight': 'CSS font-weight, e.g. 400 | 600 | 700',
      'styles[].tracking': "letter-spacing as a CSS length, e.g. '-0.02em'",
      pairing: '{ heading, body } — two font-family names to showcase together',
    },
    domains: ['design'],
    intents: ['reference', 'explain'],
  }),
  createMeta('shotlist', {
    family: 'layout',
    dataShapes: ['sequence', 'list'],
    requires: ['shots'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'shots', text: 'action', textAliases: ['description', 'desc', 'text'] }],
    blurb:
      'Film / video shot breakdown — one row per shot with a framed thumbnail showing the shot size, plus movement / lens / duration and the action + dialogue line.',
    propHints: {
      'shots[].n': 'the shot number, in sequence',
      'shots[].size':
        "'WS'|'MS'|'CU'|'ECU'|'OTS' (wide / medium / close-up / extreme close-up / over-the-shoulder)",
      'shots[].movement': "camera move, e.g. 'Slow push-in' | 'Static' | 'Handheld pan'",
      'shots[].lens': "the lens, e.g. '24mm' | '85mm'",
      'shots[].duration': "on-screen length, e.g. '4s'",
    },
    domains: ['media'],
    intents: ['plan', 'reference'],
  }),
  createMeta('beatsheet', {
    family: 'layout',
    dataShapes: ['sequence', 'list'],
    requires: ['beats'],
    optional: ['title', 'icon', 'iconColor', 'framework', 'tension', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'beats', text: 'name', textAliases: ['beat', 'label', 'title'] }],
    blurb:
      'Narrative-structure beat sheet — beats laid along the story with name, position, and a one-liner, under an optional dramatic-tension curve.',
    propHints: {
      framework: "the structure model, e.g. 'Save the Cat' | '3-act' | 'hero journey'",
      'beats[].at': "where the beat falls — a page or percent, e.g. '12' | '50%' | 'p.45'",
      'beats[].line': 'a one-line description of the beat',
      tension:
        'one number per beat (any scale) — plotted as the tension curve, e.g. [1,2,3,5,4,6,8,5]',
    },
    domains: ['writing', 'media'],
    intents: ['plan', 'explain', 'reference'],
  }),
  createMeta('promptset', {
    family: 'layout',
    dataShapes: ['list', 'text'],
    requires: ['prompts'],
    optional: ['title', 'icon', 'iconColor', 'theme', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'prompts', text: 'question', textAliases: ['prompt', 'q', 'text'] }],
    blurb:
      'A calm, low-chrome set of open reflection / journaling prompts — each an open question with a gentle one-line guidance, grouped under an optional theme. An invitation to think, not a checklist or a quiz (no checkboxes, no scores). For gratitude, evening wind-down, or working through a feeling on paper.',
    propHints: {
      theme: "an optional theme the prompts gather under, e.g. 'Evening wind-down'",
      'prompts[].question': 'the open question to sit with — never yes/no, never a task',
      'prompts[].guidance': "a gentle line on how to approach it, e.g. 'no need to be profound'",
    },
    domains: ['relationship', 'productivity'],
    intents: ['reflect'],
  }),
  createMeta('zoneladder', {
    family: 'layout',
    dataShapes: ['status', 'list'],
    requires: ['zones'],
    optional: ['title', 'icon', 'iconColor', 'metric', 'current', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'zones', text: 'name', textAliases: ['zone', 'label'] }],
    blurb:
      'A training intensity-zone ladder — stacked bands from Zone 1 (easy, bottom) to the hardest (top) on a cool→hot ramp, each with its range, felt-effort, and what it trains, plus a computed "you are here" marker on the current zone. For explaining HR / pace / RPE zones.',
    propHints: {
      metric: "'HR'|'pace'|'RPE' — what the ranges are measured in",
      'zones[].range':
        "the measured range for the metric, e.g. '133–151 bpm' | '5:30–6:00 /km' | 'RPE 4–5'",
      'zones[].effort': "the felt effort, e.g. 'Comfortable, can hold a conversation'",
      'zones[].purpose': "what training in this zone builds, e.g. 'Aerobic base & fat metabolism'",
      current: '0-based index of the zone the athlete is currently in (drives the marker)',
    },
    domains: ['fitness', 'health'],
    intents: ['explain', 'reference'],
  }),
  createMeta('picturesequence', {
    family: 'layout',
    dataShapes: ['sequence', 'list'],
    requires: ['panels'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'panels', text: 'label', textAliases: ['step', 'text', 'title'] }],
    blurb:
      'An order-the-events picture strip — 3–6 illustrated panels left→right with first / then / next / last markers and arrows between them, each a small placeholder with a caption. For early-language sequencing and simple how-to steps; the marker word is derived from position when omitted.',
    propHints: {
      'panels[].label': "the short step label, e.g. 'Get the bread'",
      'panels[].marker': "'first'|'then'|'next'|'last' — derived from position if omitted",
      'panels[].caption': 'an optional one-line caption under the panel',
    },
    domains: ['language', 'education'],
    intents: ['explain', 'howto'],
  }),
  createMeta('storyarc', {
    family: 'layout',
    dataShapes: ['sequence'],
    requires: ['framework'],
    optional: ['title', 'icon', 'iconColor', 'beats', 'caption', 'footer'],
    wowWeight: 0.81,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      "Renders a named narrative framework as its canonical visual shape with labeled stages and optional beat pins: Freytag pyramid (exposition→rising→climax→falling→dénouement), three-act, Hero's Journey (12 stages), Save the Cat (15 beats). Supplied beats are pinned to their stage.",
    propHints: {
      framework: '"freytag" | "threeact" | "herojourney" | "savethecat"',
      'beats[].stage': 'stage name matching a canonical stage in the chosen framework',
      'beats[].label': 'short label for this beat pin (a scene title, plot event, etc.)',
      'beats[].note': 'optional one-line note about this beat',
    },
    intents: ['plan', 'explain', 'reference'],
    domains: ['writing', 'media', 'education'],
  }),
  createMeta('devicemark', {
    family: 'layout',
    dataShapes: ['text'],
    requires: ['text', 'marks'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    wowWeight: 0.79,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A text passage with rhetorical/literary device spans highlighted and colour-coded by device class (metaphor, simile, alliteration, irony, anaphora, hyperbole, personification, allusion, parallelism, antithesis, oxymoron, …), with a legend. Use for AP-English/IB analysis, debate rhetoric, speechwriting tuition.',
    propHints: {
      text: 'the full passage text to annotate',
      'marks[].phrase': 'exact phrase in the passage to highlight (case-insensitive match)',
      'marks[].device':
        '"metaphor"|"simile"|"alliteration"|"irony"|"anaphora"|"hyperbole"|"personification"|"allusion"|"parallelism"|"antithesis"|"oxymoron"|"repetition"|"chiasmus"|"assonance"|"other"',
      'marks[].note': 'optional explanation of why this phrase exemplifies the device',
    },
    intents: ['explain', 'teach', 'analyze'],
    domains: ['writing', 'media', 'education'],
  }),
  createMeta('thoughtrecord', {
    family: 'layout',
    dataShapes: ['text', 'comparison'],
    requires: ['situation', 'automaticThought', 'emotion'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'emotionIntensity',
      'evidenceFor',
      'evidenceAgainst',
      'alternativeThought',
      'outcomeEmotion',
      'outcomeIntensity',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A full CBT thought record: the triggering situation, the automatic thought and how it felt, evidence weighed for and against it, then the balanced thought and how the feeling shifted. For working through ONE stuck thought step by step; reframecard is the lighter single-shift version with no evidence-weighing, and proscons weighs a decision, not a belief.',
    propHints: {
      situation: 'the trigger, in plain words — where/when the thought showed up',
      automaticThought: 'the thought as close to verbatim as possible',
      emotion: 'the felt emotion in one or two words, e.g. "Anxious", "Ashamed"',
      emotionIntensity: '0–100, how strong it felt at the time (the standard CBT scale)',
      evidenceFor: 'a few facts that seem to support the automatic thought',
      evidenceAgainst: 'a few facts that complicate or contradict it',
      alternativeThought: 'the balanced thought that weighs both columns honestly',
      outcomeEmotion: 'the emotion after weighing the evidence, if it shifted from `emotion`',
      outcomeIntensity: '0–100, the intensity after the reframe',
    },
    intents: ['comfort', 'reflect'],
  }),
];
