// Catalog entries for the `media` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_MEDIA: ComponentCatalog = [
  // — media —
  createMeta('beforeafter', {
    family: 'media',
    dataShapes: ['comparison'],
    requires: ['title', 'before', 'after'],
    optional: ['icon', 'iconColor', 'position', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Draggable wipe between two REAL before/after photos (renovation, edit, repair, restoration, seasonal or satellite imagery). Each side needs a real image src — gradients alone are not an answer. Do NOT use for abstract concepts, data, or math: use a chart, labeled diagram, or vectorspace instead.',
    propHints: {
      'before.src':
        'URL of the real BEFORE photo (required — without a real image this block is meaningless)',
      'after.src': 'URL of the real AFTER photo (required)',
    },
    intents: ['compare'],
    domains: ['photo', 'home', 'design', 'media'],
  }),
  createMeta('carousel', {
    family: 'media',
    dataShapes: ['sequence', 'media'],
    requires: ['title', 'slides'],
    optional: ['icon', 'iconColor', 'start', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Tap-through gallery of REAL images/slides with captions. Each slide needs a real image src; not a placeholder for abstract or data content.',
  }),
  createMeta('imagecallouts', {
    family: 'media',
    dataShapes: ['media', 'relationship'],
    requires: ['title', 'image', 'callouts'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Annotated image with tappable hotspots revealing labels and details.',
  }),
  createMeta('waveform', {
    family: 'media',
    dataShapes: ['series', 'media'],
    requires: ['title', 'bars'],
    optional: ['icon', 'iconColor', 'durationLabel', 'color', 'position', 'markers', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Interactive audio timeline with bar amplitudes, scrubber, and markers.',
  }),
  createMeta('videoembed', {
    family: 'media',
    dataShapes: ['media', 'sequence'],
    requires: ['title', 'thumb', 'chapters'],
    optional: ['icon', 'iconColor', 'durationLabel', 'active', 'footer'],
    interactive: true,
    wowWeight: 0.85,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'custom',
    blurb: 'Video player with chapter markers and chapter-list navigation.',
  }),
  createMeta('geomap', {
    family: 'media',
    dataShapes: ['geo'],
    requires: ['title', 'markers'],
    optional: ['icon', 'iconColor', 'zoom', 'zones', 'footer'],
    interactive: true,
    // Interactive when live (drag/zoom), but a real map is a meaningful STATIC figure in an export
    // — its tiles are CORS-enabled (crossOrigin set in GeoMap), so it rasterizes cleanly. The
    // explicit override opts this one interactive block into the figure path.
    embed: 'fluid',
    wowWeight: 0.92,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'zones', text: 'label', textAliases: ['name', 'title'] }],
    blurb:
      'A REAL interactive map (OpenStreetMap tiles) for actual places. Give each marker real {lat, lng} coordinates (decimal degrees), a name, and an optional detail. When the answer spans several places or segments (a multi-day trip, a multi-stop route), emit ONE map PER segment — each plotting that segment’s own stops — not a single overview, unless an overview is what was asked. The card lists every marker by name beside the map, numbered to its pin, so `detail` is where a street address or a one-line note belongs — it is rendered, not hidden. This is the only map type — always use it for any real-world location. For a zoning/land-use ask specifically, prefer zoningmap, which teaches the zone-polygon shape more directly.',
    propHints: {
      'zones[].coords':
        'the zone boundary as real [lat, lng] pairs (decimal degrees), at least 3 points',
      'zones[].category': "'residential'|'commercial'|'industrial'|'mixed'|'open-space'",
    },
  }),
  createMeta('lightbox', {
    family: 'media',
    dataShapes: ['media'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Inline gallery grid with full-screen lightbox on tap.',
  }),
  createMeta('moodboard', {
    family: 'media',
    dataShapes: ['media', 'composition'],
    requires: ['title', 'tiles'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.88,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Masonry layout of images, color swatches, and text blocks.',
    propHints: {
      'tiles[].kind': "'image'|'color'|'text'",
    },
  }),
  createMeta('palette', {
    family: 'media',
    dataShapes: ['composition', 'keyvalue'],
    requires: ['title', 'swatches'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [{ prop: 'swatches', text: 'name', textAliases: ['label', 'title'] }],
    blurb:
      'An actual COLOR palette — swatches with hex codes and WCAG contrast verdicts (brand/design palettes). Never as a generic category, tag, or option list — use chipset or badgeset.',
  }),
  createMeta('mediacard', {
    family: 'media',
    dataShapes: ['keyvalue', 'text'],
    requires: ['title', 'cover'],
    optional: [
      'icon',
      'iconColor',
      'year',
      'runtime',
      'rating',
      'score',
      'genres',
      'logline',
      'providers',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A poster-forward detail card for ONE recommended title (film/show/book/game): cover art, year/runtime/rating chips, a 0–100 score badge, a spoiler-safe logline, genre tags, and "where to watch" provider chips. Give a real cover.src when you have one; otherwise it falls back to the cover.from/to gradient. Pick this for a single "what should I watch/read next" pick — use carousel or lightbox for a gallery of several.',
    propHints: {
      score: 'a number 0–100 (aggregate/critic score); omit if unknown rather than guessing',
      'cover.src': 'real poster/cover image URL; omit to show the from/to gradient placeholder',
      'cover.from': 'gradient start, e.g. var(--presence-deep)',
      'cover.to': 'gradient end, e.g. var(--presence-soft)',
    },
    intents: ['decide', 'reference'],
    domains: ['media'],
    stringItems: ['genres', 'providers'],
  }),
  createMeta('diagram', {
    family: 'media',
    dataShapes: ['relationship', 'hierarchy'],
    requires: ['title', 'shapes', 'labels'],
    optional: ['icon', 'iconColor', 'ratio', 'footer'],
    tier: 'frontier',
    wowWeight: 0.8,
    blurb:
      'Labeled vector diagram with shapes (circles, rects, lines, polygons, paths) and annotated callout labels—for anatomy, physics, geography, engineering schematics.',
    colDefault: 8,
    coercer: 'generic',
    propHints: {
      'shapes[].kind': "'circle'|'rect'|'line'|'polygon'|'path'",
    },
  }),
  createMeta('svgblock', {
    family: 'media',
    dataShapes: ['relationship', 'hierarchy', 'text', 'media'],
    requires: ['title', 'svg'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    tier: 'frontier',
    // Lower than native components — use only when no purpose-built block fits.
    wowWeight: 0.42,
    blurb:
      'Tier-3 escape hatch: model-drawn SVG for a visual no native component covers (a molecule, ' +
      'a circuit, a geometric figure, a custom infographic). Strictly sanitized on render; design ' +
      'tokens (var(--presence) etc.) work via CSS inheritance, so it is light/dark-aware. Use ONLY ' +
      'when diagram/geometrycanvas/vectorspace/reactionmechanism/molecularstructure/etc. do not apply.',
    colDefault: 8,
    coercer: 'generic',
    propHints: {
      svg:
        'Complete <svg> with a viewBox (e.g. viewBox="0 0 400 300") and NO width/height attributes. ' +
        'Colors: ONLY var(--presence/--insight/--warning/--danger/--text-primary/--text-secondary/' +
        '--text-muted/--surface-card) — never hex. Allowed elements: path, rect, circle, ellipse, ' +
        'line, polyline, polygon, text, tspan, g, defs, linearGradient/radialGradient/stop, clipPath, ' +
        'mask, pattern, marker, use(#id). Forbidden: script, style, foreignObject, image, a, event ' +
        'handlers, animation, and any external/javascript:/data: URL — all are stripped on render.',
      caption: 'Optional plain-text label shown below the SVG.',
    },
  }),
  // media — sports + architecture
  createMeta('sportspitch', {
    family: 'media',
    dataShapes: ['media', 'tabular'],
    requires: ['title', 'sport'],
    optional: ['icon', 'iconColor', 'positions', 'plays', 'footer'],
    interactive: false,
    wowWeight: 0.88,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A REAL sports field/court (soccer, basketball, football, tennis, baseball) with player positions and play arrows — for formations, tactics, and play diagrams ONLY. Never for anatomy, muscle groups, exercises, or abstract "zones": use bodymap for muscles/anatomy and diagram for a labeled figure.',
    propHints: {
      sport: '"soccer"|"basketball"|"football"|"tennis"|"baseball"',
      'positions[].x': '0=left, 100=right',
      'positions[].y': '0=top, 100=bottom',
      'plays[].kind': '"pass"|"run"|"shot"',
    },
  }),
  createMeta('floorplan', {
    family: 'media',
    dataShapes: ['media', 'tabular'],
    requires: ['title', 'rooms'],
    optional: ['icon', 'iconColor', 'scale', 'footer'],
    interactive: false,
    wowWeight: 0.85,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A top-down floor plan from declarative room data — each room as a labeled rectangle. Use for apartment layouts, office design, or space-planning asks.',
    itemShapes: [{ prop: 'rooms', text: 'name', textAliases: ['room', 'space', 'area'] }],
    propHints: {
      'rooms[].x': '0..100 canvas units from left',
      'rooms[].y': '0..100 canvas units from top',
      'rooms[].w': 'width in canvas units (total 100)',
      'rooms[].h': 'height in canvas units (total 100)',
    },
  }),
  createMeta('dimensiondrawing', {
    family: 'media',
    dataShapes: ['relationship', 'tabular'],
    requires: ['outline', 'dimensions'],
    optional: ['title', 'icon', 'iconColor', 'tolerance', 'titleBlock', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A technical/shop drawing: a part profile drawn to scale with proper dimension lines (extension lines, arrowheads, measurement text), an optional tolerance note, and a small title block. For mechanical parts, machining callouts, and engineering drawings.',
    domains: ['design', 'tech'],
    intents: ['explain', 'reference'],
    itemShapes: [{ prop: 'dimensions', text: 'label' }],
    propHints: {
      'outline[]':
        '{ x, y } points of the closed part profile, in arbitrary drawing units (auto-fit to the frame)',
      'dimensions[].from': '[x, y] start of the measured span (drawing units)',
      'dimensions[].to': '[x, y] end of the measured span (drawing units)',
      'dimensions[].label': 'the measurement text, e.g. "60" or "Ø12"',
      'dimensions[].offset':
        'how far the dimension line sits off the part (drawing units, default 10)',
      titleBlock: '{ part?, scale?, units? } small title-block fields',
    },
  }),
  createMeta('explodedview', {
    family: 'media',
    dataShapes: ['hierarchy', 'sequence', 'tabular'],
    requires: ['parts'],
    optional: ['title', 'icon', 'iconColor', 'axis', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb:
      'An exploded assembly diagram: part shapes separated along an axis with dashed centerlines and numbered balloon callouts, beside a numbered parts list (n · name · ×qty). For assembly steps, parts breakdowns, and how-it-fits-together asks.',
    domains: ['design', 'tech'],
    intents: ['explain', 'howto', 'reference'],
    itemShapes: [{ prop: 'parts', text: 'name', textAliases: ['part', 'label', 'component'] }],
    propHints: {
      'parts[].n': 'callout number (1-based), matching the balloon on the figure',
      'parts[].name': 'part name shown in the list',
      'parts[].qty': 'quantity in the assembly (default 1)',
      axis: "'vertical'|'diagonal'",
    },
  }),
  createMeta('weldsymbol', {
    family: 'media',
    dataShapes: ['relationship', 'keyvalue'],
    requires: ['joint'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'side',
      'size',
      'length',
      'pitch',
      'process',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'cutting',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A welding callout: the joint cross-section AND the AWS weld symbol (reference line, arrow, weld-type glyph, size + length-pitch, process tail), with a legend explaining each part of the symbol. For weld specs and fabrication drawings.',
    domains: ['design', 'tech'],
    intents: ['explain', 'reference'],
    propHints: {
      joint: "'fillet'|'groove'|'lap'|'butt'|'tee'",
      side: "'arrow'|'other'|'both' (which side of the reference line the weld sits on)",
      size: 'weld size, e.g. "6" (mm leg/throat)',
      length: 'weld length, e.g. "50"',
      pitch: 'centre-to-centre pitch for intermittent welds, e.g. "100"',
      process: 'welding process in the tail, e.g. "GMAW"',
    },
  }),
  createMeta('cutlist', {
    family: 'media',
    dataShapes: ['tabular', 'composition'],
    requires: ['stock', 'parts'],
    optional: ['title', 'icon', 'iconColor', 'unit', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A material cut list + nesting layout: a parts table beside a to-scale stock sheet with the parts packed as labeled rectangles, the leftover offcut highlighted, and a computed yield %. For sheet goods (plywood, sheet metal, glass) and woodworking/fabrication cuts.',
    domains: ['design', 'home'],
    intents: ['howto', 'quantify', 'reference'],
    itemShapes: [{ prop: 'parts', text: 'label', textAliases: ['name', 'part'] }],
    propHints: {
      stock: '{ w, h, label? } raw stock sheet size in `unit`',
      'parts[].label': 'part name shown in the table + on the rectangle',
      'parts[].w': 'part width in `unit`',
      'parts[].h': 'part height in `unit`',
      'parts[].qty': 'how many of this part to cut',
      'parts[].x':
        'optional explicit placement from the sheet top-left (give x AND y, else it shelf-packs)',
      'parts[].y': 'optional explicit placement from the sheet top-left',
      unit: 'length unit shown in the table + scale, e.g. "mm" (default "mm")',
    },
  }),
  createMeta('spacefit', {
    family: 'media',
    dataShapes: ['media', 'tabular', 'composition'],
    requires: ['room', 'items'],
    optional: ['title', 'icon', 'iconColor', 'clearances', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A to-scale top-down room layout with furniture: the room drawn to scale with furniture rectangles placed and rotated inside, a scale ruler, and called-out walkway/clearance gaps (a gap below a comfortable threshold is flagged). For room planning, furniture fit, and “will it fit” asks.',
    domains: ['home', 'design'],
    intents: ['plan', 'decide', 'quantify'],
    itemShapes: [
      { prop: 'items', text: 'label', textAliases: ['name', 'item'] },
      { prop: 'clearances', text: 'label' },
    ],
    propHints: {
      room: '{ w, d, unit? } room footprint (width × depth) in `unit` (default "m")',
      'items[].label': 'furniture name shown on the piece',
      'items[].w': 'footprint width in `unit` (before rotation)',
      'items[].d': 'footprint depth in `unit` (before rotation)',
      'items[].x': 'left edge in `unit` from the room top-left',
      'items[].y': 'top edge in `unit` from the room top-left',
      'items[].rot': 'rotation in degrees clockwise (default 0; 90 swaps width/depth)',
      'clearances[].label': 'name of the walkway/gap, e.g. "Sofa to table"',
      'clearances[].gap': 'the gap distance in `unit` (a gap ≤ 0.9 is flagged as tight)',
    },
  }),
  createMeta('anatomyfigure', {
    family: 'media',
    dataShapes: ['media', 'relationship'],
    requires: ['organ', 'pins'],
    optional: ['title', 'icon', 'iconColor', 'view', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.82,
    tier: 'cutting',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A labeled anatomy figure: a clean built-in illustration of a named organ with numbered callout pins placed at 0–100 x/y points, each pin revealing a label + note. For "label the parts of …" anatomy/physiology asks — no image needed.',
    domains: ['health', 'science'],
    intents: ['explain', 'locate', 'reference'],
    itemShapes: [{ prop: 'pins', text: 'label', textAliases: ['name', 'part'] }],
    propHints: {
      organ:
        "'heart'|'kidney'|'nephron'|'brain'|'lung'|'eye'|'ear'|'neuron'|'skeleton'|'stomach'|'liver'",
      'pins[].x': 'horizontal anchor on the figure, 0–100 of the viewBox',
      'pins[].y': 'vertical anchor on the figure, 0–100 of the viewBox',
      'pins[].label': 'the part name shown in the numbered list',
      'pins[].note': 'a short clarifying detail revealed when the pin is active',
      view: 'a short view descriptor, e.g. "anterior" / "coronal section"',
    },
  }),
  createMeta('exposuretriangle', {
    family: 'media',
    dataShapes: ['relationship', 'keyvalue'],
    requires: ['aperture', 'shutter', 'iso'],
    optional: ['title', 'icon', 'iconColor', 'ev', 'effects', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'The photography exposure triangle: aperture, shutter, and ISO wired on a triangle with the resulting exposure in the centre and the trade-off each setting makes (depth of field / motion / noise). For camera-settings explanations and exposure decisions.',
    domains: ['photo', 'media'],
    intents: ['explain', 'decide'],
    propHints: {
      aperture: 'aperture setting, e.g. "f/2.8"',
      shutter: 'shutter speed, e.g. "1/250"',
      iso: 'ISO sensitivity as a number, e.g. 200',
      ev: 'the resulting exposure value, e.g. "EV 12"',
      'effects[].axis': "'aperture'|'shutter'|'iso'",
      'effects[].note': 'the side-effect cue for that corner, e.g. "shallow depth of field"',
    },
  }),
  createMeta('colorwheel', {
    family: 'media',
    dataShapes: ['composition', 'relationship'],
    requires: ['baseHue'],
    optional: ['title', 'icon', 'iconColor', 'harmony', 'swatches', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A color-theory wheel: a hue ring with the harmony geometry (complementary / analogous / triad / split / tetrad) drawn from a base hue, beside a swatch row of the resulting colors + hex. Related hues are derived from baseHue + harmony when swatches are omitted. For color schemes and palette theory.',
    domains: ['design', 'art'],
    intents: ['explain', 'reference'],
    itemShapes: [{ prop: 'swatches', text: 'role' }],
    propHints: {
      baseHue: 'the base hue angle, 0–360',
      harmony: "'complementary'|'analogous'|'triad'|'split'|'tetrad'",
      'swatches[].hue': 'hue angle 0–360 on the wheel',
      'swatches[].hex': 'the rendered color as a hex string, e.g. "#3b82f6"',
      'swatches[].role': 'role label, e.g. "base" / "accent"',
    },
  }),
  createMeta('artanalysis', {
    family: 'media',
    dataShapes: ['media', 'composition'],
    requires: ['overlay'],
    optional: ['title', 'icon', 'iconColor', 'regions', 'palette', 'notes', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A composition / art-technique breakdown over an abstract canvas (no image): the chosen compositional overlay (rule-of-thirds grid / leading lines / golden spiral / symmetry), labeled focal regions, a dominant-palette row, and technique/light/style notes. For analysing composition and visual technique.',
    domains: ['art', 'design'],
    intents: ['explain', 'reference'],
    itemShapes: [
      { prop: 'regions', text: 'label' },
      { prop: 'notes', text: 'text' },
    ],
    propHints: {
      overlay: "'thirds'|'leadinglines'|'goldenratio'|'symmetry'",
      'regions[].x': 'left edge 0–100 of the canvas',
      'regions[].y': 'top edge 0–100 of the canvas',
      'regions[].w': 'width 0–100 of the canvas',
      'regions[].h': 'height 0–100 of the canvas',
      'regions[].label': 'focal-region label, e.g. "subject"',
      'palette[].hex': 'dominant color as a hex string',
      'palette[].role': 'role label, e.g. "highlight" / "shadow"',
      'notes[].label': 'note heading, e.g. "Light" / "Composition"',
      'notes[].text': 'the technique observation',
    },
  }),
  createMeta('mixerboard', {
    family: 'media',
    dataShapes: ['sequence', 'tabular', 'media'],
    requires: ['tracks'],
    optional: ['title', 'icon', 'iconColor', 'bars', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A multitrack DAW / mixer view: stacked labeled track lanes on a shared bar timeline, with clip blocks positioned by start + length, plus a per-lane volume bar, pan indicator, and mute/solo state. For song arrangements, mixing sessions, and "how the tracks are laid out" asks.',
    domains: ['music', 'media'],
    intents: ['explain', 'reference'],
    itemShapes: [{ prop: 'tracks', text: 'name' }],
    propHints: {
      'tracks[].name': 'the track name, e.g. "Drums"',
      'tracks[].clips': '[{ start, len, label? }] clips positioned along the bar timeline',
      'tracks[].volume': 'fader level 0–100 (default 80)',
      'tracks[].pan': 'stereo pan -100 (L) .. 100 (R), 0 = centre',
      'tracks[].mute': 'true → the lane is muted (dimmed, M badge)',
      'tracks[].solo': 'true → the lane is soloed (accented, S badge)',
      'tracks[].color': 'var(--presence)|var(--insight)|var(--warning)',
      bars: 'total bars on the timeline; defaults to the furthest clip end (min 4)',
    },
  }),
  createMeta('wireframe', {
    family: 'media',
    dataShapes: ['structure'],
    requires: ['regions'],
    optional: ['title', 'icon', 'iconColor', 'cols', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A low-fidelity single-page wireframe — placeholder regions (header, hero, cards, CTA, footer) sketched on a column grid.',
    intents: ['plan', 'draft', 'reference'],
    domains: ['design'],
    itemShapes: [
      {
        prop: 'regions',
        text: 'label',
        textAliases: ['name', 'title'],
      },
    ],
    propHints: {
      'regions[].kind':
        "'header'|'hero'|'nav'|'image'|'text'|'button'|'card'|'list'|'footer'|'input'",
      'regions[].col': '1..12 columns this region spans (defaults per kind)',
      'regions[].rows': '1..6 grid rows tall (defaults per kind)',
      cols: 'columns in the layout grid (default 12)',
      iconColor: 'var(--presence-soft)|var(--insight)|var(--text-muted)',
    },
  }),
  createMeta('maproute', {
    family: 'media',
    dataShapes: ['geo', 'sequence'],
    requires: ['waypoints'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'center',
      'zoom',
      'distanceKm',
      'elevationGainM',
      'caption',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A REAL interactive map (OpenStreetMap tiles) with an ORDERED route: the waypoints connect into a numbered polyline, beside a stop-by-stop itinerary and a distance/elevation summary. Give each waypoint real {lat, lng} (decimal degrees) + a label, in travel order, plus an optional {leg} string (e.g. "1.2 km · 15 min") for the leg into that stop. Use for a walking tour, a hike, or one driving leg — when the answer is a single connected path between stops, not scattered pins (use geomap for unordered places).',
    domains: ['travel', 'nature'],
    intents: ['plan', 'locate', 'reference'],
    itemShapes: [{ prop: 'waypoints', text: 'label', textAliases: ['name', 'stop', 'place'] }],
    propHints: {
      'waypoints[].lat': 'real latitude in decimal degrees (-90..90)',
      'waypoints[].lng': 'real longitude in decimal degrees (-180..180)',
      'waypoints[].label': 'the stop name shown on the marker + itinerary',
      'waypoints[].leg': 'the leg INTO this stop, e.g. "1.2 km · 15 min"',
      center: 'optional map centre [lat, lng] (the route auto-fits regardless)',
      distanceKm: 'total route distance in kilometres (a number)',
      elevationGainM: 'total elevation gain in metres (a number)',
    },
  }),
  createMeta('moonphase', {
    family: 'media',
    dataShapes: ['scalar', 'status'],
    requires: ['illumination'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'waxing',
      'phaseName',
      'date',
      'upcoming',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      "A lunar-phase disk: an SVG Moon whose lit shape (the terminator) is COMPUTED from the illuminated fraction, beside the phase name, % illuminated, and an optional strip of upcoming nights. Give illumination as 0..1 and waxing true (lit on the right, growing) / false (lit on the left, shrinking). Use for tonight's phase, a stargazing plan, or a moon-phase explainer.",
    domains: ['nature', 'science'],
    intents: ['explain', 'reference'],
    propHints: {
      illumination: 'illuminated fraction of the disk, 0..1 (0.72 = 72%)',
      waxing: 'true = waxing (lit on the right, growing); false = waning (lit on the left)',
      phaseName: "the phase name, e.g. 'Waxing Gibbous'",
      date: 'the date this phase is for, e.g. "Jun 20, 2026"',
      'upcoming[].date': 'a short night label, e.g. "Fri 21"',
      'upcoming[].illumination': "that night's illuminated fraction, 0..1",
    },
  }),
  createMeta('skychart', {
    family: 'media',
    dataShapes: ['geo', 'relationship'],
    requires: ['stars'],
    optional: ['title', 'icon', 'iconColor', 'constellations', 'planets', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 7,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A circular planisphere night-sky chart: a sky dome (the horizon ring) with stars plotted at x/y (each 0..1 within the dome) and sized by magnitude, constellation connect-the-dots over them, and labeled planets. Use for "what\'s in the sky tonight", a constellation guide, or a star-chart explainer. Place stars by their relative position in the field, not RA/Dec.',
    domains: ['nature', 'science'],
    intents: ['locate', 'reference'],
    itemShapes: [{ prop: 'planets', text: 'name' }],
    propHints: {
      'stars[].x': 'horizontal position within the dome, 0..1 (0 = west, 1 = east)',
      'stars[].y': 'vertical position within the dome, 0..1 (0 = north, 1 = south)',
      'stars[].mag':
        'apparent magnitude — LOWER is brighter (drives dot size); e.g. 0 bright, 4 faint',
      'stars[].name': 'star name, shown as a label when notable',
      'constellations[].name': 'the constellation/asterism name',
      'constellations[].lines':
        'connect-the-dots segments as [fromStarIndex, toStarIndex] into stars[]',
      'planets[].x': 'horizontal position within the dome, 0..1',
      'planets[].y': 'vertical position within the dome, 0..1',
    },
  }),
  createMeta('orbitdiagram', {
    family: 'media',
    dataShapes: ['relationship', 'composition'],
    requires: ['center', 'bodies'],
    optional: ['title', 'icon', 'iconColor', 'toScale', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 7,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A scaled orbital/celestial-system diagram: a central body with concentric labeled orbit rings, a sized body on each ring, and distance/period annotations. The ring radii + body positions are computed from orbitRadius (sqrt-compressed so inner + outer both fit, unless toScale). Use for a planetary system, moons around a planet, or a star system — give each body its orbitRadius in consistent units (e.g. AU).',
    domains: ['science', 'nature'],
    intents: ['explain', 'reference'],
    itemShapes: [{ prop: 'bodies', text: 'name', textAliases: ['body', 'planet', 'moon'] }],
    propHints: {
      center: "the central body name, e.g. 'Sun'",
      'bodies[].orbitRadius':
        'orbit radius in consistent units (e.g. AU); normalized across all bodies',
      'bodies[].size': 'relative body draw size, 1..5 (optional)',
      'bodies[].color': 'body accent, e.g. var(--insight)',
      'bodies[].period': "orbital period annotation, e.g. '365 days'",
      'bodies[].distance': "distance annotation, e.g. '1.0 AU'",
      toScale: 'true = keep orbit radii linearly to scale; default false (sqrt-compressed to fit)',
    },
  }),
  createMeta('gameboard', {
    family: 'media',
    dataShapes: ['media', 'relationship', 'tabular'],
    requires: ['board', 'pieces'],
    optional: ['title', 'icon', 'iconColor', 'size', 'highlights', 'moves', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A configurable abstract game board: an 8×8 chess/checkers grid (alternating squares), a 19×19 Go board (stones on intersections), a hex grid, or a plain grid — with pieces placed on cells (a glyph or short label, tinted by side), highlighted squares, and move arrows. For openings, puzzles, tactics, and positional asks.',
    domains: ['sports'],
    intents: ['explain', 'reference'],
    propHints: {
      board: "'chess'|'checkers'|'go'|'hex'|'grid' (default 'chess')",
      size: 'grid dimension per side (default: chess/checkers 8, go 19, hex/grid 8)',
      'pieces[].row': '0-based row index from the top',
      'pieces[].col': '0-based column index from the left',
      'pieces[].glyph':
        'a single glyph drawn on the piece (a chess figurine ♞, a stone) — wins over label',
      'pieces[].label': 'a short text label on the piece (e.g. "X")',
      'pieces[].side': "'a' (light) | 'b' (dark) — tints the piece",
      'highlights[]': '{ row, col } squares to highlight',
      'moves[].from': '[row, col] origin cell',
      'moves[].to': '[row, col] destination cell (drawn as an arrow)',
    },
  }),
  createMeta('patternpiece', {
    family: 'media',
    dataShapes: ['media', 'tabular', 'composition'],
    requires: ['fabric', 'pieces'],
    optional: ['title', 'icon', 'iconColor', 'unit', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A sewing-pattern / fabric cutting layout: the fabric rectangle drawn to scale (folded fabric marked) with pattern pieces placed as labeled rectangles, each carrying a grainline arrow and an "on fold" mark, plus a computed yield %. For sewing layouts, fabric estimation, and "how to cut it" asks.',
    domains: ['design', 'home'],
    intents: ['howto', 'reference'],
    itemShapes: [{ prop: 'pieces', text: 'label', textAliases: ['name', 'piece', 'part'] }],
    propHints: {
      fabric: '{ w, h, label? } the fabric size in `unit` (the fold runs down the left edge)',
      'pieces[].label': 'piece name shown in the centre, e.g. "Front panel"',
      'pieces[].w': 'piece width in `unit`',
      'pieces[].h': 'piece height in `unit`',
      'pieces[].x': 'left edge in `unit` from the fabric top-left',
      'pieces[].y': 'top edge in `unit` from the fabric top-left',
      'pieces[].fold':
        'true → the piece’s left edge sits on the fold (drawn as a fold line, cut 1 on fold)',
      'pieces[].qty': 'how many to cut (default 1)',
      unit: 'length unit shown in the scale + yield, e.g. "cm" (default "cm")',
    },
  }),
  createMeta('emotionwheel', {
    family: 'media',
    dataShapes: ['composition', 'relationship'],
    requires: [],
    optional: ['title', 'icon', 'iconColor', 'segments', 'highlight', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    blurb:
      "Plutchik's feeling wheel: named emotions as donut wedges, one ring per intensity tier (primary/secondary/tertiary), with a chosen feeling ring-marked. Defaults to the 8 core emotions (joy, trust, fear, surprise, sadness, disgust, anger, anticipation) when segments are omitted. For naming/mapping feelings, mood check-ins, and emotional-granularity teaching.",
    domains: ['health', 'education', 'psychology'],
    intents: ['explain', 'reflect', 'reference'],
    itemShapes: [{ prop: 'segments', text: 'label' }],
    propHints: {
      'segments[].label': 'the feeling name, e.g. "joy" or "optimism"',
      'segments[].angle':
        'optional explicit centre angle 0–360; auto-spaced within its tier when omitted',
      'segments[].intensity':
        "'primary'|'secondary'|'tertiary' — which ring it sits on (default 'primary')",
      'segments[].color': 'accent token, e.g. var(--warning)',
      highlight: 'label of the segment to ring-mark, e.g. "trust"',
    },
  }),
  // — media additions: marketing/brand/property —
  createMeta('creativetest', {
    family: 'media',
    dataShapes: ['comparison', 'media'],
    requires: ['title', 'variants'],
    optional: ['icon', 'iconColor', 'winner', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'variants',
        text: 'label',
        textAliases: ['name', 'title', 'variant'],
        children: { prop: 'metrics', text: 'label', textAliases: ['name', 'metric', 'key'] },
      },
    ],
    blurb:
      'A marketing A/B creative comparison — real ad/post images side by side, each with a metric row (CTR, conversions, spend…) and the winner ribboned. Each variant needs a real image src. Use for testing ad creative, not a generic product/feature comparison — use compare or comparematrix for that.',
    propHints: {
      'variants[].src':
        'URL of the real creative image (required — without it the block is meaningless)',
      'variants[].metrics[].deltaDir': "'good'|'bad' — which way the delta favors this variant",
      winner: 'index into variants of the winning creative, once the test has concluded',
    },
    intents: ['compare', 'decide'],
    domains: ['business', 'design', 'media'],
  }),
  createMeta('brandguide', {
    family: 'media',
    dataShapes: ['composition', 'keyvalue'],
    requires: ['title', 'colors'],
    optional: ['icon', 'iconColor', 'typography', 'voiceNotes', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [
      { prop: 'colors', text: 'name', textAliases: ['label', 'title'] },
      { prop: 'typography', text: 'name', textAliases: ['role', 'label'] },
    ],
    blurb:
      'A brand identity reference — the color palette, a live type-specimen row per typeface, and short voice/tone notes. Use for a brand/style-guide ask; for a plain color palette alone use palette instead.',
    propHints: {
      'typography[].sample':
        'the font-family CSS stack to preview in, e.g. "\'Georgia\', serif" — a real installed/system font, never a URL',
      'typography[].weight': "e.g. '400' or 'Bold'",
    },
    intents: ['reference', 'explain'],
    domains: ['design', 'business', 'media'],
    stringItems: ['voiceNotes'],
  }),
  createMeta('siteplan', {
    family: 'media',
    dataShapes: ['media', 'tabular'],
    requires: ['title', 'boundary'],
    optional: ['icon', 'iconColor', 'structureFootprint', 'setbackLines', 'easements', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'setbackLines', text: 'label', textAliases: ['name', 'type', 'zone'] },
      { prop: 'easements', text: 'label', textAliases: ['name', 'type'] },
    ],
    blurb:
      'A property boundary plan — the parcel outline, an optional building footprint, dashed setback lines with distance callouts, and hatched easement strips. Distinct from floorplan (interior rooms): use this for a lot/parcel, permit, or zoning-setback ask.',
    propHints: {
      boundary:
        'the parcel outline as [x,y] pairs in any consistent site unit — auto-fit to the frame',
      'setbackLines[].offset':
        'distance inward from the property line, in the same site units as boundary',
      'easements[].path': 'the easement strip outline as [x,y] pairs, same site units as boundary',
    },
    intents: ['reference', 'plan', 'explain'],
    domains: ['home', 'design', 'legal'],
  }),
  createMeta('zoningmap', {
    family: 'media',
    dataShapes: ['geo'],
    requires: ['title', 'markers'],
    optional: ['icon', 'iconColor', 'zoom', 'zones', 'footer'],
    interactive: true,
    embed: 'fluid',
    wowWeight: 0.9,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'zones', text: 'label', textAliases: ['name', 'title'] }],
    blurb:
      "A REAL interactive map with a zoning/land-use overlay: color-filled parcel polygons by category (residential/commercial/industrial/mixed/open-space) plus a legend. Give each zone real {coords: [[lat,lng],…], category, label} and at least one marker for reference. Use for 'is this lot zoned for…' or land-use questions; for a plain location map without zoning use geomap.",
    propHints: {
      'zones[].coords':
        'the zone boundary as real [lat, lng] pairs (decimal degrees), at least 3 points',
      'zones[].category': "'residential'|'commercial'|'industrial'|'mixed'|'open-space'",
    },
    intents: ['reference', 'explain', 'decide'],
    domains: ['home', 'legal', 'travel'],
  }),
  // — media additions: puzzles, cards, craft charts, music sequencing —
  createMeta('wordsearch', {
    family: 'media',
    dataShapes: ['list', 'media'],
    requires: ['words'],
    optional: ['title', 'icon', 'iconColor', 'size', 'seed', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    stringItems: ['words'],
    blurb:
      'A word-search puzzle the component GENERATES itself: supply ONLY the hidden words (plain strings) and it deterministically places them in 8 directions and fills the rest with weighted random letters — never supply a letter grid, it would not contain the words. Clicking a word in the list reveals its placement; a reveal-all shows every answer. Never for arbitrary game boards — use gameboard.',
    propHints: {
      words: 'the hidden words as plain strings (normalized to A–Z uppercase, duplicates dropped)',
      size: 'optional grid side 8–15; default fits the longest word',
      seed: 'optional short string; the same seed + words always builds the same grid',
    },
    intents: ['draft', 'explain', 'reference'],
    domains: ['education', 'media'],
  }),
  createMeta('playingcards', {
    family: 'media',
    dataShapes: ['selection', 'media'],
    requires: ['groups'],
    optional: ['title', 'icon', 'iconColor', 'note', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'groups', children: { prop: 'cards', requiredFields: ['rank', 'suit'] } }],
    blurb:
      'Standard playing cards drawn as crisp SVG — true pip arrangements on number cards, letter + large pip on courts and aces, a patterned back for face-down cards — grouped into labeled hands ("Your hand", "Flop") laid out as a fan, row, or stack. For poker/bridge/blackjack examples, card-game rules, and probability illustrations. Never for board-game positions — use gameboard.',
    propHints: {
      'groups[].label': 'optional group caption, e.g. "Your hand" or "Dealer shows"',
      'groups[].layout': "'fan' | 'row' | 'stack' (default 'row')",
      'groups[].cards[].rank': "'A'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'|'10'|'J'|'Q'|'K'",
      'groups[].cards[].suit': "'spades'|'hearts'|'diamonds'|'clubs'",
      'groups[].cards[].faceDown': 'true → draws the patterned card back instead of the face',
      note: 'optional short annotation under the groups, e.g. the odds being illustrated',
    },
    intents: ['explain', 'reference'],
    domains: ['sports', 'media', 'education'],
  }),
  createMeta('stitchchart', {
    family: 'media',
    dataShapes: ['sequence', 'structure'],
    requires: ['rows'],
    optional: ['title', 'icon', 'iconColor', 'legend', 'gauge', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'legend', text: 'meaning', requiredFields: ['key'] }],
    blurb:
      'A knitting symbol chart read like a real one — bottom-up, RS rows right-to-left with row numbers alternating sides — where each cell draws the standard symbol for its stitch key and an auto-legend explains only the symbols in use. Give rows in knitting order (rows[0] = row 1), each with a stitches array of keys. Never for sewing pattern pieces — use patternpiece.',
    propHints: {
      'rows[].side': "'RS' | 'WS' — defaults RS for odd row numbers, WS for even",
      'rows[].number': 'optional row number; defaults to the bottom-up position',
      'rows[].stitches':
        "stitch keys in knitting order: 'k' knit, 'p' purl, 'yo' yarn over, 'k2tog' right-leaning decrease, 'ssk' left-leaning decrease, 'c4f' cable 4 front, 'c4b' cable 4 back, 'sl' slip, 'bo' bind off, 'co' cast on, 'mb' make bobble",
      'legend[].key': 'the stitch key the meaning belongs to, e.g. "mb"',
      'legend[].meaning': 'optional override/extension of the built-in legend text',
      gauge: 'optional gauge note, e.g. "22 sts × 30 rows = 10 cm in stockinette"',
    },
    intents: ['howto', 'reference'],
    domains: ['home', 'design'],
  }),
  createMeta('pianoroll', {
    family: 'media',
    dataShapes: ['sequence', 'series'],
    requires: ['notes'],
    optional: ['title', 'icon', 'iconColor', 'beatsPerBar', 'tempo', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'notes', requiredFields: ['pitch'] }],
    blurb:
      'A MIDI-style piano roll: a mini keyboard gutter (black-key rows tinted, octave labels), a beat grid with heavier bar lines, and one bar per note placed by start beat, sized by duration, and tinted by velocity. Give each note a pitch ("C4", "F#3", or a MIDI number), a start in beats, and a duration in beats — both axes auto-range from the notes. Never for sheet-music notation — use musicstaff.',
    propHints: {
      'notes[].pitch': 'scientific pitch like "C4" / "F#3" / "Bb2", or a MIDI number 0–127',
      'notes[].start': 'start position in beats, ≥ 0 (0 = the first beat of bar 1)',
      'notes[].duration': 'length in beats, > 0 (0.5 = an eighth note at 4 beats/bar)',
      'notes[].velocity': 'optional 0–1 — drives the bar tint intensity',
      'notes[].label': 'optional text on the bar when it fits; defaults to the note name',
      beatsPerBar: 'beats per bar for the heavy grid lines (default 4)',
      tempo: 'optional tempo label chip, e.g. "96 BPM"',
    },
    intents: ['explain', 'reference'],
    domains: ['music', 'media'],
  }),
];
