// Catalog entries for the `nav` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_NAV: ComponentCatalog = [
  // — nav —
  createMeta('navbar', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'brand', 'links'],
    optional: ['icon', 'iconColor', 'active', 'searchPlaceholder', 'avatar', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'links', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Top app bar with brand, navigational links, search, and user avatar.',
  }),
  createMeta('sidenav', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'groups'],
    optional: ['icon', 'iconColor', 'brand', 'brandIcon', 'active', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 3,
    colMin: 3,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'groups',
        children: { prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    blurb: 'Grouped sidebar navigation with icons, badges, and active state.',
  }),
  createMeta('breadcrumb', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'maxVisible', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.5,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Hierarchical trail with overflow collapse to ellipsis menu.',
  }),
  createMeta('pagination', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'total'],
    optional: ['icon', 'iconColor', 'page', 'siblings', 'unitLabel', 'perPage', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Numbered page selector with first/prev/next/last controls and item summary.',
  }),
  createMeta('menubar', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'menus'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'menus',
        text: 'label',
        textAliases: ['name', 'title'],
        children: { prop: 'entries', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    blurb: 'Application menu bar (File/Edit/View) with multi-column dropdowns.',
  }),
  createMeta('megamenu', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'tabs', 'columns'],
    optional: ['icon', 'iconColor', 'trigger', 'promoTitle', 'promoCopy', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'columns',
        text: 'heading',
        textAliases: ['title', 'label', 'name'],
        children: { prop: 'links', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    blurb: 'Navigation item opening a multi-column mega-panel on hover with optional promo.',
    stringItems: ['tabs'],
  }),
  createMeta('toolbar', {
    family: 'nav',
    dataShapes: ['action'],
    requires: ['title', 'groups'],
    optional: ['icon', 'iconColor', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Formatting toolbar with grouped icon buttons, dividers, and toggle states.',
  }),
  createMeta('commandbar', {
    family: 'nav',
    dataShapes: ['action'],
    requires: ['title', 'actions'],
    optional: ['icon', 'iconColor', 'noun', 'totalItems', 'selected', 'rows', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      { prop: 'rows', text: 'label', textAliases: ['name', 'title', 'text'] },
      { prop: 'actions', text: 'label', textAliases: ['name', 'title', 'text'] },
    ],
    blurb: 'Contextual action bar for bulk operations on selected items with live count.',
  }),
  createMeta('treeview', {
    family: 'nav',
    dataShapes: ['hierarchy'],
    requires: ['title', 'nodes'],
    optional: ['icon', 'iconColor', 'selected', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'cutting',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'File/folder tree with expand/collapse, selection, and recursive nesting.',
  }),
  createMeta('bottomnav', {
    family: 'nav',
    dataShapes: ['navigation'],
    requires: ['title', 'tabs'],
    optional: ['icon', 'iconColor', 'active', 'screens', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.58,
    tier: 'base',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'tabs', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Mobile bottom navigation bar with icons, labels, and active indicator.',
    stringItems: ['screens'],
  }),
];
