// Catalog entries for the `overlays` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_OVERLAYS: ComponentCatalog = [
  // — overlays —
  createMeta('modal', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'heading',
      'body',
      'confirm',
      'cancel',
      'color',
    ],
    interactive: true,
    wowWeight: 0.75,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Centered dialog with title, body, and action buttons; opens on trigger click.',
  }),
  createMeta('confirmdialog', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'heading',
      'body',
      'alertIcon',
      'confirm',
      'cancel',
      'color',
    ],
    interactive: true,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Destructive confirmation dialog with alert styling and danger-colored action.',
  }),
  createMeta('drawer', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'heading',
      'subhead',
      'rows',
      'confirm',
      'cancel',
      'color',
    ],
    interactive: true,
    wowWeight: 0.78,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Right-side drawer with scrollable rows; triggers from button or card.',
  }),
  createMeta('sheet', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'heading',
      'subhead',
      'options',
      'color',
    ],
    interactive: true,
    wowWeight: 0.76,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Bottom sheet with options and selection; mobile-native interaction pattern.',
  }),
  createMeta('popover', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'heading',
      'body',
      'stat',
      'statLabel',
      'action',
      'color',
    ],
    interactive: true,
    wowWeight: 0.74,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Anchored popover with arrow and contextual content; highlights a key stat.',
  }),
  createMeta('hovercard', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'mention',
      'lead',
      'name',
      'handle',
      'bio',
      'avatar',
      'stats',
      'action',
      'color',
    ],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'stats', text: 'value', textAliases: ['val', 'number', 'stat'] }],
    blurb: 'Rich preview card on mention hover; shows profile name, bio, and stats.',
  }),
  createMeta('tooltip', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'prompt', 'targets', 'color'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'targets', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Multiple labeled elements with styled tooltips in configurable placements.',
  }),
  createMeta('menu', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'menuLabel',
      'items',
      'color',
    ],
    interactive: true,
    wowWeight: 0.72,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Dropdown menu with icons, shortcuts, and separators; standard desktop pattern.',
  }),
  createMeta('contextmenu', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'target', 'targetIcon', 'description', 'items', 'color'],
    interactive: true,
    wowWeight: 0.71,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Right-click context menu on a target; shows actions for the selected element.',
  }),
  createMeta('commandk', {
    family: 'overlays',
    dataShapes: ['overlay'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'trigger',
      'triggerIcon',
      'description',
      'placeholder',
      'groups',
      'color',
    ],
    interactive: true,
    wowWeight: 0.85,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'groups',
        text: 'label',
        textAliases: ['name', 'title', 'heading'],
        children: { prop: 'commands', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    blurb: 'Command palette with grouped commands, search, and keyboard navigation.',
  }),
];
