// Catalog entries for the `pickers` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_PICKERS: ComponentCatalog = [
  // — pickers —
  createMeta('datepicker', {
    family: 'pickers',
    dataShapes: ['selection'],
    requires: ['title', 'value'],
    optional: ['label', 'placeholder', 'month', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Field with popover calendar to select a single date.',
  }),
  createMeta('calendarpick', {
    family: 'pickers',
    dataShapes: ['selection', 'status'],
    requires: ['title'],
    optional: ['month', 'value', 'events', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Inline month calendar with event dots and navigation.',
  }),
  createMeta('daterange', {
    family: 'pickers',
    dataShapes: ['selection'],
    requires: ['title'],
    optional: ['month', 'start', 'end', 'presets', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Two-month calendar picker for selecting start and end dates.',
    stringItems: ['presets'],
  }),
  createMeta('timepicker', {
    family: 'pickers',
    dataShapes: ['selection'],
    requires: ['title'],
    optional: [
      'label',
      'format',
      'hour',
      'minute',
      'meridiem',
      'step',
      'icon',
      'iconColor',
      'footer',
      'color',
    ],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Hours and minutes input with steppers and AM/PM toggle.',
  }),
  createMeta('colorpicker', {
    family: 'pickers',
    dataShapes: ['selection'],
    requires: ['title'],
    optional: ['label', 'value', 'swatches', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Swatch grid and hue strip with hex preview.',
  }),
  createMeta('fileupload', {
    family: 'pickers',
    dataShapes: ['selection', 'action'],
    requires: ['title'],
    optional: ['prompt', 'hint', 'files', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'files', text: 'name', textAliases: ['label', 'filename', 'title'] }],
    blurb: 'Drag-drop zone with file list showing name, size, and upload progress.',
    propHints: {
      'files[].kind': "'doc'|'image'|'slides'|'table'|'pdf'|'file'",
    },
  }),
  createMeta('tagsinput', {
    family: 'pickers',
    dataShapes: ['selection', 'list'],
    requires: ['title'],
    optional: [
      'label',
      'tags',
      'placeholder',
      'suggestions',
      'max',
      'icon',
      'iconColor',
      'footer',
      'color',
    ],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Chip input with keyboard entry, suggestions, and removal.',
    stringItems: ['tags', 'suggestions'],
  }),
  createMeta('numberstepper', {
    family: 'pickers',
    dataShapes: ['selection', 'scalar'],
    requires: ['title'],
    optional: [
      'label',
      'value',
      'min',
      'max',
      'step',
      'prefix',
      'suffix',
      'caption',
      'icon',
      'iconColor',
      'footer',
      'color',
    ],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Numeric input with minus/plus buttons and min/max bounds.',
  }),
  createMeta('searchselect', {
    family: 'pickers',
    dataShapes: ['selection'],
    requires: ['title', 'options'],
    optional: ['label', 'placeholder', 'selected', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Searchable dropdown with keyboard navigation and live filtering.',
  }),
  createMeta('formpanel', {
    family: 'pickers',
    dataShapes: ['selection', 'action'],
    requires: ['title', 'fields'],
    optional: ['heading', 'submitLabel', 'success', 'icon', 'iconColor', 'footer', 'color'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Multi-field form with validation, types (text/email/select/textarea), and submit.',
    propHints: {
      'fields[].type': "'text'|'email'|'select'|'textarea'",
    },
  }),
];
