// Catalog entries for the `stats` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_STATS: ComponentCatalog = [
  // — stats —
  createMeta('sparkstat', {
    family: 'stats',
    dataShapes: ['scalar', 'series'],
    requires: ['title', 'value', 'points'],
    optional: ['icon', 'iconColor', 'unit', 'delta', 'deltaDir', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 4,
    coercer: 'generic',
    blurb: 'Big number with inline sparkline showing trend over time.',
  }),
  createMeta('counter', {
    family: 'stats',
    dataShapes: ['scalar'],
    requires: ['title', 'value', 'label'],
    optional: [
      'icon',
      'iconColor',
      'prefix',
      'suffix',
      'decimals',
      'delta',
      'deltaDir',
      'color',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.55,
    tier: 'base',
    colDefault: 4,
    colMin: 3,
    coercer: 'generic',
    blurb: 'Animated count-up to a number with label and delta.',
  }),
  createMeta('herostat', {
    family: 'stats',
    dataShapes: ['scalar'],
    requires: ['title', 'value'],
    optional: [
      'icon',
      'iconColor',
      'unit',
      'narrative',
      'trend',
      'trendDir',
      'detail',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.8,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Extra-large stat with narrative and hoverable trend detail.',
  }),
  createMeta('trendtile', {
    family: 'stats',
    dataShapes: ['scalar', 'series'],
    requires: ['title', 'value', 'delta', 'bars'],
    optional: ['icon', 'iconColor', 'deltaDir', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 4,
    colMin: 3,
    coercer: 'generic',
    blurb: 'Number with arrow, percent delta, and mini sparkbar.',
  }),
  createMeta('scorebadge', {
    family: 'stats',
    dataShapes: ['scalar', 'composition'],
    requires: ['title', 'score'],
    optional: ['icon', 'iconColor', 'grade', 'caption', 'color', 'components', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'base',
    colDefault: 4,
    colMin: 4,
    coercer: 'generic',
    itemShapes: [{ prop: 'components', text: 'label', textAliases: ['name', 'title'] }],
    blurb:
      'A single graded score 0–100 as a circular badge with a letter/grade ring (credit score, health score, quality grade). Never for a plain metric or count — use kpi.',
  }),
  createMeta('percentilebar', {
    family: 'stats',
    dataShapes: ['scalar', 'distribution'],
    requires: ['title', 'percentile', 'value'],
    optional: ['icon', 'iconColor', 'unit', 'lowLabel', 'highLabel', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'A value placed on a distribution by its PERCENTILE RANK — "you are in the top X%" (test scores, benchmarks, growth charts). Never as a plain progress or completion bar — use progressbar or gauge.',
  }),
  createMeta('statpair', {
    family: 'stats',
    dataShapes: ['comparison', 'relationship'],
    requires: ['title', 'left', 'right'],
    optional: ['icon', 'iconColor', 'connector', 'ratioLabel', 'footer'],
    interactive: false,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    blurb: 'Two related numbers with connector and computed ratio.',
  }),
  createMeta('scorecard', {
    family: 'stats',
    dataShapes: ['keyvalue', 'composition'],
    requires: ['title', 'tiles'],
    optional: ['icon', 'iconColor', 'cols', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'tiles', text: 'value', textAliases: ['val', 'stat', 'number'] }],
    blurb: 'Grid of mini stats (icon, value, trend) that lift on hover.',
  }),
  createMeta('deltacascade', {
    family: 'stats',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'prefix', 'suffix', 'footer'],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'steps', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Sequential value changes flowing to a total with hoverable step detail.',
  }),
  createMeta('bulletkpi', {
    family: 'stats',
    dataShapes: ['comparison', 'status'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.65,
    tier: 'base',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Stacked bullet KPIs showing value vs target mini-bars.',
  }),
  // — stats additions (long-tail academic) —
  createMeta('confusionmatrix', {
    family: 'stats',
    dataShapes: ['tabular', 'distribution', 'comparison'],
    requires: ['title', 'classes', 'matrix'],
    optional: [
      'icon',
      'iconColor',
      'correctColor',
      'errorColor',
      'showTotals',
      'readout',
      'actualLabel',
      'predictedLabel',
      'countLabel',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'An N×N confusion matrix: rows are the actual class, columns the predicted class, and each ' +
      'cell a count heat-shaded by its value (the diagonal = correct predictions, off-diagonal = ' +
      'errors). Class labels sit on both axes, with optional row/column totals and a derived ' +
      'read-out (overall accuracy, or a per-class precision/recall table). The standard ' +
      'classifier-evaluation visual; also fits medical test results (TP/FP/FN/TN) and A/B outcome ' +
      'grids. Keeps cells legible from 2×2 up to ~8×8.',
    // `classes` is a bare string[] and `matrix` a number[][]; both must pass through the generic
    // coercer untouched, so no itemShapes (an itemShape with no `text` would drop every string).
    propHints: {
      classes: 'class labels in order; row i = actual class[i], column j = predicted class[j]',
      matrix:
        'square N×N integer counts where matrix[i][j] = samples whose ACTUAL class is i and ' +
        'PREDICTED class is j; the diagonal matrix[i][i] is the correct predictions. Real counts only.',
      correctColor: "heat color for diagonal (correct) cells, e.g. 'var(--presence)' (default)",
      errorColor: "heat color for off-diagonal (error) cells, e.g. 'var(--danger)' (default)",
      readout: "'accuracy' (overall % headline) | 'perclass' (precision/recall table) | 'none'",
      showTotals: 'true to draw a row/column totals strip on the right and bottom edges',
      actualLabel: "y-axis (truth) title, default 'Actual'",
      predictedLabel: "x-axis (model guess) title, default 'Predicted'",
      countLabel: "noun for the accuracy read-out, e.g. 'samples' (default), 'cases', 'emails'",
    },
    intents: ['explain', 'quantify', 'reference', 'teach'],
    domains: ['data', 'science', 'education'],
    stringItems: ['classes'],
  }),
  createMeta('kpidashboard', {
    family: 'stats',
    dataShapes: ['keyvalue', 'series', 'scalar'],
    requires: ['tiles'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'tiles', text: 'label', textAliases: ['name', 'metric', 'title'] }],
    propHints: {
      'tiles[].deltaDir':
        "'up'|'down'|'good' — up/good color positive, down colors negative; use 'good' when a falling value is desirable (e.g. churn down)",
      'tiles[].spark':
        'number[] of raw magnitudes oldest→newest (6–12 points) for the tile sparkline',
    },
    blurb:
      'A grid of executive KPI tiles, each a big value with delta and its own inline sparkline — a one-glance metrics board (MRR, churn, NRR, CAC, runway).',
    domains: ['business', 'data', 'money'],
    intents: ['track', 'quantify'],
  }),
  createMeta('abtestresult', {
    family: 'stats',
    dataShapes: ['comparison', 'distribution'],
    requires: ['title', 'control', 'variant'],
    optional: ['icon', 'iconColor', 'pValue', 'confidenceInterval', 'significant', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 6,
    coercer: 'generic',
    propHints: {
      'control.conversionRate': 'fraction 0..1, e.g. 0.084 = 8.4% — never a 0..100 percentage',
      'variant.conversionRate': 'fraction 0..1, e.g. 0.084 = 8.4% — never a 0..100 percentage',
      confidenceInterval:
        '[low, high] real 95% CI bounds on the relative lift %, same scale as the shown lift (e.g. [9.1, 26.8] for a +18.0% lift) — only pass this when a real interval was computed, never invent one',
      significant:
        'explicit true/false call on statistical significance; omit to let the badge fall back to pValue < 0.05, or omit both for no badge',
    },
    blurb:
      'An A/B experiment readout: control vs. variant conversion rate, computed lift, and — only when supplied — a p-value/CI significance read. Use for a launched test result, never a hypothetical comparison.',
    domains: ['business', 'data', 'science'],
    intents: ['quantify', 'decide', 'track'],
  }),
  createMeta('powersample', {
    family: 'stats',
    dataShapes: ['scalar', 'series'],
    requires: ['effectSize'],
    optional: ['title', 'icon', 'iconColor', 'alpha', 'power', 'requiredN', 'curve', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    propHints: {
      effectSize:
        'standardized effect size (Cohen\'s d) the test should detect, e.g. 0.5 for a "medium" effect — magnitude only, sign is cosmetic',
      alpha: 'two-sided significance level, 0..1 (default 0.05)',
      power:
        'target power to design for, 0..1 (default 0.8) — omit requiredN to have this solved into a sample size',
      requiredN:
        'a caller-already-computed sample size per group; when given it is trusted, and power is read off it instead of solved for',
      curve:
        'real (n, power) points from an actual power analysis, e.g. [{n:200,power:0.42},{n:800,power:0.91}] — plotted verbatim as a line with the resolved (n, power) marked; omit entirely rather than invent points',
    },
    blurb:
      'Statistical power / sample-size calculator: a headline "n per group for X% power" solved from whichever of effect size, alpha, power, or a caller-given n is missing, plus an optional power-vs-n line (only drawn from real supplied points). Use before an experiment ("how many do we need") or after ("was this adequately powered").',
    domains: ['business', 'data', 'science'],
    intents: ['quantify', 'decide', 'plan'],
  }),
  createMeta('inventoryreorder', {
    family: 'stats',
    dataShapes: ['status', 'comparison'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'item', 'title'] }],
    propHints: {
      'items[].sku': 'the stock-keeping unit code, e.g. "SKU-4471"',
      'items[].level': 'current stock on hand — a real count, never a percentage',
      'items[].reorderPoint': 'the stock level that should trigger a purchase order',
      'items[].safetyStock': 'the minimum buffer never to dip below; omit to default to 0',
      'items[].max': "the track's full-scale ceiling (warehouse capacity or a comfortable max)",
      'items[].leadTimeDays': 'supplier lead time in days; omit when unknown',
    },
    blurb:
      'A supply-chain reorder dashboard: one row per SKU, a stock-level bar over a red/amber/green safety-stock/reorder-point track with a reorder tick — use for inventory health, never a plain progress bar.',
    domains: ['business', 'retail'],
    intents: ['track', 'decide'],
  }),
  createMeta('boardgamescore', {
    family: 'stats',
    dataShapes: ['tabular', 'ranking'],
    requires: ['title', 'players'],
    optional: ['icon', 'iconColor', 'game', 'rounds', 'footer'],
    interactive: false,
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'players', text: 'name', textAliases: ['player', 'label'] }],
    propHints: {
      'players[].roundScores':
        'number[], one entry per round played so far, oldest first — real scores only',
      'players[].total': 'the running total; when omitted it is summed from roundScores instead',
      rounds: 'total rounds to show; omit to size the grid to the longest roundScores',
    },
    blurb:
      'A tabletop scorepad: players × rounds grid like a physical score sheet, running total highlighted, current leader called out. Use for a game night or tournament tally, never a generic leaderboard.',
    domains: ['games', 'home'],
    intents: ['track', 'reference'],
  }),
  createMeta('cvssscorecard', {
    family: 'stats',
    dataShapes: ['scalar', 'status'],
    requires: ['title', 'baseScore', 'severity'],
    optional: ['icon', 'iconColor', 'vector', 'cve', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'vector', text: 'label', textAliases: ['metric', 'name', 'component'] }],
    propHints: {
      baseScore: 'the CVSS base score, 0.0–10.0 — a real reported score, never estimated',
      severity: "'none'|'low'|'medium'|'high'|'critical' — the CVSS qualitative rating band",
      'vector[].label':
        'the metric abbreviation, e.g. "AV" (Attack Vector), "PR" (Privileges Required)',
      'vector[].value': 'the metric\'s value, e.g. "Network", "Low", "None"',
      cve: 'the CVE identifier, e.g. "CVE-2024-21306"; omit when unknown',
    },
    blurb:
      'A CVSS vulnerability severity scorecard: a radial 0–10 base-score gauge colored by severity band, beside a compact chip row for the vector components (AV, AC, PR, UI, S, C, I, A). Use for a specific reported vulnerability, never a generic risk score.',
    domains: ['security', 'code'],
    intents: ['quantify', 'track'],
  }),
  createMeta('ridgeplot', {
    family: 'stats',
    dataShapes: ['distribution', 'comparison'],
    requires: ['title', 'categories'],
    optional: ['icon', 'iconColor', 'overlap', 'footer'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'categories', text: 'label', textAliases: ['name', 'series', 'group'] }],
    propHints: {
      'categories[].curve':
        'number[], ≥2 real, non-negative density/frequency samples evenly spaced along a shared x-axis — plotted verbatim, never smoothed or fit',
      overlap:
        "0..1, how far each ridge's peak rises into the row above (default 0.55); 0 keeps ridges flush, 1 gives heavy overlap",
    },
    blurb:
      'A ridge plot (joyplot): one density curve per category, stacked with a slight vertical overlap so shapes are easy to compare. Use to compare distribution SHAPE across 3+ groups, never a single distribution — use distributioncurve for that.',
    domains: ['data', 'science', 'business'],
    intents: ['quantify', 'explain'],
  }),
  createMeta('ecdf', {
    family: 'stats',
    dataShapes: ['distribution'],
    requires: ['title', 'values'],
    optional: ['icon', 'iconColor', 'unit', 'color', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    propHints: {
      values:
        'number[], the raw real sample values — sorted client-side into the real step function, never fit or smoothed',
    },
    blurb:
      "An empirical CDF: sorts real sample values and draws the actual stepped 0→1 cumulative-probability function. Use for a real, honest look at a distribution's spread (percentiles, tails) — never a smoothed density; use distributioncurve for that.",
    domains: ['data', 'science', 'business'],
    intents: ['quantify', 'explain'],
  }),
  createMeta('forestplot', {
    family: 'stats',
    dataShapes: ['comparison', 'distribution'],
    requires: ['studies'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'measure',
      'pooled',
      'heterogeneity',
      'favorsLeft',
      'favorsRight',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.84,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'studies',
        text: 'label',
        textAliases: ['name', 'study', 'trial'],
        requiredFields: ['effect', 'ciLow', 'ciHigh'],
      },
    ],
    propHints: {
      measure:
        "'OR' | 'RR' | 'HR' | 'MD' | 'SMD' — ratio measures (OR/RR/HR) plot on a log axis with the null line at 1; difference measures (MD/SMD) plot linearly with the null at 0. Default 'OR'.",
      'studies[].effect':
        "the point estimate on the measure's natural scale (an OR of 0.82, an MD of −3.1) — real reported values only",
      'studies[].ciLow': 'lower 95% interval bound, same scale as effect',
      'studies[].ciHigh': 'upper 95% interval bound, same scale as effect',
      'studies[].weight':
        'percent weight 0..100 (sizes the square marker); omit to size by the inverse-variance weight recovered from the CI',
      'studies[].year': 'publication year, shown after the label',
      pooled:
        '{ effect, ciLow, ciHigh, label? } — a caller-computed summary diamond; omit to have a fixed-effect inverse-variance pool computed from the study CIs',
      heterogeneity: "a real reported heterogeneity readout, e.g. 'I² = 34%' — never invented",
      favorsLeft: "left axis-end reading, e.g. 'Favors treatment'",
      favorsRight: "right axis-end reading, e.g. 'Favors control'",
    },
    blurb:
      'A meta-analysis forest plot: one row per study (square marker sized by weight over its 95% CI whisker) on a shared axis with a dashed null line, plus a pooled summary diamond whose width is the pooled CI — computed as a fixed-effect inverse-variance pool when not supplied. For evidence synthesis across studies/experiments in an educational or research-methods frame. Never for simple group means with error bars — use errorbars.',
    intents: ['quantify', 'explain', 'teach', 'decide'],
    domains: ['science', 'data', 'education'],
  }),
];
