// Catalog entries for the `status` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_STATUS: ComponentCatalog = [
  createMeta('a11yaudit', {
    family: 'status',
    dataShapes: ['status', 'list'],
    requires: ['title', 'checks'],
    optional: ['icon', 'iconColor', 'score', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'checks', text: 'label', textAliases: ['name', 'title', 'check'] }],
    blurb:
      'Accessibility audit: a11y checks each marked pass/warn/fail with notes and an optional score.',
    propHints: {
      'checks[].status':
        "'pass'|'warn'|'fail' (drives the coloured badge: pass=green, warn=amber, fail=red)",
      score: "optional overall score string, e.g. '82/100' or 'AA'",
    },
    intents: ['reference', 'decide', 'track'],
  }),
  // — status —
  createMeta('progressbar', {
    family: 'status',
    dataShapes: ['status'],
    requires: ['title', 'segments'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.65,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'segments', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Multi-segment milestone bar showing progress through workflow stages.',
  }),
  createMeta('stepindicator', {
    family: 'status',
    dataShapes: ['status', 'sequence'],
    requires: ['title', 'steps'],
    optional: ['icon', 'iconColor', 'orientation', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'steps', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Clickable step workflow showing done/active/locked progression.',
    propHints: {
      'steps[].state': "'done'|'active'|'locked'",
    },
  }),
  createMeta('statustimeline', {
    family: 'status',
    dataShapes: ['status', 'sequence'],
    requires: ['title', 'events'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'events', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Timeline of timestamped events with filterable status badges.',
    propHints: {
      'events[].status': "'pending'|'progress'|'done'|'failed' (drives the badge + filter chips)",
    },
  }),
  createMeta('healthgrid', {
    family: 'status',
    dataShapes: ['status', 'composition'],
    requires: ['title', 'cells'],
    optional: ['icon', 'iconColor', 'cols', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'cells',
        text: 'label',
        textAliases: ['name', 'title'],
        requiredFields: ['level'],
      },
    ],
    blurb: 'Grid of system health indicators (ok/warn/down) with hover details.',
    propHints: {
      'cells[].level': "'ok'|'warn'|'down'",
    },
  }),
  createMeta('emptystate', {
    family: 'status',
    dataShapes: ['status', 'action'],
    requires: ['title', 'headline'],
    optional: [
      'icon',
      'iconColor',
      'art',
      'copy',
      'action',
      'actionIcon',
      'secondary',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.6,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Illustrated empty state with headline, copy, and optional call-to-action.',
  }),
  createMeta('skeleton', {
    family: 'status',
    dataShapes: ['status'],
    requires: ['title'],
    optional: ['icon', 'iconColor', 'variant', 'rows', 'loadedLabel', 'footer'],
    interactive: true,
    wowWeight: 0.45,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Loading skeleton with shimmer animation and preview toggle.',
  }),
  createMeta('sliderinput', {
    family: 'status',
    dataShapes: ['selection', 'status'],
    requires: ['title', 'min', 'max'],
    optional: [
      'icon',
      'iconColor',
      'prompt',
      'step',
      'value',
      'prefix',
      'suffix',
      'marks',
      'outputLabel',
      'outputFactor',
      'outputPrefix',
      'outputSuffix',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'marks', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Draggable range slider with live value and optional derived output.',
  }),
  createMeta('segmented', {
    family: 'status',
    dataShapes: ['selection'],
    requires: ['title', 'options'],
    optional: ['icon', 'iconColor', 'selected', 'color', 'footer'],
    interactive: true,
    wowWeight: 0.58,
    tier: 'base',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'options', text: 'label', textAliases: ['name', 'title', 'text'] }],
    blurb: 'Segmented radio control with animated thumb and value preview.',
  }),
  createMeta('rangefilter', {
    family: 'status',
    dataShapes: ['selection', 'status'],
    requires: ['title', 'min', 'max', 'items'],
    optional: [
      'icon',
      'iconColor',
      'step',
      'low',
      'high',
      'prefix',
      'suffix',
      'unitLabel',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.73,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Dual-handle range slider with live-filtered item list and count.',
  }),
  createMeta('ratinginput', {
    family: 'status',
    dataShapes: ['selection', 'status'],
    requires: ['title'],
    optional: [
      'icon',
      'iconColor',
      'shape',
      'max',
      'value',
      'caption',
      'facets',
      'color',
      'footer',
    ],
    interactive: true,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'facets', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Interactive star/heart rating control with optional facet breakdowns.',
  }),
  createMeta('litigationtimeline', {
    family: 'status',
    dataShapes: ['status', 'sequence'],
    requires: ['title', 'events'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'events', text: 'kind', textAliases: ['type', 'category', 'stage', 'action'] },
    ],
    blurb:
      'Court-case docket rail: filings, motions, hearings, orders and deadlines with urgency-colored nodes and a live countdown on critical deadlines. Use for litigation status, never a generic project timeline.',
    propHints: {
      'events[].kind': "'filing'|'motion'|'hearing'|'order'|'deadline'",
      'events[].urgency': "'routine'|'soon'|'critical' (drives node color + filter chips)",
      'events[].court': 'the court/tribunal, e.g. "D. Del."',
      'events[].party': 'the filing/moving party, e.g. "Plaintiff"',
    },
    intents: ['track', 'reference'],
    domains: ['legal'],
  }),
  createMeta('billtracker', {
    family: 'status',
    dataShapes: ['status', 'sequence'],
    requires: ['title', 'bill', 'stages'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'stages', text: 'name', textAliases: ['label', 'title', 'step'] }],
    blurb:
      'Legislative bill status: a fixed Introduced → Committee → Floor Vote → Other Chamber → Signed rail, a dead-end glyph if it fails a stage, and a vote-tally chip under any stage with a recorded vote.',
    propHints: {
      'stages[].name': "'Introduced'|'Committee'|'Floor Vote'|'Other Chamber'|'Signed'",
      'stages[].status': "'done'|'current'|'pending'|'failed'",
      'stages[].voteTally': '{ yea: number, nay: number } — only on a stage with a recorded vote',
    },
    intents: ['track', 'reference'],
    domains: ['legal'],
  }),
  createMeta('triageboard', {
    family: 'status',
    dataShapes: ['status', 'ranking'],
    requires: ['title', 'patients'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'patients',
        text: 'chiefComplaint',
        textAliases: ['complaint', 'reason', 'presentation'],
        children: { prop: 'vitals', text: 'label', textAliases: ['name', 'vital', 'vitalSign'] },
      },
    ],
    blurb:
      'ER waiting-room acuity board: patients sorted most-urgent-first by Emergency Severity Index (1 = resuscitation, 5 = non-urgent), a big colored ESI badge, and optional vitals. Illustrative only, never real PHI.',
    propHints: {
      'patients[].esiLevel': '1-5 Emergency Severity Index, 1 = most urgent',
      'patients[].vitals[].abnormal': 'true flags the reading as out of normal range',
    },
    intents: ['track', 'decide'],
    domains: ['health'],
  }),
  createMeta('mentalhealthscreen', {
    family: 'status',
    dataShapes: ['status', 'scalar'],
    requires: ['title', 'instrument', 'items', 'total', 'maxTotal', 'bands'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'items', text: 'prompt', textAliases: ['question', 'text', 'item'] },
      { prop: 'bands', text: 'label', textAliases: ['name', 'severity'] },
    ],
    blurb:
      'Scored screening instrument (PHQ-9/GAD-7 style): a 0-3 dot-tick row per item, and a horizontal severity-banded bar with a marker landing on the total. Illustrative only, never a diagnosis.',
    propHints: {
      'items[].score': '0-3, 0 = not at all, 3 = nearly every day',
      'bands[].range': '[low, high] inclusive score range this severity band covers',
      'bands[].tone': "'ok'|'mild'|'moderate'|'severe'",
    },
    intents: ['track', 'reference'],
    domains: ['health', 'psychology'],
  }),
  createMeta('usabilityfindings', {
    family: 'status',
    dataShapes: ['status', 'list'],
    requires: ['title', 'issues'],
    optional: ['icon', 'iconColor', 'taskSuccessRate', 'avgTimeOnTask', 'footer'],
    interactive: false,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'issues', text: 'label', textAliases: ['title', 'name', 'issue', 'finding'] },
    ],
    blurb:
      'UX research test summary: task-success rate and time-on-task up top, then usability issues severity-badged critical/major/minor with affected-user counts.',
    propHints: {
      'issues[].severity': "'critical'|'major'|'minor'",
      taskSuccessRate: '0-100, percent of participants who completed the task',
      avgTimeOnTask: 'pre-formatted, e.g. "3m 42s"',
    },
    intents: ['track', 'reference'],
    domains: ['design', 'business'],
  }),
  createMeta('roomblockdashboard', {
    family: 'status',
    dataShapes: ['status', 'composition'],
    requires: ['title', 'cells'],
    optional: ['icon', 'iconColor', 'cols', 'footer'],
    interactive: true,
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'cells', text: 'label', textAliases: ['name', 'room', 'title'] }],
    blurb:
      'Event/hotel room-block occupancy grid: held vs booked vs checked-in vs open, with a legend and a "N/N rooms committed" banner. Use for a block of rooms held for an event, not a single reservation.',
    propHints: {
      'cells[].level': "'held'|'booked'|'checked-in'|'open'",
    },
    intents: ['track', 'reference'],
    domains: ['travel', 'business'],
  }),
  createMeta('immigrationcase', {
    family: 'status',
    dataShapes: ['status', 'sequence'],
    requires: ['title', 'visaCategory', 'stages'],
    optional: ['icon', 'iconColor', 'priorityDate', 'rfeDeadline', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'stages', text: 'name', textAliases: ['label', 'title', 'step'] }],
    blurb:
      'Visa/petition case status rail: filing stages done/current/pending/failed, a priority-date readout, and an RFE response countdown when one is outstanding.',
    propHints: {
      'stages[].status': "'done'|'current'|'pending'|'failed'",
      rfeDeadline: 'the Request for Evidence response due date, if one is outstanding',
    },
    intents: ['track', 'reference'],
    domains: ['legal'],
  }),
  createMeta('painscale', {
    family: 'status',
    dataShapes: ['status', 'scalar'],
    requires: ['value'],
    optional: ['title', 'icon', 'iconColor', 'kind', 'anchors', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb: 'Clinical pain rating — Wong-Baker FACES or a 0–10 visual-analog scale.',
    intents: ['reference', 'reflect'],
    domains: ['health'],
    propHints: {
      value: '0..10 (0 = no pain, 10 = worst pain)',
      kind: "'faces' (six Wong-Baker faces, default) | 'vas' (visual-analog 0–10 bar)",
    },
    stringItems: ['anchors'],
  }),
  createMeta('habittracker', {
    family: 'status',
    dataShapes: ['status', 'tabular'],
    requires: ['habits'],
    optional: ['title', 'icon', 'iconColor', 'days', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'habits', text: 'name', textAliases: ['label', 'title'] }],
    blurb: 'Weekly multi-habit grid with per-habit completion rings and a week summary.',
    intents: ['track'],
    domains: ['productivity', 'health'],
    propHints: {
      'habits[].done': 'array of booleans, one per day, aligned to `days` (default Mon..Sun)',
    },
    stringItems: ['days'],
  }),
  createMeta('streakgrid', {
    family: 'status',
    dataShapes: ['status', 'series'],
    requires: ['days'],
    optional: ['title', 'icon', 'iconColor', 'habit', 'current', 'best', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 6,
    colMin: 5,
    coercer: 'generic',
    blurb:
      "Habit-streak card — recent-day dots, current/best counters, don't-break-the-chain framing.",
    intents: ['track'],
    domains: ['fitness', 'productivity'],
    propHints: {
      'days[].done': 'boolean — whether the habit was kept that day (oldest → newest)',
    },
  }),
];
