// Catalog entries for the `tables` family — the fact sheet the Live selector retrieves over
// and the prompt menu is built from. This module carries the DETAIL fields (blurb, requires,
// optional, item shapes, prop hints); the compact selection facts are generated from it into
// facts.generated.ts. It is loaded lazily, only for the families a turn actually reaches, which is
// what keeps per-turn cost proportional to the answer rather than to the library.
//
// After editing, run `pnpm gen:catalog` — a staleness test fails the build otherwise.
import { createMeta, type ComponentCatalog } from '../meta';

export const CATALOG_TABLES: ComponentCatalog = [
  // — tables —
  createMeta('datatable', {
    family: 'tables',
    dataShapes: ['tabular'],
    archetype: 'table',
    caps: ['currency', 'percent', 'total-row', 'status-color', 'in-cell-bar', 'sort', 'search'],
    requires: ['title', 'columns', 'rows'],
    optional: [
      'icon',
      'iconColor',
      'sortKey',
      'sortDir',
      'searchable',
      'searchPlaceholder',
      'footer',
      'annotations',
    ],
    propHints: {
      annotations:
        'OPTIONAL closed-grammar adornments that turn a plain table into a receipt/ledger/scorecard. An array of {op,...}: {"op":"format","target":{"kind":"column","key":"<col>"},"as":"currency|percent|unit"}; {"op":"summary","stat":"total|mean|max|min","columns":["<col>"]} (WE compute it — never send the number); {"op":"emphasize","target":{"kind":"row","match":"<row label>"},"tone":"presence|insight|warning|danger"}; {"op":"status","target":{"kind":"column","key":"<col>"},"rules":[{"match":"<text>","tone":"danger"}]}; {"op":"bar","target":{"kind":"column","key":"<col>"}}. Reference only real column keys / row labels.',
    },
    interactive: true,
    wowWeight: 0.65,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Sortable, filterable table with search — annotate it (currency, totals, highlights).',
  }),
  createMeta('pivot', {
    family: 'tables',
    dataShapes: ['tabular', 'composition'],
    requires: ['title', 'rowGroup', 'colHeaders', 'measures', 'rows'],
    optional: ['icon', 'iconColor', 'measure', 'accent', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'Two-way crosstab (row category × column category) of ONE metric per view; color-scaled cells, togglable measures, row/col totals.',
    propHints: {
      colHeaders:
        'category labels across the top (quarters, regions, stages…) — the column dimension, NOT metric names',
      measures:
        "the metric(s) the toggle switches between; the active one fills every column. Different metrics (e.g. Revenue vs Margin) go HERE — never as separate colHeaders, which would just repeat a column. e.g. [{key:'rev',label:'Revenue'}]",
      'rows[].cells[].values':
        'object keyed by each measure.key → that metric at this row × column',
    },
    stringItems: ['colHeaders'],
  }),
  createMeta('leaderboard', {
    family: 'tables',
    dataShapes: ['ranking', 'comparison'],
    requires: ['title', 'metrics', 'rows'],
    optional: ['icon', 'iconColor', 'metric', 'accent', 'footer'],
    interactive: true,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'name', textAliases: ['label', 'title'] }],
    blurb: 'Ranked rows with medals, bars, and rank-movement indicators; toggle metrics.',
  }),
  createMeta('treetable', {
    family: 'tables',
    dataShapes: ['hierarchy', 'tabular'],
    requires: ['title', 'nodes'],
    optional: ['icon', 'iconColor', 'valueLabel', 'accent', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'nodes', text: 'label', children: { prop: 'children', text: 'label' } }],
    propHints: {
      'nodes[].value':
        'the row\'s own displayed amount, e.g. "¥1,000" — a SEPARATE field from label, never appended to it as text',
      'nodes[].pct':
        "0..1 share of the whole for the inline bar (e.g. this row's value ÷ the total) — omit rather than guess if there's no meaningful whole to share",
      valueLabel: 'header for the value column, e.g. "Budget" or "Revenue" (defaults to "Value")',
    },
    blurb: 'Hierarchical tree with expand/collapse rows, inline bars, and tags.',
  }),
  createMeta('swimlane', {
    family: 'tables',
    dataShapes: ['flow', 'sequence'],
    requires: ['title', 'lanes'],
    optional: ['icon', 'iconColor', 'ticks', 'footer'],
    interactive: true,
    wowWeight: 0.85,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'lanes',
        text: 'actor',
        textAliases: ['label', 'name', 'title'],
        children: { prop: 'events', text: 'label', textAliases: ['name', 'title', 'text'] },
      },
    ],
    blurb:
      'Concurrent processes as horizontal lanes, each owned by an ACTOR, with time-ordered events/bars across them (UML sequence, multi-team handoffs, request flow). Never for generic multi-row data — use datatable for tabular data.',
    stringItems: ['ticks'],
  }),
  createMeta('footnotetable', {
    family: 'tables',
    dataShapes: ['tabular'],
    requires: ['title', 'columns', 'rows', 'notes'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.58,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb: 'Table with clickable footnote anchors; footnotes show on hover/click.',
    stringItems: ['columns'],
  }),
  createMeta('sparktable', {
    family: 'tables',
    dataShapes: ['series', 'tabular'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'valueLabel', 'trendLabel', 'footer'],
    interactive: true,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'name', textAliases: ['label', 'title'] }],
    blurb:
      'Rows with inline sparklines, current value, and delta indicators; hover to probe trend.',
  }),
  createMeta('smallmultiples', {
    family: 'tables',
    dataShapes: ['series', 'comparison'],
    requires: ['title', 'panels'],
    optional: ['icon', 'iconColor', 'cols', 'kind', 'footer'],
    interactive: true,
    wowWeight: 0.82,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'panels', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Grid of same-scale mini bar or line charts; shared domain across all panels.',
  }),
  createMeta('comparebars', {
    family: 'tables',
    dataShapes: ['comparison', 'ranking'],
    requires: ['title', 'series', 'rows'],
    optional: ['icon', 'iconColor', 'highlight', 'footer'],
    interactive: true,
    wowWeight: 0.73,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'title'] }],
    blurb: 'Grouped horizontal bars per metric row; highlight a series to dim others.',
  }),
  createMeta('comparematrix', {
    family: 'tables',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'cols', 'rows'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    intents: ['compare', 'decide', 'explain', 'reference'],
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['attribute', 'dimension', 'name'] }],
    propHints: {
      cols: 'the things being compared, one column header each (e.g. ["Stoicism","Buddhism","Existentialism"]).',
      'rows[].cells':
        'one cell per column, in cols order; each {kind?:"text"|"yes"|"no"|"partial"|"rating", value?, note?}. "text"=a short phrase, "rating"=a 0–5 number, yes/no/partial render a verdict glyph (no value needed).',
      'rows[].best':
        'optional 0-based index of the column that wins this attribute; omit for a tie.',
    },
    blurb:
      'A qualitative side-by-side comparison grid: columns are the things compared, rows are attributes, cells hold a short value, a yes/no/partial verdict, or a 0–5 rating, and a row can flag its winner. Pick over matrix (a STEM value grid), comparebars (numeric bars), clearancematrix (safe/caution/avoid verdicts), or matrixgrid (a numeric heatmap) for "X vs Y vs Z", "how do these differ", or a decision across criteria — philosophies, systems, plans, candidates, characters.',
    stringItems: ['cols'],
  }),
  createMeta('matrixgrid', {
    family: 'tables',
    dataShapes: ['tabular', 'relationship'],
    requires: ['title', 'rowLabels', 'colLabels', 'cells'],
    optional: ['icon', 'iconColor', 'min', 'max', 'accent', 'diagonal', 'unit', 'legend', 'footer'],
    interactive: true,
    wowWeight: 0.8,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A 2D NUMERIC matrix rendered as a color-scaled grid (heat map, confusion matrix, correlation); optional diagonal mark and legend ramp. Never for a table of text/labels — use datatable.',
    stringItems: ['rowLabels', 'colLabels'],
  }),
  createMeta('clearancematrix', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison', 'status'],
    requires: ['title', 'rows', 'columns', 'cells'],
    optional: ['icon', 'iconColor', 'legend', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'An item × constraint grid rating each pairing safe / caution / avoid / unknown with a one-line reason; avoid cells stand out and unrated pairs show "check a pro". Pick over ingredientmatrix (boolean overlap) or matrixgrid (heatmapped numbers) when each pairing needs a verdict plus its why — drug/supplement interactions, allergen checks, material compatibility.',
    itemShapes: [{ prop: 'cells', text: 'reason', textAliases: ['why', 'note', 'detail'] }],
    propHints: {
      'cells[].row': 'must match one of `rows` (matched case/space-insensitively)',
      'cells[].col': 'must match one of `columns`',
      'cells[].level': "'safe'|'caution'|'avoid'|'unknown'",
      'cells[].reason': 'one short line of why, e.g. "raises bleeding risk"',
      legend: 'true|false — show the verdict key below the grid',
    },
    intents: ['decide', 'reference', 'compare', 'explain'],
    stringItems: ['rows', 'columns'],
  }),
  createMeta('matrix', {
    family: 'tables',
    dataShapes: ['tabular', 'hierarchy'],
    requires: ['title', 'rows'],
    optional: ['icon', 'iconColor', 'caption', 'corner', 'cols', 'bracket', 'footer'],
    tier: 'frontier',
    wowWeight: 0.72,
    blurb:
      'A general labeled value grid for linear algebra, truth tables, Punnett squares, or confusion matrices.',
    coercer: 'generic',
    stringItems: ['cols'],
  }),
  createMeta('sensitivitytable', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison'],
    requires: ['title', 'rowVar', 'rows', 'colVar', 'cols', 'cells'],
    optional: ['icon', 'iconColor', 'unit', 'currency', 'higherBetter', 'baseCell', 'footer'],
    interactive: false,
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'What-if sensitivity grid; rows × columns of parameter values, cells heatmapped by output.',
    propHints: {
      rowVar: 'label for the row-axis variable, e.g. "Discount Rate"',
      colVar: 'label for the column-axis variable, e.g. "Growth Rate"',
      baseCell: '[rowIndex, colIndex] of the base/expected-case cell',
    },
  }),
  createMeta('labpanel', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'results'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.75,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'Lab test results panel; each row shows test name, value, reference range, and high/low flag.',
    itemShapes: [{ prop: 'results', text: 'name', textAliases: ['test', 'analyte', 'label'] }],
    propHints: {
      'results[].low': 'lower bound of the reference interval',
      'results[].high': 'upper bound of the reference interval',
      'results[].prior': 'optional prior value for a trend arrow',
    },
  }),
  // tables — cooking
  createMeta('ingredientmatrix', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison'],
    requires: ['title', 'recipes', 'ingredients', 'matrix'],
    optional: ['icon', 'iconColor', 'quantities', 'highlight', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'An ingredient × recipe overlap table — checkmarks where an ingredient appears in a recipe. Use for shopping list optimization, meal-prep planning, or recipe comparison.',
    stringItems: ['recipes', 'ingredients'],
  }),
  createMeta('conjugation', {
    family: 'tables',
    dataShapes: ['tabular', 'list'],
    requires: ['title', 'verb', 'tenses'],
    optional: ['language', 'note'],
    interactive: false,
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A verb conjugation table across persons and tenses — pronouns as row headers, tenses as column groups. Irregular forms are highlighted. Works for any language.',
    propHints: {
      verb: 'the infinitive form, e.g. "hablar"',
      language: 'e.g. "Spanish", "French", "Latin"',
      'tenses[].name': 'tense name, e.g. "Present", "Preterite"',
      'tenses[].forms': 'array of {pronoun, form, irregular?}',
    },
  }),
  createMeta('financialstatement', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison'],
    requires: ['periods', 'rows'],
    optional: ['title', 'icon', 'iconColor', 'currency', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      "A multi-period financial statement (P&L / balance sheet / cash flow): a left label column indented by nesting, one right-aligned currency column per period, subtotal/total rows ruled + bold, negatives in accountant's parentheses. Pick for revenue/expense/cash breakdowns across quarters or years.",
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'line', 'item'] }],
    propHints: {
      periods: 'column headers left→right, e.g. ["Q1 FY25","Q2 FY25","Q3 FY25"]',
      'rows[].values':
        'one number per period, same order as `periods`; use a negative for a cost/outflow',
      'rows[].kind':
        "'line'|'subtotal'|'total' — subtotal/total get a top rule + bold; total is tinted",
      'rows[].indent': 'integer ≥0 — indent the label under a subtotal (each level ≈14px)',
      currency: 'ISO 4217 code, e.g. "USD", "EUR" (default USD)',
    },
    intents: ['quantify', 'explain', 'reference'],
    domains: ['money', 'business'],
    stringItems: ['periods'],
  }),
  createMeta('cohortgrid', {
    family: 'tables',
    dataShapes: ['tabular', 'series'],
    requires: ['cohorts'],
    optional: ['title', 'icon', 'iconColor', 'periods', 'unit', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    blurb:
      'A cohort-retention triangle: rows are cohorts (label + size), columns are periods-since-start (0..N), each cell heat-shaded by its value and the ragged later-cohorts edge left blank, with a per-column average footer. Pick for retention / churn decay by signup month or any "how does cohort X hold up over time".',
    itemShapes: [{ prop: 'cohorts', text: 'label', textAliases: ['name', 'cohort', 'month'] }],
    propHints: {
      'cohorts[].values':
        'value per period-since-start; use null for an unobserved (future) cell so the triangle stays ragged',
      'cohorts[].size': 'cohort size (e.g. signups), shown beside the label',
      periods:
        'optional column headers, e.g. ["M0","M1","M2"]; defaults to M0…Mn sized to the widest cohort',
      unit: "suffix on each cell, default '%'",
    },
    intents: ['track', 'quantify'],
    domains: ['business', 'data'],
    stringItems: ['periods'],
  }),
  createMeta('riskmatrix', {
    family: 'tables',
    dataShapes: ['comparison', 'distribution', 'status'],
    requires: ['risks'],
    optional: ['title', 'icon', 'iconColor', 'size', 'caption', 'footer'],
    interactive: true,
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A likelihood × impact risk matrix: an N×N grid RAG-banded (green→amber→red) by likelihood×impact, each risk plotted as a labeled chip in its cell, with a register below pairing each risk to its owner + mitigation. Pick for launch/project/security risk reviews and any "what could go wrong and how bad".',
    itemShapes: [{ prop: 'risks', text: 'label', textAliases: ['name', 'risk', 'title'] }],
    propHints: {
      'risks[].likelihood': 'integer 1 (rare) … 5 (almost certain)',
      'risks[].impact': 'integer 1 (negligible) … 5 (severe)',
      'risks[].owner': 'who owns the risk, e.g. "Platform", "GTM"',
      'risks[].mitigation': 'one-line plan to reduce or absorb it',
      size: '3 | 4 | 5 — grid dimension (default 5)',
    },
    intents: ['decide', 'track', 'quantify'],
    domains: ['business', 'productivity'],
  }),
  createMeta('careplan', {
    family: 'tables',
    dataShapes: ['tabular', 'sequence', 'status'],
    requires: ['entries'],
    optional: ['title', 'icon', 'iconColor', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 12,
    colMin: 8,
    coercer: 'generic',
    blurb:
      'A nursing care-plan board: one row per patient problem read left→right through the nursing process — Assessment/Dx → Goal → Interventions → Rationale → Evaluation — with an outcome chip (met/partial/ongoing) on each goal. For nursing care plans, clinical handoffs, and nursing-school teaching.',
    itemShapes: [{ prop: 'entries', text: 'assessment', textAliases: ['cue', 'problem', 'data'] }],
    propHints: {
      'entries[].diagnosis': 'the nursing diagnosis / problem statement',
      'entries[].goal': 'the expected outcome the plan works toward',
      'entries[].interventions': 'array of nursing interventions (one string each)',
      'entries[].rationale': 'why those interventions work (the evidence)',
      'entries[].status': "'met'|'partial'|'ongoing' — outcome at evaluation",
    },
    intents: ['plan', 'track', 'reference'],
    domains: ['health'],
  }),
  createMeta('doseladder', {
    family: 'tables',
    dataShapes: ['sequence', 'tabular', 'keyvalue'],
    requires: ['drug', 'ladder'],
    optional: [
      'title',
      'icon',
      'iconColor',
      'route',
      'computed',
      'adjustments',
      'caption',
      'footer',
    ],
    interactive: false,
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    blurb:
      'A medication dosing / titration visual: an optional weight/eGFR-based starting-dose readout (input → result with the formula shown), a stepped titration ladder where the ceiling rung is marked, and a banded renal/hepatic dose-adjustment lookup. For drug titration schedules, weight-based dosing, and dose-adjustment reference.',
    itemShapes: [{ prop: 'ladder', text: 'step', textAliases: ['stage', 'phase', 'label'] }],
    propHints: {
      drug: 'the medication name',
      route: 'route of administration, e.g. "oral", "IV"',
      'computed.input': 'the patient input the dose is derived from, e.g. "Weight 72 kg"',
      'computed.formula': 'the dosing rule applied, e.g. "0.1 mg/kg"',
      'computed.result': 'the resulting starting dose, e.g. "7.2 mg"',
      'ladder[].dose': 'the dose at this rung, e.g. "25 mg daily"',
      'ladder[].ceiling': 'true to mark this rung as the dosing ceiling (the max)',
      'adjustments[].condition': 'the organ-function band, e.g. "eGFR 30–59"',
      'adjustments[].change': 'the dose change for that band, e.g. "Reduce by 50%"',
    },
    intents: ['quantify', 'howto', 'reference'],
    domains: ['health'],
  }),
  createMeta('sizechart', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison'],
    requires: ['columns', 'rows'],
    optional: ['title', 'icon', 'iconColor', 'unit', 'highlight', 'guide', 'caption', 'footer'],
    interactive: false,
    wowWeight: 0.66,
    tier: 'base',
    colDefault: 8,
    colMin: 5,
    coercer: 'generic',
    blurb:
      'An apparel/footwear size comparison chart — one row per size mapped across systems and measurements (US · UK · EU · cm), with an optional highlighted size and a how-to-measure guide. Use for shopping, fit, and size-conversion asks.',
    intents: ['reference', 'decide'],
    domains: ['shopping', 'home'],
    stringItems: ['columns'],
  }),
  createMeta('pricingtable', {
    family: 'tables',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'plans', 'features'],
    optional: ['icon', 'iconColor', 'caption', 'footer'],
    wowWeight: 0.8,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      { prop: 'plans', text: 'name', textAliases: ['plan', 'tier', 'title'] },
      { prop: 'features', text: 'label', textAliases: ['feature', 'name'] },
    ],
    propHints: {
      'plans[].price': 'a short price string, e.g. "$29", "Free", "Custom" — not a bare number.',
      'plans[].period':
        'billing cadence after the price, e.g. "/mo", "/seat/mo". Omit for one-time or "Custom" prices.',
      'plans[].highlighted':
        'true for exactly one plan — the tier to spotlight with a "most popular" ribbon.',
      'features[].values':
        'one entry per plan, SAME order as `plans`: true/false for included/not, or a short string like "Up to 5 seats".',
    },
    blurb:
      'A tiered plan/pricing comparison: a rich header card per plan (price, tagline, CTA, a ribbon on the highlighted tier) over a feature grid, check/dash or a short value per plan. Pick over comparematrix (attribute-vs-option, no price cards) for SaaS tiers, membership levels, service packages — "which plan should I get".',
    intents: ['decide', 'compare', 'reference'],
    domains: ['business', 'money'],
  }),
  createMeta('raci', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'tasks', 'roles', 'cells'],
    optional: ['icon', 'iconColor', 'legend', 'footer'],
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    propHints: {
      'cells[].task': 'must match one of `tasks` (matched case/space-insensitively).',
      'cells[].role': 'must match one of `roles`.',
      'cells[].rating': "'R' (Responsible) | 'A' (Accountable) | 'C' (Consulted) | 'I' (Informed).",
      legend: 'true|false — show the R/A/C/I key below the grid.',
    },
    blurb:
      'A RACI responsibility matrix: tasks × roles, each pairing rated Responsible/Accountable/Consulted/Informed with a colored single-letter badge. Pick over clearancematrix (safe/caution/avoid verdicts) or swimlane (a timeline) for "who owns this", project ownership, program planning.',
    intents: ['plan', 'decide', 'reference'],
    domains: ['business'],
    stringItems: ['tasks', 'roles'],
  }),
  createMeta('rubric', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'criteria', 'levels', 'cells'],
    optional: ['icon', 'iconColor', 'scores', 'maxScore', 'footer'],
    wowWeight: 0.74,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [
      { prop: 'cells', text: 'descriptor', textAliases: ['text', 'detail', 'description'] },
    ],
    propHints: {
      'cells[].criterion': 'must match one of `criteria` (matched case/space-insensitively).',
      'cells[].level': 'must match one of `levels`.',
      'cells[].descriptor': 'one short line of what THIS level looks like for THIS criterion.',
      'cells[].achieved': 'true for the one level actually earned on this criterion.',
      'scores[].score': 'points earned for that criterion; pairs with `maxScore` for a total.',
    },
    blurb:
      'A grading rubric: criteria × performance levels, each cell the prose for what that level looks like; the level actually earned is tinted, with an optional trailing score column. Education, hiring, structured evaluation — "how is this graded", "what does a 4/5 look like here".',
    intents: ['explain', 'reference', 'decide'],
    domains: ['education'],
    stringItems: ['criteria', 'levels'],
  }),
  createMeta('interviewscorecard', {
    family: 'tables',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'candidates', 'criteria', 'cells'],
    optional: ['icon', 'iconColor', 'scale', 'footer'],
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    propHints: {
      'cells[].candidate': 'must match one of `candidates` (matched case/space-insensitively).',
      'cells[].criterion': 'must match one of `criteria`.',
      'cells[].rating': 'a number within `scale` (defaults 1..5); higher is better.',
      'cells[].note': 'an optional one-line note shown under the rating.',
      scale: '{min:number,max:number} the rating scale every cell is drawn from.',
    },
    blurb:
      'An HR interview evaluation: candidates × criteria, each cell a color-scaled numeric rating with an optional note, plus a per-candidate average. Pick over comparematrix (qualitative, no numeric scale) for hiring panels — "how did each candidate score".',
    intents: ['decide', 'compare', 'reference'],
    domains: ['business'],
    stringItems: ['candidates', 'criteria'],
  }),
  createMeta('gradebook', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'students', 'assignments', 'cells'],
    optional: ['icon', 'iconColor', 'showClassAverage', 'footer'],
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 10,
    colMin: 7,
    coercer: 'generic',
    propHints: {
      'cells[].student': 'must match one of `students` (matched case/space-insensitively).',
      'cells[].assignment': 'must match one of `assignments`.',
      'cells[].maxScore': 'points the assignment is out of; defaults to 100.',
      showClassAverage: 'true|false — show a trailing class-average column (default true).',
    },
    blurb:
      'A class gradebook: students × assignments, each cell a score with its derived letter grade, plus a class-average readout. Education, teaching — "how is the class doing", "where does each student stand".',
    intents: ['track', 'reference', 'explain'],
    domains: ['education'],
    stringItems: ['students', 'assignments'],
  }),
  createMeta('datadictionary', {
    family: 'tables',
    dataShapes: ['tabular', 'keyvalue'],
    requires: ['title', 'variables'],
    optional: ['icon', 'iconColor', 'source', 'nRows', 'nCols', 'footer'],
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'variables', text: 'name', textAliases: ['column', 'field', 'key'] }],
    propHints: {
      'variables[].dtype': "'int'|'float'|'str'|'bool'|'category'|'datetime'",
      'variables[].unit': "e.g. 'ms', 'USD', 'kg' — omit for unitless fields",
      'variables[].missingPct': '0–100, the share of rows missing this variable',
      source: "the dataset/table this documents, e.g. 'eval_results.parquet'",
    },
    blurb:
      'A dataset variable reference / codebook: a monospace name column, a colored dtype pill, unit + description, and a thin per-row missing-data bar. Data science, research — "what\'s in this dataset", "explain this column", a methods-section variable table.',
    intents: ['reference', 'explain'],
    domains: ['data', 'science', 'business'],
  }),
  createMeta('ablationtable', {
    family: 'tables',
    dataShapes: ['comparison', 'tabular'],
    requires: ['baseline', 'baselineValue', 'metric', 'rows'],
    optional: ['title', 'icon', 'iconColor', 'higherBetter', 'footer'],
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'removed', textAliases: ['component', 'feature', 'name'] }],
    propHints: {
      baseline: "the full/unablated system's name, e.g. 'Transformer-v3 (full)'",
      baselineValue: "the full system's score on `metric` — every row is diffed against this",
      metric: "what's being measured, e.g. 'Accuracy (%)'",
      'rows[].delta': 'change vs. baselineValue; computed as value − baselineValue when omitted',
      'rows[].deltaDirection': "'better'|'worse' — inferred from the delta's sign when omitted",
      higherBetter: 'true|false — whether a larger metric value wins (default true)',
    },
    blurb:
      'An ML ablation-study comparison: the full model pinned at top, then one row per component removed, each diffed against it with a colored ±delta chip (danger when it regresses, presence when it improves). ML/data-science — "what does each piece actually contribute".',
    intents: ['explain', 'quantify', 'reference'],
    domains: ['data', 'science', 'code'],
  }),
  createMeta('spectrumtable', {
    family: 'tables',
    dataShapes: ['tabular', 'structure'],
    requires: ['technique', 'peaks'],
    optional: ['title', 'icon', 'iconColor', 'compound', 'solvent', 'footer'],
    wowWeight: 0.7,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'peaks', text: 'assignment', textAliases: ['label', 'group', 'fragment'] },
    ],
    propHints: {
      technique: "'nmr-1h'|'nmr-13c'|'ir'|'ms' — picks which columns render",
      'peaks[].x': 'δ (ppm) for NMR, wavenumber (cm⁻¹) for IR, m/z for MS',
      'peaks[].multiplicity': "NMR only, e.g. 's'|'d'|'t'|'q'|'dd'|'m'",
      'peaks[].integration': 'NMR only, the integrated proton count at this shift',
      'peaks[].intensity': 'IR/MS only, 0–100 relative peak height',
      solvent: "NMR only, e.g. 'CDCl3'",
    },
    blurb:
      'A spectroscopy peak-interpretation table (NMR/IR/MS): columns switch by technique — NMR shows shift/multiplicity/integration/assignment, IR shows wavenumber/intensity/functional-group, MS shows m/z/relative-abundance/fragment — over an optional tick-marked axis strip. Chemistry — "read this spectrum", "identify this compound".',
    intents: ['explain', 'reference'],
    domains: ['science', 'chemistry', 'education'],
  }),
  createMeta('fmeatable', {
    family: 'tables',
    dataShapes: ['ranking', 'tabular', 'status'],
    requires: ['items'],
    optional: ['title', 'icon', 'iconColor', 'footer'],
    wowWeight: 0.72,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'failureMode', textAliases: ['mode', 'failure', 'name'] }],
    propHints: {
      'items[].severity': '1 (none) … 10 (catastrophic)',
      'items[].occurrence': '1 (rare) … 10 (near-certain)',
      'items[].detection': '1 (certain to catch it) … 10 (no way to catch it)',
      'items[].action': 'the recommended fix',
    },
    blurb:
      'A Failure Mode and Effects Analysis: one row per failure mode, the Risk Priority Number (severity × occurrence × detection) always computed here and rows auto-sorted descending by it, with a danger rule marking the top 1–3 as "fix these first". Manufacturing, reliability/quality engineering — "what could fail, and which failure matters most".',
    intents: ['decide', 'track', 'quantify'],
    domains: ['business', 'science', 'productivity'],
  }),
  createMeta('billofmaterials', {
    family: 'tables',
    dataShapes: ['hierarchy', 'tabular'],
    requires: ['rows'],
    optional: ['title', 'icon', 'iconColor', 'currency', 'footer'],
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'part', 'item'] }],
    propHints: {
      'rows[].kind': "'part' (default)|'subassembly'|'total'",
      'rows[].indent':
        'integer ≥0 — nesting depth (each level ≈14px); a subassembly rolls up every part nested under it',
      'rows[].qty': 'part rows only; defaults to 1 when omitted but unitCost is given',
      'rows[].unitCost':
        'part rows only; extended cost (qty × unitCost) is always computed, never taken as input',
      currency: 'ISO 4217 code, e.g. "USD", "EUR" (default USD)',
    },
    blurb:
      'A hierarchical parts list with cost rollup: rows nest by indent, qty × unit cost is always computed into an extended-cost column, a subassembly row rolls up every part nested under it, and a total row is the grand total across every part. Manufacturing, hardware, procurement — "what does this build cost".',
    intents: ['quantify', 'reference', 'plan'],
    domains: ['business', 'science'],
  }),
  createMeta('complexitysummary', {
    family: 'tables',
    dataShapes: ['comparison', 'tabular'],
    requires: ['title', 'approaches'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'approaches', text: 'name', textAliases: ['approach', 'algorithm', 'method'] },
    ],
    propHints: {
      'approaches[].timeComplexity': 'Big-O time complexity, e.g. "O(n log n)"',
      'approaches[].spaceComplexity': 'Big-O space complexity, e.g. "O(n)"',
      'approaches[].notes': 'a short tradeoff, or when this approach is worth picking',
    },
    blurb:
      'A multi-approach Big-O comparison table: one row per named approach with its time/space complexity in monospace notation and a short tradeoff note. The wrap-up artifact at the end of a technical-interview walkthrough — "how do these approaches compare", "brute force vs. optimal".',
    intents: ['compare', 'explain', 'reference'],
    domains: ['code', 'education'],
  }),
  createMeta('expressionheatmap', {
    family: 'tables',
    dataShapes: ['tabular', 'relationship'],
    requires: ['title', 'genes', 'samples', 'values'],
    optional: ['icon', 'iconColor', 'clusterGenes', 'clusterSamples', 'scaleLabel', 'footer'],
    interactive: true,
    wowWeight: 0.78,
    tier: 'cutting',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    propHints: {
      genes: 'row labels — gene symbols, e.g. ["TP53","MYC","EGFR"]',
      samples: 'column labels — sample/condition names',
      values:
        'genes × samples log2 fold-change; values[i][j] pairs genes[i] with samples[j]. Negative = down-regulated, positive = up-regulated, 0 = unchanged.',
      clusterGenes: 'reserved, not yet implemented — rows always render in the given order',
      clusterSamples: 'reserved, not yet implemented — columns always render in the given order',
      scaleLabel: 'the scale caption, e.g. "log2 fold-change" (default)',
    },
    blurb:
      'A gene-expression heat map: genes × samples, each cell a log2 fold-change on a diverging blue↓/red↑ scale centered at zero. Molecular biology, bioinformatics — "read this expression panel", "which genes moved between conditions".',
    intents: ['explain', 'quantify', 'reference'],
    domains: ['science', 'biology', 'data'],
    stringItems: ['genes', 'samples'],
  }),
  createMeta('discoverytracker', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'requests'],
    optional: ['icon', 'iconColor', 'footer'],
    interactive: true,
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 9,
    colMin: 7,
    coercer: 'generic',
    itemShapes: [
      { prop: 'requests', text: 'description', textAliases: ['request', 'item', 'summary'] },
    ],
    propHints: {
      'requests[].num': 'the request number in the set, e.g. 4 for "RFP No. 4"',
      'requests[].status': "'outstanding'|'produced'|'objected'|'privileged'",
      'requests[].batesRange': 'the Bates range produced, e.g. "ACME-000412–000488"',
      'requests[].privilegeBasis':
        'the privilege ground asserted, e.g. "attorney work product" — only when status is privileged',
    },
    blurb:
      'A legal discovery request log: a sortable table with filter chips and a colored status badge per row (outstanding/produced/objected/privileged). Litigation, legal ops — "where does discovery stand".',
    intents: ['track', 'reference'],
    domains: ['business'],
  }),
  createMeta('dentaltreatmentplan', {
    family: 'tables',
    dataShapes: ['tabular', 'sequence'],
    requires: ['title', 'entries'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      { prop: 'entries', text: 'procedure', textAliases: ['treatment', 'name', 'description'] },
    ],
    propHints: {
      'entries[].tooth': 'the tooth being worked on, e.g. "#14", "UL6"',
      'entries[].priority': "'urgent'|'recommended'|'elective'",
      'entries[].visit': 'the visit this is scheduled for, e.g. "Visit 1" — rows group by this',
      'entries[].cost': 'a plain number; the per-visit and grand totals are always summed here',
    },
    blurb:
      'A dental treatment plan: entries grouped by visit, a priority-colored chip per row, and a running cost total that rolls up to a grand total. Dentistry, patient billing — "what\'s the plan, and what does it cost".',
    intents: ['plan', 'quantify'],
    domains: ['health'],
  }),
  createMeta('rollcall', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'bill', 'legislators'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.68,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'legislators',
        text: 'name',
        textAliases: ['legislator', 'member', 'representative'],
      },
    ],
    propHints: {
      'legislators[].party': 'any party/caucus label, e.g. "D", "R", "Green" — rows band by it',
      'legislators[].vote': "'yea'|'nay'|'present'|'absent'",
      bill: 'the measure being voted on, e.g. "H.R. 4521, Infrastructure Modernization Act"',
    },
    blurb:
      'A legislative roll-call vote: a header tally bar counted from the roster, party-line color banding, and a colored vote-glyph chip per legislator. Civics, legislative tracking — "how did the vote go".',
    intents: ['reference', 'track'],
    domains: ['business'],
  }),
  createMeta('collectiontracker', {
    family: 'tables',
    dataShapes: ['tabular', 'list'],
    requires: ['title', 'items'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.58,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'items', text: 'name', textAliases: ['item', 'piece', 'title'] }],
    propHints: {
      'items[].condition': "'mint'|'good'|'fair'",
      'items[].value': 'estimated current value, a plain number; omit if untracked',
    },
    blurb:
      'A hobbyist collection — stamps, coins, cards, vinyl. A summary strip (count + running value) then a responsive card grid with a condition badge per piece. Collecting, hobbies — "what\'s my collection worth".',
    intents: ['track', 'reference'],
    domains: ['lifestyle'],
  }),
  createMeta('cma', {
    family: 'tables',
    dataShapes: ['tabular', 'comparison'],
    requires: ['title', 'subject', 'comps', 'suggestedListPrice'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.76,
    tier: 'frontier',
    colDefault: 10,
    colMin: 8,
    coercer: 'generic',
    itemShapes: [
      {
        prop: 'comps',
        text: 'address',
        textAliases: ['property', 'comp', 'listing'],
        children: { prop: 'adjustments', text: 'label', textAliases: ['name', 'item', 'reason'] },
      },
    ],
    propHints: {
      subject: 'a plain object: { address, beds, baths, sqft, yearBuilt? }',
      'comps[].distance': 'miles from the subject property, a plain number',
      'comps[].adjustments[].amount':
        'signed dollars toward the subject value; negative when the comp outclasses the subject on that point. The adjusted price is always computed here as soldPrice + Σ(adjustments), never taken as input.',
      suggestedListPrice: 'a plain object: { low, high, point? }',
    },
    blurb:
      'A real-estate comparative market analysis: a subject KPI strip, a ruled comp table with signed adjustments in accountant\'s-parentheses style, and a highlighted suggested-list-price banner. Real estate — "what should this list for".',
    intents: ['decide', 'quantify'],
    domains: ['home', 'money'],
  }),
  createMeta('taxreturnsummary', {
    family: 'tables',
    dataShapes: ['tabular', 'scalar'],
    requires: ['title', 'filingStatus', 'taxYear', 'rows', 'refundOrOwed'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.66,
    tier: 'frontier',
    colDefault: 7,
    colMin: 5,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'label', textAliases: ['name', 'line', 'item'] }],
    propHints: {
      'rows[].kind':
        "'line'|'subtotal'|'total' — subtotal/total get a top rule + bold; total is tinted",
      'rows[].indent': 'integer ≥0 — indent the label under a subtotal (each level ≈14px)',
      refundOrOwed: "a plain object: { amount, direction }, direction is 'refund'|'owed'",
    },
    blurb:
      'A 1040-style filing summary — NOT the marginal-rate bracket chart. A single-column ledger from income lines down to the total, then a large highlighted refund/owed chip. Personal finance, tax prep — "what did the return come out to".',
    intents: ['quantify', 'reference'],
    domains: ['money'],
  }),
  createMeta('depreciationschedule', {
    family: 'tables',
    dataShapes: ['tabular', 'series'],
    requires: [
      'title',
      'assetDescription',
      'cost',
      'method',
      'usefulLife',
      'annualDepreciation',
      'rows',
    ],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.64,
    tier: 'frontier',
    colDefault: 9,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'rows', text: 'period', textAliases: ['year', 'label'] }],
    propHints: {
      method: "the depreciation method, e.g. 'Straight-line', '200% declining balance'",
      'rows[].endingBasis': 'the basis carried into the next period, running toward salvage value',
    },
    blurb:
      'A rental/business asset depreciation schedule — a direct sibling of Amortization\'s KPI-strip-then-table shape, basis paying down toward salvage value instead of a loan balance to zero. Accounting, rental property, small business — "how does this asset\'s basis run off".',
    intents: ['quantify', 'reference'],
    domains: ['money', 'business'],
  }),
  createMeta('vendortracker', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'vendors'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'vendors', text: 'name', textAliases: ['vendor', 'company'] }],
    propHints: {
      'vendors[].category': "'catering'|'venue'|'photo'|'av'|'decor'|'other'",
      'vendors[].status': "'inquired'|'booked'|'confirmed'",
    },
    blurb:
      'An event/wedding vendor tracker: a category icon and status pill per row, plus a two-segment payment bar showing the paid deposit against the balance due. Event planning, weddings — "who\'s booked, what\'s still owed".',
    intents: ['plan', 'track'],
    domains: ['lifestyle', 'money'],
  }),
  createMeta('sponsorshiptracker', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'deals'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.62,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'deals', text: 'brand', textAliases: ['sponsor', 'company', 'partner'] }],
    propHints: {
      'deals[].status': "'pitched'|'negotiating'|'contracted'|'delivered'|'paid'",
      'deals[].currency': 'ISO 4217 code, e.g. "USD" (default USD)',
    },
    blurb:
      'A content-creator sponsorship/brand-deal tracker: a status pill per row, a right-aligned rate column, and a paid/unpaid accent bar. Creator economy, freelance — "what\'s owed, and by whom".',
    intents: ['track', 'quantify'],
    domains: ['money', 'media'],
  }),
  createMeta('caseload', {
    family: 'tables',
    dataShapes: ['tabular', 'status'],
    requires: ['title', 'cases'],
    optional: ['icon', 'iconColor', 'footer'],
    wowWeight: 0.58,
    tier: 'frontier',
    colDefault: 8,
    colMin: 6,
    coercer: 'generic',
    itemShapes: [{ prop: 'cases', text: 'clientRef', textAliases: ['client', 'ref', 'caseId'] }],
    propHints: {
      clientRef: 'a case reference or initials — NEVER a full client name (confidentiality)',
      'cases[].riskLevel': "'low'|'medium'|'high' — omit when a case hasn't been assessed yet",
    },
    blurb:
      'A social-worker caseload: one row per client (a case reference or initials, never a full name), a risk-flag badge banded like a risk matrix, and the next scheduled contact. Social work, case management — "where does each case stand, who needs attention first".',
    intents: ['track', 'reference'],
    domains: ['health'],
  }),
];
